In [1]:
import pandas as pd

In [2]:
# dataframe
data = {'country': ['Belgium', 'France', 'Germany', 'Netherlands', 'United Kingdom'],
        'population': [11.3, 64.3, 81.3, 16.9, 64.9],
        'area': [30510, 671308, 357050, 41526, 244820],
        'capital': ['Brussels', 'Paris', 'Berlin', 'Amsterdam', 'London']}
countries = pd.DataFrame(data)
countries = countries.set_index('country') # 인덱스 지정
countries

                population    area    capital
country
Belgium               11.3   30510   Brussels
France                64.3  671308      Paris
Germany               81.3  357050     Berlin
Netherlands           16.9   41526  Amsterdam
United Kingdom        64.9  244820     London

In [3]:
countries.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Belgium to United Kingdom
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   population  5 non-null      float64
 1   area        5 non-null      int64
 2   capital     5 non-null      object
dtypes: float64(1), int64(1), object(1)
memory usage: 160.0+ bytes

---

<div class="alert alert-success">
    <b>EXERCISE</b>: 인구밀도를 의미하는 `density` 칼럼을 추가하세요. (주의: 현재 'population' 칼럼은 100만 단위로 표기되어 있습니다)  
  
</div>

In [18]:
countries['density'] = countries["population"]/countries["area"] * 1000000

In [19]:
countries

                population    area    capital     density
country
Belgium               11.3   30510   Brussels  370.370370
France                64.3  671308      Paris   95.783158
Germany               81.3  357050     Berlin  227.699202
Netherlands           16.9   41526  Amsterdam  406.973944
United Kingdom        64.9  244820     London  265.092721

<div class="alert alert-success">
    <b>EXERCISE</b>: 인구밀도가 300을 초과하는 국가(country)의 수도(capital)과 인구(population)을 선택해주세요.  
  
</div>

In [24]:
countries.loc[(countries['density'] > 300), ["capital", "population"]]

               capital  population
country
Belgium       Brussels        11.3
Netherlands  Amsterdam        16.9

<div class="alert alert-success">
    <b>EXERCISE</b>: 'density_ratio' 칼럼을 추가해주세요. (density_ratio = 인구밀도/평균 인구밀도)
</div>

In [25]:
countries['density_ratio'] = countries['density']/countries['density'].mean()

In [26]:
countries

                population    area    capital     density  density_ratio
country
Belgium               11.3   30510   Brussels  370.370370       1.355755
France                64.3  671308      Paris   95.783158       0.350618
Germany               81.3  357050     Berlin  227.699202       0.833502
Netherlands           16.9   41526  Amsterdam  406.973944       1.489744
United Kingdom        64.9  244820     London  265.092721       0.970382

<div class="alert alert-success">
    <b>EXERCISE</b>: 영국(United Kingdom)의 수도(capital)를 'Cambridge'로 변경해주세요.
</div>

In [40]:
countries.loc["United Kingdom", 'capital'] = "Cambridge"

In [41]:
countries

                population    area    capital     density  density_ratio
country
Belgium               11.3   30510   Brussels  370.370370       1.355755
France                64.3  671308      Paris   95.783158       0.350618
Germany               81.3  357050     Berlin  227.699202       0.833502
Netherlands           16.9   41526  Amsterdam  406.973944       1.489744
United Kingdom        64.9  244820  Cambridge  265.092721       0.970382

<div class="alert alert-success">
    <b>EXERCISE</b>: 인구 밀도가 100 초과, 300 미만인 국가들을 표시해주세요.  
</div>

In [42]:
countries.loc[(countries['density'] < 300) & (countries['density'] > 100)]

                population    area    capital     density  density_ratio
country
Germany               81.3  357050     Berlin  227.699202       0.833502
United Kingdom        64.9  244820  Cambridge  265.092721       0.970382

<div class="alert alert-success">
    <b>EXERCISE</b>: 수도가 7글자 이상인 국가들을 표시해주세요. (힌트: string의 len( )를 사용하세요.)
</div>

In [53]:
countries.loc[(countries['capital'].str.len() > 7)]

                population    area    capital     density  density_ratio
country
Belgium               11.3   30510   Brussels  370.370370       1.355755
Netherlands           16.9   41526  Amsterdam  406.973944       1.489744
United Kingdom        64.9  244820  Cambridge  265.092721       0.970382

<div class="alert alert-success">
    <b>EXERCISE</b>: 수도에 'am' 이 포함되는 국가들을 표시해주세요. (힌트: string의 contains( )를 사용하세요.)
</div>

In [54]:
countries.loc[(countries['capital'].str.contains("am"))]

                population    area    capital     density  density_ratio
country
Netherlands           16.9   41526  Amsterdam  406.973944       1.489744
United Kingdom        64.9  244820  Cambridge  265.092721       0.970382

# 영화리뷰 데이터에서 자료 찾기

movie_title_data.tsv 읽어오기

https://drive.google.com/file/d/1cvBtLVyfhfodJK-BXWqBLcopyus9HOIc/view?usp=sharing

In [63]:
titles = pd.read_table("./data/movie_title_data.tsv")

C:\Users\Admin\AppData\Local\Temp\ipykernel_11932\132108640.py:1: DtypeWarning: Columns (4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  titles = pd.read_table("./data/movie_title_data.tsv")

<div class="alert alert-success">
    <b>EXERCISE</b>: titles 데이터프레임에는 몇 개의 영화가 기록되어 있나요?
</div>

In [64]:
titles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8407399 entries, 0 to 8407398
Data columns (total 9 columns):
 #   Column          Dtype
---  ------          -----
 0   tconst          object
 1   titleType       object
 2   primaryTitle    object
 3   originalTitle   object
 4   isAdult         object
 5   startYear       object
 6   endYear         object
 7   runtimeMinutes  object
 8   genres          object
dtypes: object(9)
memory usage: 577.3+ MB

In [65]:
titles.columns

Index(['tconst', 'titleType', 'primaryTitle', 'originalTitle', 'isAdult',
       'startYear', 'endYear', 'runtimeMinutes', 'genres'],
      dtype='object')

In [66]:
titles.value_counts("originalTitle")

originalTitle
Episode #1.1            41344
Episode #1.2            37283
Episode #1.3            35175
Episode #1.4            31782
Episode #1.5            28991
                        ...
öregHarcos                  1
öregHarcos II               1
über den Wolken             1
überRICH                    1
ülker Dankek Reklami        1
Name: count, Length: 4019695, dtype: int64

<div class="alert alert-success">
    <b>EXERCISE</b>: titles에서 가장 빠른 시기에 제작된 영화 두 개를 표시하세요.  힌트: .sort_values()
</div>

In [69]:
titles.sort_values(by='endYear', ascending=True)[:2]

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
5851663,tt4344414,tvSeries,Grace Voss,Grace Voss,0,1931,1932,15,Drama
5850008,tt4340818,tvSeries,Doris Sharp,Doris Sharp,0,1931,1932,15,Music

<div class="alert alert-success">
    <b>EXERCISE</b>: 제목(title)이 "Hamlet"인 영화는 몇 개가 있나요?
</div>

In [71]:
titles.loc[(titles["originalTitle"] == "Hamlet")]

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
594,tt0000598,short,"Hamlet, Prince of Denmark",Hamlet,0,1907,\N,10,"Drama,Short"
876,tt0000886,movie,"Hamlet, Prince of Denmark",Hamlet,0,1910,\N,\N,Drama
1228,tt0001240,movie,Hamlet,Hamlet,0,1911,\N,\N,Drama
1229,tt0001241,short,Hamlet,Hamlet,0,1910,\N,20,"Drama,Short"
1230,tt0001242,short,Hamlet,Hamlet,0,1908,\N,\N,"Drama,Short"
...,...,...,...,...,...,...,...,...,...
7347169,tt7656792,tvEpisode,Hamlet,Hamlet,0,2017,\N,\N,Animation
7413345,tt7798632,movie,Hamlet,Hamlet,0,\N,\N,\N,Comedy
7476376,tt7934018,tvMovie,Hamlet,Hamlet,0,1983,\N,\N,Drama
7609545,tt8219328,tvMovie,Hamlet,Hamlet,0,2018,\N,191,Drama
8306453,tt9703966,movie,Hamlet,Hamlet,0,\N,\N,\N,Drama

<div class="alert alert-success">
    <b>EXERCISE</b>: 제목(title)이 "Treasure Island"인 영화를 제작년도(year)의 오름차순에 따라 표시하세요
</div>

In [ ]:
titles.loc[(titles["originalTitle"] == "Treasure Island")]

<div class="alert alert-success">
    <b>EXERCISE</b>: 1950년에서 1959년 사이 몇 개의 영화가 만들어졌나요?(1950 <= 제작년도 <= 1959)
</div>

# 타이타닉 자료에서 그룹별 연산하기

원격 DB에 접속해서 titanic 데이터베이스 안에 있는 p_info, t_info, survived 테이블을 불러와 합치고 아래의 문제를 풀어보세요.<br>
<id:kict00, pw:kict00, ip:221.155.18.165:3306, db:titanic>

<div class="alert alert-success">
    <b>EXERCISE</b>: 데이터의 상위 5개 행을 출력하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 데이터의 정보(info)를 출력하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 데이터의 기술통계(describe)를 확인하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 처음 100명의 데이터를 출력하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 인덱스가 10~20인 데이터를 출력하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 컬럼 이름을 모두 출력하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 데이터의 shape를 확인하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Age' 컬럼의 평균을 구하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Survived' 컬럼의 고유값을 확인하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 나이가 30 이상인 승객만 출력하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 성별이 'female'이고 생존한 승객만 출력하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 나이가 10살 이하이고 요금이 20 이상인 승객을 출력하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 나이가 결측치인 데이터를 출력하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 나이를 기준으로 오름차순 정렬하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 요금을 기준으로 내림차순 정렬하고 상위 5명만 출력하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 성별로 그룹화하여 생존률 평균을 구하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: Pclass별 평균 나이를 구하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Age'에 10을 더한 값을 새로운 컬럼 'Age_plus_10'으로 추가하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Age'가 18 이상이면 '성인', 아니면 '미성년'으로 분류하는 컬럼을 추가하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Age'의 결측치를 평균으로 채우세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Cabin' 컬럼의 결측치를 'Unknown'으로 채우세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 중복된 'Ticket' 값을 제거하고 몇 개가 남는지 출력하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Embarked' 컬럼의 고유값과 각각의 개수를 출력하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 인덱스를 'PassengerId'로 설정하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 인덱스를 초기화하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 성별과 Pclass의 생존률을 피벗 테이블로 만드세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: groupby()를 사용하여 각 성별(sex)의 평균 나이(age)를 구하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 전체 승객(passenger)의 평균 생존율을 구하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 25세 이하 승객의 생존율을 구하세요. (힌트: 불리언 인덱싱)
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 남성의 생존율을 구하세요. 여성의 생존율을 구하세요. (힌트: 불리언 인덱싱)
</div>

<div class="alert alert-success">
    <b>EXERCISE</b>: 생존율을 구하는 함수가 작성되어 있습니다. 성별 생존율을 groupby를 활용해 구하기 위해 ?부분을 알맞게 채워주세요.
</div>

In [49]:
def survival_ratio(survived):
    return survived.sum() / len(survived)