# pandas

In [1]:
# pip install pandas
# conda install pandas

* numpy를 내부적으로 활용함
* 데이터 분석에 특화된 데이터 구조 제공(테이블, dataframe)
* 다양한 데이터 분석 함수 제공
* 데이터베이스에 쉽게 연결 가능
* json 데이터 html의 table요소를 dataframe으로 손쉽게 변형 가능

# pandas에서 다루는 데이터 타입 2가지
## 1) DataFrame: 2차원의 표형식 데이터 
* python의 dict와도 비슷 하나의 key에 list 형태의 value가 매칭되어 있는 형태
* {key : [value1, value2, value3], key2 : [value1, value2, value3]}
## 2) Series: 1차원의 벡터형식 데이터
* python의 list, tuple, ndarray의 1차원 상태와 비슷

In [115]:
import pandas as pd

# 데이터프레임 만들기
pd.DataFrame({key1: [value1, value2] key2 : [value1, value2]})

In [3]:
df = pd.DataFrame(
        {'이름' : ['홍길동', '둘리', '또치', '도우너'],
         '주소' : ['서울', '의정부', '고양', '성남'],
         '취미' : ['음악감상', '놀기', '달리기', '바이올린']}
        )

In [4]:
df.shape

(4, 3)

In [5]:
df.ndim

2

In [6]:
df['이름'].dtype

dtype('O')

In [7]:
print(df['이름'][:2])

0    홍길동
1     둘리
Name: 이름, dtype: object

# Series 만들기
* pd.Series([리스트 자료/튜플], name="컬럼명")
* 이름을 가지고 있는 list / 벡터
* dataframe에서 컬럼 1개를 잘라온 형태

In [8]:
ages = pd.Series([22,53, 35], name="나이")

In [9]:
ages.dtype

dtype('int64')

In [10]:
ages[0:2]

0    22
1    53
Name: 나이, dtype: int64

In [11]:
ages[::-1]

2    35
1    53
0    22
Name: 나이, dtype: int64

In [12]:
ages.min()

np.int64(22)

In [13]:
ages.max()

np.int64(53)

In [14]:
ages.sum()

np.int64(110)

In [15]:
ages.cumsum()

0     22
1     75
2    110
Name: 나이, dtype: int64

In [16]:
ages.mean()

np.float64(36.666666666666664)

In [17]:
ages.median()

np.float64(35.0)

# 판다스에서 자료 불러오기, 저장하기
* csv, tsv, excel, json, html, sql
* pd.read_확장자명(파일경로, 옵션)

excel 파일 불러오기

In [18]:
df_excel = pd.read_excel("./data/Online Retail.xlsx")
df_excel

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [19]:
df_excel2 = pd.read_excel("./data/아파트(매매)_실거래가_20240806113828.xlsx", header=12, usecols=[1,2,3,4,5])
df_excel2

C:\Users\Admin\miniforge3\envs\fintech\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

                       시군구      번지    본번  부번                단지명
0         서울특별시 영등포구 당산동5가      42    42   0          당산삼성래미안4차
1      강원특별자치도 원주시 지정면 가곡리    1512  1512   0  원주롯데캐슬골드파크1차(5단지)
2        대구광역시 달성군 화원읍 구라리    1650  1650   0             대곡역래미안
3             광주광역시 남구 진월동   312-7   312   7                 광명
4             광주광역시 남구 진월동  331-93   331  93                 중흥
...                    ...     ...   ...  ..                ...
37575        서울특별시 송파구 장지동     849   849   0          송파파인타운3단지
37576        부산광역시 사상구 모라동     552   552   0               백양그린
37577        광주광역시 광산구 비아동   152-5   152   5                 호반
37578        부산광역시 사상구 모라동     552   552   0               백양그린
37579         대구광역시 북구 읍내동  1366-2  1366   2               칠곡보성

[37580 rows x 5 columns]

In [20]:
df_csv = pd.read_csv("./data/아파트(매매)_실거래가_20240806113828.csv", header=12)
df_csv

,NO,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),...,층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자,주택유형
0,1,서울특별시 영등포구 당산동5가,42,42,0,당산삼성래미안4차,115.7800,202407,31,"139,000",...,4,개인,개인,2003,당산로 214,-,직거래,-,-,아파트
1,2,강원특별자치도 원주시 지정면 가곡리,1512,1512,0,원주롯데캐슬골드파크1차(5단지),84.9644,202407,31,"38,900",...,10,개인,개인,2019,신지정로 250,20240802,중개거래,강원 원주시,-,아파트
2,3,대구광역시 달성군 화원읍 구라리,1650,1650,0,대곡역래미안,84.5958,202407,31,"29,500",...,11,개인,개인,2007,비슬로539길 35,-,중개거래,대구 달성군,-,아파트
3,4,광주광역시 남구 진월동,312-7,312,7,광명,70.6250,202407,31,"16,900",...,1,개인,개인,1998,광복마을길 63,-,중개거래,광주 남구,-,아파트
4,5,광주광역시 남구 진월동,331-93,331,93,중흥,84.8400,202407,31,"17,500",...,13,개인,개인,1992,서문대로749번마길 30,-,직거래,-,24.07.31,아파트
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37575,37576,서울특별시 송파구 장지동,849,849,0,송파파인타운3단지,84.9800,202407,1,"117,500",...,14,개인,개인,2008,충민로 152,-,중개거래,서울 송파구,-,아파트
37576,37577,부산광역시 사상구 모라동,552,552,0,백양그린,41.3000,202407,1,"7,000",...,8,개인,개인,1992,모라로110번길 88,-,중개거래,부산 사상구,24.07.10,아파트
37577,37578,광주광역시 광산구 비아동,152-5,152,5,호반,59.8800,202407,1,"15,400",...,5,개인,개인,1998,비아로 185,-,중개거래,광주 광산구,24.07.26,아파트
37578,37579,부산광역시 사상구 모라동,552,552,0,백양그린,41.3000,202407,1,"7,500",...,10,개인,개인,1992,모라로110번길 88,-,중개거래,부산 사상구,24.07.19,아파트
37579,37580,대구광역시 북구 읍내동,1366-2,1366,2,칠곡보성,84.9800,202407,1,"21,000",...,9,개인,개인,1992,구암로21길 26,-,중개거래,대구 북구,-,아파트

In [21]:
df_json = pd.read_json("./data/서울특별시_관광지입장정보_2011_2016.json")
df_json

    ForNum  NatNum  addrCd gungu      resNm  rnum   sido  yyyymm
0    44722   75991    1111   종로구        창덕궁     1  서울특별시  201112
1        0   11017    1111   종로구        운현궁     2  서울특별시  201112
2   132399  237330    1111   종로구        경복궁     3  서울특별시  201112
3     3133   21267    1111   종로구        창경궁     4  서울특별시  201112
4    18226   24223    1111   종로구         종묘     5  서울특별시  201112
..     ...     ...     ...   ...        ...   ...    ...     ...
62    5588   44232    1141  서대문구  서대문형무소역사관     8  서울특별시  201512
63       0   22587    1141  서대문구  서대문자연사박물관     9  서울특별시  201512
64   29520    8822    1144   마포구    트릭아이미술관    10  서울특별시  201512
65       3    1647    1165   서초구      헌릉ㆍ인릉    11  서울특별시  201512
66     492   14454    1168   강남구      선릉·정릉    12  서울특별시  201512

[67 rows x 8 columns]

In [22]:
df_html = pd.read_html("./data/corpList.htm")
df_html[0]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,한국제15호스팩,금융 지원 서비스업,기업인수합병,2024-06-26,12월,유한,NaN,서울특별시
1,에스오에스랩,"측정, 시험, 항해, 제어 및 기타 정밀기기 제조업; 광학기기 제외",산업용 및 차량용 라이다(LiDAR),2024-06-25,12월,정지성,홈페이지 보기,광주광역시
2,미래에셋비전스팩6호,금융 지원 서비스업,기업인수합병,2024-06-24,12월,정명훈,NaN,서울특별시
3,에이치엠씨제7호스팩,금융 지원 서비스업,기타금융,2024-06-24,12월,강신명,NaN,서울특별시
4,파라다이스,유원지 및 기타 오락관련 서비스업,"카지노, 호텔, 복합리조트",2024-06-24,12월,최종환..,홈페이지 보기,서울특별시
5,한중엔시에스,"전동기, 발전기 및 전기 변환 · 공급 · 제어 장치 제조업","수냉식 냉각시스템 ESS Parts, 공랭식 ESS Module Parts, EV ...",2024-06-24,12월,김환식,홈페이지 보기,경상북도
6,KB제29호스팩,금융 지원 서비스업,기업인수합병,2024-06-21,12월,서영화,NaN,서울특별시
7,미래에셋비전스팩5호,금융 지원 서비스업,기업인수합병,2024-06-19,12월,김대호,NaN,서울특별시
8,씨어스테크놀로지,의료용 기기 제조업,심전도검사솔루션 입원환자모니터링솔루션,2024-06-19,12월,이영신,홈페이지 보기,경기도
9,한국제14호스팩,금융 지원 서비스업,기업인수합병,2024-06-19,12월,변성환,NaN,서울특별시
10,디비금융스팩12호,기타 금융업,기업인수 및 합병,2024-06-18,12월,김창희,NaN,서울특별시
11,라메디텍,의료용 기기 제조업,초소형 레이저 의료기기 및 미용기기,2024-06-17,12월,최종석,NaN,서울특별시
12,그리드위즈,"그외 기타 전문, 과학 및 기술 서비스업","수요관리 서비스, 전기차 충전기 모뎀 등",2024-06-14,12월,김구환,홈페이지 보기,경기도
13,다원넥스뷰,사진장비 및 광학기기 제조업,LSMB(Laser Micro Bonding System),2024-06-11,12월,남기중,홈페이지 보기,경기도
14,미래에셋비전스팩4호,금융 지원 서비스업,기업인수목적회사(기타금융서비스),2024-05-29,12월,김정수,NaN,서울특별시

DB에서 자료 읽어오기

In [116]:
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb()

In [24]:
engine = create_engine("mysql+pymysql://root:1234@localhost:3306/exchange_rate")
conn = engine.connect()
df_sql = pd.read_sql("exchange_rate", con=conn)
df_sql

,일자,통화,현찰_사실_때_환율,현찰_사실_때_Spread,현찰_파실_때_환율,현찰_파실_때_Spread,송금_보낼_때_보낼_때,송금_받을_때_받을_때,외화수표파실때,매매기준율,환가료율,미화환산율
0,1995-01-03,미국 USD,800.53,1.5,776.87,1.5,791.80,785.60,0.00,788.70,0.00000,1.0000
1,1995-01-03,일본 JPY (100),798.89,1.5,775.29,1.5,791.81,782.37,0.00,787.09,0.00000,0.9980
2,1995-01-03,유로 EUR,0.00,0.0,0.00,0.0,975.40,959.92,957.94,967.66,7.37000,1.2269
3,1995-01-03,중국 CNY,0.00,0.0,0.00,0.0,94.12,0.00,0.00,93.38,1.00000,0.1184
4,1995-01-03,홍콩 HKD,103.45,3.0,100.41,3.0,102.74,101.12,0.00,101.93,0.00000,0.1292
...,...,...,...,...,...,...,...,...,...,...,...,...
311018,2025-04-10,리비아 LYD,0.00,0.0,0.00,0.0,264.12,258.90,0.00,261.51,0.00000,0.1799
311019,2025-04-10,루마니아 RON,0.00,0.0,0.00,0.0,331.61,324.41,0.00,328.01,7.75833,0.2256
311020,2025-04-10,미얀마 MMK,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.69,0.00000,0.0005
311021,2025-04-10,에티오피아 ETB,0.00,0.0,0.00,0.0,0.00,0.00,0.00,10.98,0.00000,0.0076
311022,2025-04-10,우즈베키스탄 UZS,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.11,0.00000,0.0001

# 타이타닉 데이터셋으로 pandas 기능 익히기

In [154]:
df = pd.read_csv("./data/Taitanic_train.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

* 데이터의 일부만 보기
* 앞쪽 head(행개수), 뒷쪽 tail(행개수)
* 기본 값은 5행

In [27]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [28]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [29]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [30]:
df.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [31]:
df.tail(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [32]:
# 데이터 프레임 각 컬럼의 데이터타입
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

# .info() 
* 컬럼명, null이 아닌 데이터 개수, 데이터타입을 동시에 출력

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

# .describe()
* 데이터 프레임의 숫자 데이터의 기초통계를 보여주는 함수
* count, mean, std, min, 25%, 50%, 75%, max

In [34]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

# 판다스 데이터 프레임에서 일부 자료만 추출하기

* 데이터프레임에서 1개 컬럼만 가져오기

In [35]:
df.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [36]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [37]:
print(type(df['Name']))

<class 'pandas.core.series.Series'>

* 2개 이상의 컬럼을 가져오기

In [38]:
df[['Age', 'Name']]

      Age                                               Name
0    22.0                            Braund, Mr. Owen Harris
1    38.0  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    26.0                             Heikkinen, Miss. Laina
3    35.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4    35.0                           Allen, Mr. William Henry
..    ...                                                ...
886  27.0                              Montvila, Rev. Juozas
887  19.0                       Graham, Miss. Margaret Edith
888   NaN           Johnston, Miss. Catherine Helen "Carrie"
889  26.0                              Behr, Mr. Karl Howell
890  32.0                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [39]:
df[['Age', 'Name', 'Pclass']]

      Age                                               Name  Pclass
0    22.0                            Braund, Mr. Owen Harris       3
1    38.0  Cumings, Mrs. John Bradley (Florence Briggs Th...       1
2    26.0                             Heikkinen, Miss. Laina       3
3    35.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1
4    35.0                           Allen, Mr. William Henry       3
..    ...                                                ...     ...
886  27.0                              Montvila, Rev. Juozas       2
887  19.0                       Graham, Miss. Margaret Edith       1
888   NaN           Johnston, Miss. Catherine Helen "Carrie"       3
889  26.0                              Behr, Mr. Karl Howell       1
890  32.0                                Dooley, Mr. Patrick       3

[891 rows x 3 columns]

* 테이터프레임의 컬럼 순서 바꾸기

In [40]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [41]:
df2 = df[['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'Embarked', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'PassengerId']]
df2

,Survived,Pclass,Name,Sex,Age,Embarked,SibSp,Parch,Ticket,Fare,Cabin,PassengerId
0,0,3,"Braund, Mr. Owen Harris",male,22.0,S,1,0,A/5 21171,7.2500,NaN,1
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,C,1,0,PC 17599,71.2833,C85,2
2,1,3,"Heikkinen, Miss. Laina",female,26.0,S,0,0,STON/O2. 3101282,7.9250,NaN,3
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,S,1,0,113803,53.1000,C123,4
4,0,3,"Allen, Mr. William Henry",male,35.0,S,0,0,373450,8.0500,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,S,0,0,211536,13.0000,NaN,887
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,S,0,0,112053,30.0000,B42,888
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,S,1,2,W./C. 6607,23.4500,NaN,889
889,1,1,"Behr, Mr. Karl Howell",male,26.0,C,0,0,111369,30.0000,C148,890
890,0,3,"Dooley, Mr. Patrick",male,32.0,Q,0,0,370376,7.7500,NaN,891

# 데이터프레임에서 일부 컬럼만 가져오기2
* loc: 인덱스 이름과 컬럼명으로 데이터의 일부를 추출해 가져옴
  * df.loc[시작_row_인덱스 : 끝_row_인덱스, ['컬럼명1', '컬럼명2']
* iloc: 인덱스을 이용해 슬라이싱으로 데이터의 일부를 가져옴
  * df.iloc[시작_row_index : 끝_row_index, 시작_column_index : 끝_column_index]

#### loc[시작_row_인덱스 : 끝_row_인덱스, ['컬럼명1', '컬럼명2']

In [42]:
df[['Name', 'Age']]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [43]:
df.loc[100:130, ['Name', 'Age']]

                                  Name   Age
100            Petranec, Miss. Matilda  28.0
101   Petroff, Mr. Pastcho ("Pentcho")   NaN
102          White, Mr. Richard Frasar  21.0
103         Johansson, Mr. Gustaf Joel  33.0
104     Gustafsson, Mr. Anders Vilhelm  37.0
105              Mionoff, Mr. Stoytcho  28.0
106   Salkjelsvik, Miss. Anna Kristine  21.0
107             Moss, Mr. Albert Johan   NaN
108                    Rekic, Mr. Tido  38.0
109                Moran, Miss. Bertha   NaN
110     Porter, Mr. Walter Chamberlain  47.0
111               Zabour, Miss. Hileni  14.5
112             Barton, Mr. David John  22.0
113            Jussila, Miss. Katriina  20.0
114              Attalah, Miss. Malake  17.0
115              Pekoniemi, Mr. Edvard  21.0
116               Connors, Mr. Patrick  70.5
117    Turpin, Mr. William John Robert  29.0
118           Baxter, Mr. Quigg Edmond  24.0
119  Andersson, Miss. Ellis Anna Maria   2.0
120        Hickman, Mr. Stanley George  21.0
121         Moore, Mr. Leonard Charles   NaN
122               Nasser, Mr. Nicholas  32.5
123                Webber, Miss. Susan  32.5
124        White, Mr. Percival Wayland  54.0
125       Nicola-Yarred, Master. Elias  12.0
126                McMahon, Mr. Martin   NaN
127          Madsen, Mr. Fridtjof Arne  24.0
128                  Peter, Miss. Anna   NaN
129                 Ekstrom, Mr. Johan  45.0
130               Drazenoic, Mr. Jozef  33.0

In [44]:
df.loc[109, ['Age']]

Age    NaN
Name: 109, dtype: object

In [45]:
df.loc[101, ['Age']] = 29

In [46]:
print(df.loc[101:102, ['Name', 'Age']])
display(df.loc[101:102, ['Name', 'Age']])
# print(type(df.loc[101, ['Name', 'Age']]))

                                 Name   Age
101  Petroff, Mr. Pastcho ("Pentcho")  29.0
102         White, Mr. Richard Frasar  21.0

                                 Name   Age
101  Petroff, Mr. Pastcho ("Pentcho")  29.0
102         White, Mr. Richard Frasar  21.0

#### df.iloc[시작_row_index : 끝_row_index, 시작_column_index : 끝_column_index]

In [47]:
df.iloc[4:, -5:]

     Parch      Ticket     Fare Cabin Embarked
4        0      373450   8.0500   NaN        S
5        0      330877   8.4583   NaN        Q
6        0       17463  51.8625   E46        S
7        1      349909  21.0750   NaN        S
8        2      347742  11.1333   NaN        S
..     ...         ...      ...   ...      ...
886      0      211536  13.0000   NaN        S
887      0      112053  30.0000   B42        S
888      2  W./C. 6607  23.4500   NaN        S
889      0      111369  30.0000  C148        C
890      0      370376   7.7500   NaN        Q

[887 rows x 5 columns]

In [48]:
df.iloc[4, 4] = 'female'

In [49]:
df.iloc[4, 4]

'female'

In [50]:
df.iloc[:10:-1, ::-1]

,Embarked,Cabin,Fare,Ticket,Parch,SibSp,Age,Sex,Name,Pclass,Survived,PassengerId
890,Q,NaN,7.7500,370376,0,0,32.0,male,"Dooley, Mr. Patrick",3,0,891
889,C,C148,30.0000,111369,0,0,26.0,male,"Behr, Mr. Karl Howell",1,1,890
888,S,NaN,23.4500,W./C. 6607,2,1,NaN,female,"Johnston, Miss. Catherine Helen ""Carrie""",3,0,889
887,S,B42,30.0000,112053,0,0,19.0,female,"Graham, Miss. Margaret Edith",1,1,888
886,S,NaN,13.0000,211536,0,0,27.0,male,"Montvila, Rev. Juozas",2,0,887
...,...,...,...,...,...,...,...,...,...,...,...,...
15,S,NaN,16.0000,248706,0,0,55.0,female,"Hewlett, Mrs. (Mary D Kingcome)",2,1,16
14,S,NaN,7.8542,350406,0,0,14.0,female,"Vestrom, Miss. Hulda Amanda Adolfina",3,0,15
13,S,NaN,31.2750,347082,5,1,39.0,male,"Andersson, Mr. Anders Johan",3,0,14
12,S,NaN,8.0500,A/5. 2151,0,0,20.0,male,"Saundercock, Mr. William Henry",3,0,13
11,S,C103,26.5500,113783,0,0,58.0,female,"Bonnell, Miss. Elizabeth",1,1,12

* 특정 컬럼에서 유일값(중복되지 않은 고유한 값) 출력하기 
* .unique()

In [51]:
print(df['Embarked'] .unique())

['S' 'C' 'Q' nan]

* .nunique()
* 유일값의 개수를 출력
* nan 값은 무시

In [52]:
df['Embarked'].nunique()

3

* 카테고리 컬럼에서 유일값 별 개수를 세는 함수
* value_counts()

In [53]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [54]:
# ascending 옵션 value의 개수에 따라서 오름차순, 내림차순 정렬
df['Pclass'].value_counts(ascending=True)

Pclass
2    184
1    216
3    491
Name: count, dtype: int64

In [55]:
df['Age'].value_counts(sort=False)

Age
22.00    27
38.00    11
26.00    18
35.00    18
54.00     8
         ..
0.67      1
30.50     2
0.42      1
34.50     1
74.00     1
Name: count, Length: 88, dtype: int64

* 데이터를 정렬하는 함수
* sort_values(by="컬럼명")
* order by

In [56]:
df.sort_values(by="Age", ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

* 기준컬럼 2개로 정렬할 때

In [57]:
df.sort_values(by=['Pclass', "Age"], ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
766,767,0,1,"Brewe, Dr. Arthur Jackson",male,NaN,0,0,112379,39.6000,NaN,C
793,794,0,1,"Hoyt, Mr. William Fisher",male,NaN,0,0,PC 17600,30.6958,NaN,C
815,816,0,1,"Fry, Mr. Richard",male,NaN,0,0,112058,0.0000,B102,S
839,840,1,1,"Marechal, Mr. Pierre",male,NaN,0,0,11774,29.7000,C47,C
849,850,1,1,"Goldenberg, Mrs. Samuel L (Edwiga Grabowska)",female,NaN,1,0,17453,89.1042,C92,C

* 컬럼을 인덱스로 지정하기
* set_index("컬럼명")

In [58]:
df = df.set_index(["PassengerId", "Name"])
df

,,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,Name,,,,,,,,,,
1,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
3,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
5,"Allen, Mr. William Henry",0,3,female,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
888,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
889,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
891,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [59]:
df.loc[(889, 'Johnston, Miss. Catherine Helen "Carrie"'): (891, 'Dooley, Mr. Patrick') , ['Pclass', 'Age'] ]

                                                      Pclass   Age
PassengerId Name
889         Johnston, Miss. Catherine Helen "Carrie"       3   NaN
890         Behr, Mr. Karl Howell                          1  26.0
891         Dooley, Mr. Patrick                            3  32.0

In [60]:
df.iloc[888:, [1,3]]

                                                      Pclass   Age
PassengerId Name
889         Johnston, Miss. Catherine Helen "Carrie"       3   NaN
890         Behr, Mr. Karl Howell                          1  26.0
891         Dooley, Mr. Patrick                            3  32.0

* 인덱스를 숫자로 초기화 
* reset_index(drop=True)

In [61]:
df

,,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,Name,,,,,,,,,,
1,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
3,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
5,"Allen, Mr. William Henry",0,3,female,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
888,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
889,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
891,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [62]:
# df.reset_index(drop=True)
df = df.reset_index()
df

,PassengerId,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
4,5,"Allen, Mr. William Henry",0,3,female,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
887,888,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
890,891,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

* 컬럼이름 출력하기, 바꾸기
* df.columns

In [63]:
df.columns

Index(['PassengerId', 'Name', 'Survived', 'Pclass', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

* 컬럼 이름 변경하기
* rename(columns={'원래이름':'새이름', '원래이름2':'새이름2'}):

In [64]:
df.rename(columns={'PassengerId': 'Pid', 'Survived':'surv'}, inplace=True)
df

,Pid,Name,surv,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
4,5,"Allen, Mr. William Henry",0,3,female,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
887,888,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
890,891,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [65]:
df

,Pid,Name,surv,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
4,5,"Allen, Mr. William Henry",0,3,female,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
887,888,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
890,891,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

* df.columns 로 출력되는 리스트 길이와 같은 새로운 이름의 리스트로 덮어쓰기

In [66]:
df.columns

Index(['Pid', 'Name', 'surv', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [67]:
newName = ['승객번호', '이름', '생존여부', '선실등급', '성별', '나이',
           '형제자매수', '부모자식수', '티켓번호', '티켓가격', 
           '선실번호', '목적지']

In [68]:
df.columns = newName
df

,승객번호,이름,생존여부,선실등급,성별,나이,형제자매수,부모자식수,티켓번호,티켓가격,선실번호,목적지
0,1,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
4,5,"Allen, Mr. William Henry",0,3,female,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
887,888,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
890,891,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

* 컬럼 추가하기
* 변수명['컬럼명'] = value

In [69]:
df['가족수'] = 0

In [70]:
df['가족수'] = df['형제자매수'] + df['부모자식수']
df

,승객번호,이름,생존여부,선실등급,성별,나이,형제자매수,부모자식수,티켓번호,티켓가격,선실번호,목적지,가족수
0,1,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",0,3,female,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S,0
887,888,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S,0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3
889,890,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C,0
890,891,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q,0

* 컬럼 삭제하기
* del df['컬럼명']
* df.drop('컬럼명', axis=1, inplace=True)

In [71]:
del df['형제자매수']
df

,승객번호,이름,생존여부,선실등급,성별,나이,부모자식수,티켓번호,티켓가격,선실번호,목적지,가족수
0,1,"Braund, Mr. Owen Harris",0,3,male,22.0,0,A/5 21171,7.2500,NaN,S,1
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",1,3,female,26.0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",0,3,female,35.0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",0,2,male,27.0,0,211536,13.0000,NaN,S,0
887,888,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,112053,30.0000,B42,S,0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,2,W./C. 6607,23.4500,NaN,S,3
889,890,"Behr, Mr. Karl Howell",1,1,male,26.0,0,111369,30.0000,C148,C,0
890,891,"Dooley, Mr. Patrick",0,3,male,32.0,0,370376,7.7500,NaN,Q,0

In [72]:
df = df.drop('부모자식수', axis=1)
df

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지,가족수
0,1,"Braund, Mr. Owen Harris",0,3,male,22.0,A/5 21171,7.2500,NaN,S,1
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",1,3,female,26.0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",0,3,female,35.0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",0,2,male,27.0,211536,13.0000,NaN,S,0
887,888,"Graham, Miss. Margaret Edith",1,1,female,19.0,112053,30.0000,B42,S,0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,W./C. 6607,23.4500,NaN,S,3
889,890,"Behr, Mr. Karl Howell",1,1,male,26.0,111369,30.0000,C148,C,0
890,891,"Dooley, Mr. Patrick",0,3,male,32.0,370376,7.7500,NaN,Q,0

In [73]:
df.columns

Index(['승객번호', '이름', '생존여부', '선실등급', '성별', '나이', '티켓번호', '티켓가격', '선실번호', '목적지',
       '가족수'],
      dtype='object')

In [74]:
drop_cols = ['승객번호', '이름', '티켓번호', '티켓가격', '선실번호', '목적지',
       '가족수']

In [75]:
df.drop(drop_cols, axis=1)

     생존여부  선실등급      성별    나이
0       0     3    male  22.0
1       1     1  female  38.0
2       1     3  female  26.0
3       1     1  female  35.0
4       0     3  female  35.0
..    ...   ...     ...   ...
886     0     2    male  27.0
887     1     1  female  19.0
888     0     3  female   NaN
889     1     1    male  26.0
890     0     3    male  32.0

[891 rows x 4 columns]

* 데이터 타입 바꾸기
* astype(자료형)
* apply(형변환함수)

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   승객번호    891 non-null    int64
 1   이름      891 non-null    object
 2   생존여부    891 non-null    int64
 3   선실등급    891 non-null    int64
 4   성별      891 non-null    object
 5   나이      715 non-null    float64
 6   티켓번호    891 non-null    object
 7   티켓가격    891 non-null    float64
 8   선실번호    204 non-null    object
 9   목적지     889 non-null    object
 10  가족수     891 non-null    int64
dtypes: float64(2), int64(4), object(5)
memory usage: 76.7+ KB

In [77]:
df['승객번호'] = df['승객번호'].astype('float')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   승객번호    891 non-null    float64
 1   이름      891 non-null    object
 2   생존여부    891 non-null    int64
 3   선실등급    891 non-null    int64
 4   성별      891 non-null    object
 5   나이      715 non-null    float64
 6   티켓번호    891 non-null    object
 7   티켓가격    891 non-null    float64
 8   선실번호    204 non-null    object
 9   목적지     889 non-null    object
 10  가족수     891 non-null    int64
dtypes: float64(3), int64(3), object(5)
memory usage: 76.7+ KB

In [78]:
df['승객번호'] = df['승객번호'].apply(lambda x: "짝수" if float(x) % 2 == 0 else "홀수")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   승객번호    891 non-null    object
 1   이름      891 non-null    object
 2   생존여부    891 non-null    int64
 3   선실등급    891 non-null    int64
 4   성별      891 non-null    object
 5   나이      715 non-null    float64
 6   티켓번호    891 non-null    object
 7   티켓가격    891 non-null    float64
 8   선실번호    204 non-null    object
 9   목적지     889 non-null    object
 10  가족수     891 non-null    int64
dtypes: float64(2), int64(3), object(6)
memory usage: 76.7+ KB

In [79]:
df

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지,가족수
0,홀수,"Braund, Mr. Owen Harris",0,3,male,22.0,A/5 21171,7.2500,NaN,S,1
1,짝수,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,PC 17599,71.2833,C85,C,1
2,홀수,"Heikkinen, Miss. Laina",1,3,female,26.0,STON/O2. 3101282,7.9250,NaN,S,0
3,짝수,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,113803,53.1000,C123,S,1
4,홀수,"Allen, Mr. William Henry",0,3,female,35.0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...
886,홀수,"Montvila, Rev. Juozas",0,2,male,27.0,211536,13.0000,NaN,S,0
887,짝수,"Graham, Miss. Margaret Edith",1,1,female,19.0,112053,30.0000,B42,S,0
888,홀수,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,W./C. 6607,23.4500,NaN,S,3
889,짝수,"Behr, Mr. Karl Howell",1,1,male,26.0,111369,30.0000,C148,C,0
890,홀수,"Dooley, Mr. Patrick",0,3,male,32.0,370376,7.7500,NaN,Q,0

# 판다스 데이터프레임에서 조건에 맞는 행만 가져오기
* df[df['컬럼명'] 조건식] 
* 조건식 연산자 <, <=, >, >=, ==, !=, &, |

In [80]:
df[df['승객번호'] == "홀수"]

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지,가족수
0,홀수,"Braund, Mr. Owen Harris",0,3,male,22.0,A/5 21171,7.2500,NaN,S,1
2,홀수,"Heikkinen, Miss. Laina",1,3,female,26.0,STON/O2. 3101282,7.9250,NaN,S,0
4,홀수,"Allen, Mr. William Henry",0,3,female,35.0,373450,8.0500,NaN,S,0
6,홀수,"McCarthy, Mr. Timothy J",0,1,male,54.0,17463,51.8625,E46,S,0
8,홀수,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",1,3,female,27.0,347742,11.1333,NaN,S,2
...,...,...,...,...,...,...,...,...,...,...,...
882,홀수,"Dahlberg, Miss. Gerda Ulrika",0,3,female,22.0,7552,10.5167,NaN,S,0
884,홀수,"Sutehall, Mr. Henry Jr",0,3,male,25.0,SOTON/OQ 392076,7.0500,NaN,S,0
886,홀수,"Montvila, Rev. Juozas",0,2,male,27.0,211536,13.0000,NaN,S,0
888,홀수,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,W./C. 6607,23.4500,NaN,S,3
890,홀수,"Dooley, Mr. Patrick",0,3,male,32.0,370376,7.7500,NaN,Q,0

In [81]:
# 나이가 35 초과인 사람만 필터링
df[df['나이'] > 35]

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지,가족수
1,짝수,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,PC 17599,71.2833,C85,C,1
6,홀수,"McCarthy, Mr. Timothy J",0,1,male,54.0,17463,51.8625,E46,S,0
11,짝수,"Bonnell, Miss. Elizabeth",1,1,female,58.0,113783,26.5500,C103,S,0
13,짝수,"Andersson, Mr. Anders Johan",0,3,male,39.0,347082,31.2750,NaN,S,6
15,짝수,"Hewlett, Mrs. (Mary D Kingcome)",1,2,female,55.0,248706,16.0000,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...
865,짝수,"Bystrom, Mrs. (Karolina)",1,2,female,42.0,236852,13.0000,NaN,S,0
871,짝수,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",1,1,female,47.0,11751,52.5542,D35,S,2
873,짝수,"Vander Cruyssen, Mr. Victor",0,3,male,47.0,345765,9.0000,NaN,S,0
879,짝수,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",1,1,female,56.0,11767,83.1583,C50,C,1
885,짝수,"Rice, Mrs. William (Margaret Norton)",0,3,female,39.0,382652,29.1250,NaN,Q,5

* 여성이면서 나이가 35세 초과인 행 찾기 and 조건

In [82]:
df[(df['성별'] == 'female') & (df['나이'] > 35)]

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지,가족수
1,짝수,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,PC 17599,71.2833,C85,C,1
11,짝수,"Bonnell, Miss. Elizabeth",1,1,female,58.0,113783,26.5500,C103,S,0
15,짝수,"Hewlett, Mrs. (Mary D Kingcome)",1,2,female,55.0,248706,16.0000,NaN,S,0
25,짝수,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",1,3,female,38.0,347077,31.3875,NaN,S,6
40,홀수,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",0,3,female,40.0,7546,9.4750,NaN,S,1
...,...,...,...,...,...,...,...,...,...,...,...
862,홀수,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",1,1,female,48.0,17466,25.9292,D17,S,0
865,짝수,"Bystrom, Mrs. (Karolina)",1,2,female,42.0,236852,13.0000,NaN,S,0
871,짝수,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",1,1,female,47.0,11751,52.5542,D35,S,2
879,짝수,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",1,1,female,56.0,11767,83.1583,C50,C,1
885,짝수,"Rice, Mrs. William (Margaret Norton)",0,3,female,39.0,382652,29.1250,NaN,Q,5

* 성별이 male, 선실등급 1, 생존여부 1인 사람을 찾으세요.

In [83]:
df[(df['성별'] == 'male') & (df['선실등급'] == 1) & (df['생존여부'] == 1)]

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지,가족수
23,짝수,"Sloper, Mr. William Thompson",1,1,male,28.00,113788,35.5000,A6,S,0
55,짝수,"Woolner, Mr. Hugh",1,1,male,NaN,19947,35.5000,C52,S,0
97,짝수,"Greenfield, Mr. William Bertram",1,1,male,23.00,PC 17759,63.3583,D10 D12,C,1
187,짝수,"Romaine, Mr. Charles Hallace (""Mr C Rolmane"")",1,1,male,45.00,111428,26.5500,NaN,S,0
209,짝수,"Blank, Mr. Henry",1,1,male,40.00,112277,31.0000,A31,C,0
224,홀수,"Hoyt, Mr. Frederick Maxfield",1,1,male,38.00,19943,90.0000,C93,S,1
248,홀수,"Beckwith, Mr. Richard Leonard",1,1,male,37.00,11751,52.5542,D35,S,2
298,홀수,"Saalfeld, Mr. Adolphe",1,1,male,NaN,19988,30.5000,C106,S,0
305,짝수,"Allison, Master. Hudson Trevor",1,1,male,0.92,113781,151.5500,C22 C26,S,3
370,홀수,"Harder, Mr. George Achilles",1,1,male,25.00,11765,55.4417,E50,C,1
390,홀수,"Carter, Mr. William Ernest",1,1,male,36.00,113760,120.0000,B96 B98,S,3
430,홀수,"Bjornstrom-Steffansson, Mr. Mauritz Hakan",1,1,male,28.00,110564,26.5500,C52,S,0
445,짝수,"Dodge, Master. Washington",1,1,male,4.00,33638,81.8583,A34,S,2
447,짝수,"Seward, Mr. Frederic Kimber",1,1,male,34.00,113794,26.5500,NaN,S,0
449,짝수,"Peuchen, Major. Arthur Godfrey",1,1,male,52.00,113786,30.5000,C104,S,0
453,짝수,"Goldenberg, Mr. Samuel L",1,1,male,49.00,17453,89.1042,C92,C,1
460,홀수,"Anderson, Mr. Harry",1,1,male,48.00,19952,26.5500,E12,S,0
484,홀수,"Bishop, Mr. Dickinson H",1,1,male,25.00,11967,91.0792,B49,C,1
507,짝수,"Bradley, Mr. George (""George Arthur Brayton"")",1,1,male,NaN,111427,26.5500,NaN,S,0
512,홀수,"McGough, Mr. James Robert",1,1,male,36.00,PC 17473,26.2875,E25,S,0
550,홀수,"Thayer, Mr. John Borland Jr",1,1,male,17.00,17421,110.8833,C70,C,2
572,홀수,"Flynn, Mr. John Irwin (""Irving"")",1,1,male,36.00,PC 17474,26.3875,E25,S,0
587,짝수,"Frolicher-Stehli, Mr. Maxmillian",1,1,male,60.00,13567,79.2000,B41,C,2
599,짝수,"Duff Gordon, Sir. Cosmo Edmund (""Mr Morgan"")",1,1,male,49.00,PC 17485,56.9292,A20,C,1
604,홀수,"Homer, Mr. Harry (""Mr E Haven"")",1,1,male,35.00,111426,26.5500,NaN,C,0
607,짝수,"Daniel, Mr. Robert Williams",1,1,male,27.00,113804,30.5000,NaN,S,0
621,짝수,"Kimball, Mr. Edwin Nelson Jr",1,1,male,42.00,11753,52.5542,D19,S,1
630,홀수,"Barkworth, Mr. Algernon Henry Wilson",1,1,male,80.00,27042,30.0000,A23,S,0
632,홀수,"Stahelin-Maeglin, Dr. Max",1,1,male,32.00,13214,30.5000,B50,C,0
645,짝수,"Harper, Mr. Henry Sleeper",1,1,male,48.00,PC 17572,76.7292,D33,C,1
647,짝수,"Simonius-Blumer, Col. Oberst Alfons",1,1,male,56.00,13213,35.5000,A26,C,0
660,홀수,"Frauenthal, Dr. Henry William",1,1,male,50.00,PC 17611,133.6500,NaN,S,2
679,짝수,"Cardeza, Mr. Thomas Drake Martinez",1,1,male,36.00,PC 17755,512.3292,B51 B53 B55,C,1
681,짝수,"Hassab, Mr. Hammad",1,1,male,27.00,PC 17572,76.7292,D49,C,0
690,홀수,"Dick, Mr. Albert Adrian",1,1,male,31.00,17474,57.0000,B20,S,1
701,짝수,"Silverthorne, Mr. Spencer Victor",1,1,male,35.00,PC 17475,26.2875,E24,S,0
707,짝수,"Calderhead, Mr. Edward Pennington",1,1,male,42.00,PC 17476,26.2875,E24,S,0
712,홀수,"Taylor, Mr. Elmer Zebley",1,1,male,48.00,19996,52.0000,C126,S,1
724,홀수,"Chambers, Mr. Norman Campbell",1,1,male,27.00,113806,53.1000,E8,S,1
737,짝수,"Lesurer, Mr. Gustave J",1,1,male,35.00,PC 17755,512.3292,B101,C,0
740,홀수,"Hawksford, Mr. Walter James",1,1,male,NaN,16988,30.0000,D45,S,0
802,홀수,"Carter, Master. William Thornton II",1,1,male,11.00,113760,120.0000,B96 B98,S,3
839,짝수,"Marechal, Mr. Pierre",1,1,male,NaN,11774,29.7000,C47,C,0
857,짝수,"Daly, Mr. Peter Denis",1,1,male,51.00,113055,26.5500,E17,S,0
889,짝수,"Behr, Mr. Karl Howell",1,1,male,26.00,111369,30.0000,C148,C,0

* 선실 등급별 승차권 금액의 최소, 최대, 평균 등 4분위수를 보고싶다.

In [84]:
# 선실 등급이 1등석인 사람들의 승차권 금액 통계량을 보고 싶다.
df[df['선실등급'] == 1]['티켓가격'].describe()

count    216.000000
mean      84.154687
std       78.380373
min        0.000000
25%       30.923950
50%       60.287500
75%       93.500000
max      512.329200
Name: 티켓가격, dtype: float64

In [85]:
df[df['티켓가격'] > 512]

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지,가족수
258,홀수,"Ward, Miss. Anna",1,1,female,35.0,PC 17755,512.3292,NaN,C,0
679,짝수,"Cardeza, Mr. Thomas Drake Martinez",1,1,male,36.0,PC 17755,512.3292,B51 B53 B55,C,1
737,짝수,"Lesurer, Mr. Gustave J",1,1,male,35.0,PC 17755,512.3292,B101,C,0

In [86]:
df[df['티켓가격'] == 0]

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지,가족수
179,짝수,"Leonard, Mr. Lionel",0,3,male,36.0,LINE,0.0,NaN,S,0
263,짝수,"Harrison, Mr. William",0,1,male,40.0,112059,0.0,B94,S,0
271,짝수,"Tornquist, Mr. William Henry",1,3,male,25.0,LINE,0.0,NaN,S,0
277,짝수,"Parkes, Mr. Francis ""Frank""",0,2,male,NaN,239853,0.0,NaN,S,0
302,홀수,"Johnson, Mr. William Cahoone Jr",0,3,male,19.0,LINE,0.0,NaN,S,0
413,짝수,"Cunningham, Mr. Alfred Fleming",0,2,male,NaN,239853,0.0,NaN,S,0
466,홀수,"Campbell, Mr. William",0,2,male,NaN,239853,0.0,NaN,S,0
481,짝수,"Frost, Mr. Anthony Wood ""Archie""",0,2,male,NaN,239854,0.0,NaN,S,0
597,짝수,"Johnson, Mr. Alfred",0,3,male,49.0,LINE,0.0,NaN,S,0
633,짝수,"Parr, Mr. William Henry Marsh",0,1,male,NaN,112052,0.0,NaN,S,0
674,홀수,"Watson, Mr. Ennis Hastings",0,2,male,NaN,239856,0.0,NaN,S,0
732,홀수,"Knight, Mr. Robert J",0,2,male,NaN,239855,0.0,NaN,S,0
806,홀수,"Andrews, Mr. Thomas Jr",0,1,male,39.0,112050,0.0,A36,S,0
815,짝수,"Fry, Mr. Richard",0,1,male,NaN,112058,0.0,B102,S,0
822,홀수,"Reuchlin, Jonkheer. John George",0,1,male,38.0,19972,0.0,NaN,S,0

#  조건에 맞는 행을 찾은 후 특정 컬럼만 조회하기

* 선실등급이 1이거나 2이면서 생존한 여성 중에서 이름 컬럼만 보고 싶을 때

In [87]:
df.columns

Index(['승객번호', '이름', '생존여부', '선실등급', '성별', '나이', '티켓번호', '티켓가격', '선실번호', '목적지',
       '가족수'],
      dtype='object')

In [88]:
df.loc[((df['선실등급'] == 1) | (df['선실등급'] == 2)) & (df['생존여부'] == 1) & (df['성별'] == 'female'), '이름']

1      Cumings, Mrs. John Bradley (Florence Briggs Th...
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
9                    Nasser, Mrs. Nicholas (Adele Achem)
11                              Bonnell, Miss. Elizabeth
15                      Hewlett, Mrs. (Mary D Kingcome)
                             ...
871     Beckwith, Mrs. Richard Leonard (Sallie Monypeny)
874                Abelson, Mrs. Samuel (Hannah Wizosky)
879        Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)
880         Shelley, Mrs. William (Imanita Parrish Hall)
887                         Graham, Miss. Margaret Edith
Name: 이름, Length: 161, dtype: object

In [89]:
df[((df['선실등급'] == 1) | (df['선실등급'] == 2)) & (df['생존여부'] == 1) & (df['성별'] == 'female')]['이름']

1      Cumings, Mrs. John Bradley (Florence Briggs Th...
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
9                    Nasser, Mrs. Nicholas (Adele Achem)
11                              Bonnell, Miss. Elizabeth
15                      Hewlett, Mrs. (Mary D Kingcome)
                             ...
871     Beckwith, Mrs. Richard Leonard (Sallie Monypeny)
874                Abelson, Mrs. Samuel (Hannah Wizosky)
879        Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)
880         Shelley, Mrs. William (Imanita Parrish Hall)
887                         Graham, Miss. Margaret Edith
Name: 이름, Length: 161, dtype: object

* 나이가 25세 미만이면서 생존자의 이름

In [90]:
df.loc[(df['나이'] < 25) & (df['생존여부'] == 1), '이름']

9           Nasser, Mrs. Nicholas (Adele Achem)
10              Sandstrom, Miss. Marguerite Rut
22                  McGowan, Miss. Anna "Annie"
39                  Nicola-Yarred, Miss. Jamila
43     Laroche, Miss. Simonne Marie Anne Andree
                         ...
855                  Aks, Mrs. Sam (Leah Rosen)
858       Baclini, Mrs. Solomon (Latifa Qurban)
869             Johnson, Master. Harold Theodor
875            Najib, Miss. Adele Kiamie "Jane"
887                Graham, Miss. Margaret Edith
Name: 이름, Length: 118, dtype: object

In [91]:
# 결과에서 이름과 나이를 같이 보고 싶다.
df.loc[(df['나이'] < 25) & (df['생존여부'] == 1), ['이름', '나이']]

                                           이름    나이
9         Nasser, Mrs. Nicholas (Adele Achem)  14.0
10            Sandstrom, Miss. Marguerite Rut   4.0
22                McGowan, Miss. Anna "Annie"  15.0
39                Nicola-Yarred, Miss. Jamila  14.0
43   Laroche, Miss. Simonne Marie Anne Andree   3.0
..                                        ...   ...
855                Aks, Mrs. Sam (Leah Rosen)  18.0
858     Baclini, Mrs. Solomon (Latifa Qurban)  24.0
869           Johnson, Master. Harold Theodor   4.0
875          Najib, Miss. Adele Kiamie "Jane"  15.0
887              Graham, Miss. Margaret Edith  19.0

[118 rows x 2 columns]

In [92]:
df[(df.나이 < 25) & (df.생존여부 == 1)][['이름', '나이']]

                                           이름    나이
9         Nasser, Mrs. Nicholas (Adele Achem)  14.0
10            Sandstrom, Miss. Marguerite Rut   4.0
22                McGowan, Miss. Anna "Annie"  15.0
39                Nicola-Yarred, Miss. Jamila  14.0
43   Laroche, Miss. Simonne Marie Anne Andree   3.0
..                                        ...   ...
855                Aks, Mrs. Sam (Leah Rosen)  18.0
858     Baclini, Mrs. Solomon (Latifa Qurban)  24.0
869           Johnson, Master. Harold Theodor   4.0
875          Najib, Miss. Adele Kiamie "Jane"  15.0
887              Graham, Miss. Margaret Edith  19.0

[118 rows x 2 columns]

In [93]:
df.나이

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: 나이, Length: 891, dtype: float64

.isin([조건1, 조건2]) or 조건을 여러 번 써야 할 때 간단히 표현

* 선실등급을 1, 2등인 사람을 추출

In [94]:
df[(df['선실등급'] == 1) | (df['선실등급'] == 2)]

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지,가족수
1,짝수,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,PC 17599,71.2833,C85,C,1
3,짝수,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,113803,53.1000,C123,S,1
6,홀수,"McCarthy, Mr. Timothy J",0,1,male,54.0,17463,51.8625,E46,S,0
9,짝수,"Nasser, Mrs. Nicholas (Adele Achem)",1,2,female,14.0,237736,30.0708,NaN,C,1
11,짝수,"Bonnell, Miss. Elizabeth",1,1,female,58.0,113783,26.5500,C103,S,0
...,...,...,...,...,...,...,...,...,...,...,...
880,홀수,"Shelley, Mrs. William (Imanita Parrish Hall)",1,2,female,25.0,230433,26.0000,NaN,S,1
883,짝수,"Banfield, Mr. Frederick James",0,2,male,28.0,C.A./SOTON 34068,10.5000,NaN,S,0
886,홀수,"Montvila, Rev. Juozas",0,2,male,27.0,211536,13.0000,NaN,S,0
887,짝수,"Graham, Miss. Margaret Edith",1,1,female,19.0,112053,30.0000,B42,S,0
889,짝수,"Behr, Mr. Karl Howell",1,1,male,26.0,111369,30.0000,C148,C,0

In [95]:
df[df['선실등급'].isin([1,2])]

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지,가족수
1,짝수,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,PC 17599,71.2833,C85,C,1
3,짝수,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,113803,53.1000,C123,S,1
6,홀수,"McCarthy, Mr. Timothy J",0,1,male,54.0,17463,51.8625,E46,S,0
9,짝수,"Nasser, Mrs. Nicholas (Adele Achem)",1,2,female,14.0,237736,30.0708,NaN,C,1
11,짝수,"Bonnell, Miss. Elizabeth",1,1,female,58.0,113783,26.5500,C103,S,0
...,...,...,...,...,...,...,...,...,...,...,...
880,홀수,"Shelley, Mrs. William (Imanita Parrish Hall)",1,2,female,25.0,230433,26.0000,NaN,S,1
883,짝수,"Banfield, Mr. Frederick James",0,2,male,28.0,C.A./SOTON 34068,10.5000,NaN,S,0
886,홀수,"Montvila, Rev. Juozas",0,2,male,27.0,211536,13.0000,NaN,S,0
887,짝수,"Graham, Miss. Margaret Edith",1,1,female,19.0,112053,30.0000,B42,S,0
889,짝수,"Behr, Mr. Karl Howell",1,1,male,26.0,111369,30.0000,C148,C,0

# 특정 단어를 포함한 행 찾기
* 이름에 Joseph 가 들어간 사람 찾기
* like %단어% - SQL
* .str.contains("찾을 단어")

In [96]:
df[df['이름'].str.contains("Joseph")]

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지,가족수
20,홀수,"Fynney, Mr. Joseph J",0,2,male,35.0,239865,26.0000,NaN,S,0
34,홀수,"Meyer, Mr. Edgar Joseph",0,1,male,28.0,PC 17604,82.1708,NaN,C,1
95,짝수,"Shorney, Mr. Charles Joseph",0,3,male,NaN,374910,8.0500,NaN,S,0
140,홀수,"Boulos, Mrs. Joseph (Sultana)",0,3,female,NaN,2678,15.2458,NaN,C,2
145,짝수,"Nicholls, Mr. Joseph Charles",0,2,male,19.0,C.A. 33112,36.7500,NaN,S,2
194,홀수,"Brown, Mrs. James Joseph (Margaret Tobin)",1,1,female,44.0,PC 17610,27.7208,B4,C,0
375,짝수,"Meyer, Mrs. Edgar Joseph (Leila Saks)",1,1,female,NaN,PC 17604,82.1708,NaN,C,1
454,홀수,"Peduzzi, Mr. Joseph",0,3,male,NaN,A/5 2817,8.0500,NaN,S,0
532,홀수,"Elias, Mr. Joseph Jr",0,3,male,17.0,2690,7.2292,NaN,C,2
559,짝수,"de Messemaeker, Mrs. Guillaume Joseph (Emma)",1,3,female,36.0,345572,17.4000,NaN,S,1
578,홀수,"Caram, Mrs. Joseph (Maria Elias)",0,3,female,NaN,2689,14.4583,NaN,C,1
589,짝수,"Murdlin, Mr. Joseph",0,3,male,NaN,A./5. 3235,8.0500,NaN,S,0
608,홀수,"Laroche, Mrs. Joseph (Juliette Marie Louise La...",1,2,female,22.0,SC/Paris 2123,41.5792,NaN,C,3
685,짝수,"Laroche, Mr. Joseph Philippe Lemercier",0,2,male,25.0,SC/Paris 2123,41.5792,NaN,C,3
752,홀수,"Vande Velde, Mr. Johannes Joseph",0,3,male,33.0,345780,9.5000,NaN,S,0
828,홀수,"McCormack, Mr. Thomas Joseph",1,3,male,NaN,367228,7.7500,NaN,Q,0

In [97]:
# 티켓번호에 PC라는 문자가 포함된 티켓을 필터링
df[df['티켓번호'].str.contains("PC")]

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지,가족수
1,짝수,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,PC 17599,71.2833,C85,C,1
30,홀수,"Uruchurtu, Don. Manuel E",0,1,male,40.0,PC 17601,27.7208,NaN,C,0
31,짝수,"Spencer, Mrs. William Augustus (Marie Eugenie)",1,1,female,NaN,PC 17569,146.5208,B78,C,1
34,홀수,"Meyer, Mr. Edgar Joseph",0,1,male,28.0,PC 17604,82.1708,NaN,C,1
52,홀수,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",1,1,female,49.0,PC 17572,76.7292,D33,C,1
64,홀수,"Stewart, Mr. Albert A",0,1,male,NaN,PC 17605,27.7208,NaN,C,0
96,홀수,"Goldschmidt, Mr. George B",0,1,male,71.0,PC 17754,34.6542,A5,C,0
97,짝수,"Greenfield, Mr. William Bertram",1,1,male,23.0,PC 17759,63.3583,D10 D12,C,1
118,홀수,"Baxter, Mr. Quigg Edmond",0,1,male,24.0,PC 17558,247.5208,B58 B60,C,1
139,짝수,"Giglio, Mr. Victor",0,1,male,24.0,PC 17593,79.2000,B86,C,0
155,짝수,"Williams, Mr. Charles Duane",0,1,male,51.0,PC 17597,61.3792,NaN,C,1
168,홀수,"Baumann, Mr. John D",0,1,male,NaN,PC 17318,25.9250,NaN,S,0
177,짝수,"Isham, Miss. Ann Elizabeth",0,1,female,50.0,PC 17595,28.7125,C49,C,0
194,홀수,"Brown, Mrs. James Joseph (Margaret Tobin)",1,1,female,44.0,PC 17610,27.7208,B4,C,0
195,짝수,"Lurette, Miss. Elise",1,1,female,58.0,PC 17569,146.5208,B80,C,0
256,홀수,"Thorne, Mrs. Gertrude Maybelle",1,1,female,NaN,PC 17585,79.2000,NaN,C,0
258,홀수,"Ward, Miss. Anna",1,1,female,35.0,PC 17755,512.3292,NaN,C,0
268,홀수,"Graham, Mrs. William Thompson (Edith Junkins)",1,1,female,58.0,PC 17582,153.4625,C125,S,1
269,짝수,"Bissette, Miss. Amelia",1,1,female,35.0,PC 17760,135.6333,C99,S,0
273,짝수,"Natsch, Mr. Charles H",0,1,male,37.0,PC 17596,29.7000,C118,C,1
295,짝수,"Lewy, Mr. Ervin G",0,1,male,NaN,PC 17612,27.7208,NaN,C,0
299,짝수,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",1,1,female,50.0,PC 17558,247.5208,B58 B60,C,1
307,짝수,"Penasco y Castellana, Mrs. Victor de Satode (M...",1,1,female,17.0,PC 17758,108.9000,C65,C,1
309,짝수,"Francatelli, Miss. Laura Mabel",1,1,female,30.0,PC 17485,56.9292,E36,C,0
311,짝수,"Ryerson, Miss. Emily Borie",1,1,female,18.0,PC 17608,262.3750,B57 B59 B63 B66,C,4
325,짝수,"Young, Miss. Marie Grice",1,1,female,36.0,PC 17760,135.6333,C32,C,0
332,홀수,"Graham, Mr. George Edward",0,1,male,38.0,PC 17582,153.4625,C91,S,1
334,홀수,"Frauenthal, Mrs. Henry William (Clara Heinshei...",1,1,female,NaN,PC 17611,133.6500,NaN,S,1
369,짝수,"Aubart, Mme. Leontine Pauline",1,1,female,24.0,PC 17477,69.3000,B35,C,0
373,짝수,"Ringhini, Mr. Sante",0,1,male,22.0,PC 17760,135.6333,NaN,C,0
375,짝수,"Meyer, Mrs. Edgar Joseph (Leila Saks)",1,1,female,NaN,PC 17604,82.1708,NaN,C,1
380,홀수,"Bidois, Miss. Rosalie",1,1,female,42.0,PC 17757,227.5250,NaN,C,0
493,짝수,"Artagaveytia, Mr. Ramon",0,1,male,71.0,PC 17609,49.5042,NaN,C,0
505,짝수,"Penasco y Castellana, Mr. Victor de Satode",0,1,male,18.0,PC 17758,108.9000,C65,C,1
512,홀수,"McGough, Mr. James Robert",1,1,male,36.0,PC 17473,26.2875,E25,S,0
513,짝수,"Rothschild, Mrs. Martin (Elizabeth L. Barrett)",1,1,female,54.0,PC 17603,59.4000,NaN,C,1
527,짝수,"Farthing, Mr. John",0,1,male,NaN,PC 17483,221.7792,C95,S,0
537,짝수,"LeRoy, Miss. Bertha",1,1,female,30.0,PC 17761,106.4250,NaN,C,0
544,홀수,"Douglas, Mr. Walter Donald",0,1,male,50.0,PC 17761,106.4250,C86,C,1
557,짝수,"Robbins, Mr. Victor",0,1,male,NaN,PC 17757,227.5250,NaN,C,0
572,홀수,"Flynn, Mr. John Irwin (""Irving"")",1,1,male,36.0,PC 17474,26.3875,E25,S,0
599,짝수,"Duff Gordon, Sir. Cosmo Edmund (""Mr Morgan"")",1,1,male,49.0,PC 17485,56.9292,A20,C,1
609,짝수,"Shutes, Miss. Elizabeth W",1,1,female,40.0,PC 17582,153.4625,C125,S,0
641,짝수,"Sagesser, Mlle. Emma",1,1,female,24.0,PC 17477,69.3000,B35,C,0
645,짝수,"Harper, Mr. Henry Sleeper",1,1,male,48.0,PC 17572,76.7292,D33,C,1
660,홀수,"Frauenthal, Dr. Henry William",1,1,male,50.0,PC 17611,133.6500,NaN,S,2
679,짝수,"Cardeza, Mr. Thomas Drake Martinez",1,1,male,36.0,PC 17755,512.3292,B51 B53 B55,C,1
681,짝수,"Hassab, Mr. Hammad",1,1,male,27.0,PC 17572,76.7292,D49,C,0
700,홀수,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",1,1,female,18.0,PC 17757,227.5250,C62 C64,C,1
701,짝수,"Silverthorne, Mr. Spencer Victor",1,1,male,35.0,PC 17475,26.2875,E24,S,0
707,짝수,"Calderhead, Mr. Edward Pennington",1,1,male,42.0,PC 17476,26.2875,E24,S,0
710,홀수,"Mayne, Mlle. Berthe Antonine (""Mrs de Villiers"")",1,1,female,24.0,PC 17482,49.5042,C90,C,0
716,홀수,"Endres, Miss. Caroline Louise",1,1,female,38.0,PC 17757,227.5250,C45,C,0
737,짝수,"Lesurer, Mr. Gustave J",1,1,male,35.0,PC 17755,512.3292,B101,C,0
742,홀수,"Ryerson, Miss. Susan Parker ""Suzette""",1,1,female,21.0,PC 17608,262.3750,B57 B59 B63 B66,C,4
789,짝수,"Guggenheim, Mr. Benjamin",0,1,male,46.0,PC 17593,79.2000,B82 B84,C,0
793,짝수,"Hoyt, Mr. William Fisher",0,1,male,NaN,PC 17600,30.6958,NaN,C,0
835,짝수,"Compton, Miss. Sara Rebecca",1,1,female,39.0,PC 17756,83.1583,E49,C,2
853,짝수,"Lines, Miss. Mary Conover",1,1,female,16.0,PC 17592,39.4000,D28,S,1
867,짝수,"Roebling, Mr. Washington Augustus II",0,1,male,31.0,PC 17590,50.4958,A24,S,0

In [98]:
df[df['티켓번호'].str.contains("C.A")]

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지,가족수
33,짝수,"Wheadon, Mr. Edward H",0,2,male,66.0,C.A. 24579,10.5000,NaN,S,0
56,홀수,"Rugg, Miss. Emily",1,2,female,21.0,C.A. 31026,10.5000,NaN,S,0
58,홀수,"West, Miss. Constance Mirium",1,2,female,5.0,C.A. 34651,27.7500,NaN,S,3
66,홀수,"Nye, Mrs. (Elizabeth Ramell)",1,2,female,29.0,C.A. 29395,10.5000,F33,S,0
70,홀수,"Jenkin, Mr. Stephen Curnow",0,2,male,32.0,C.A. 33111,10.5000,NaN,S,0
93,짝수,"Dean, Mr. Bertram Frank",0,3,male,26.0,C.A. 2315,20.5750,NaN,S,3
134,홀수,"Sobey, Mr. Samuel James Hayden",0,2,male,25.0,C.A. 29178,13.0000,NaN,S,0
145,짝수,"Nicholls, Mr. Joseph Charles",0,2,male,19.0,C.A. 33112,36.7500,NaN,S,2
161,짝수,"Watt, Mrs. James (Elizabeth ""Bessie"" Inglis Mi...",1,2,female,40.0,C.A. 33595,15.7500,NaN,S,0
234,홀수,"Leyson, Mr. Robert William Norman",0,2,male,24.0,C.A. 29566,10.5000,NaN,S,0
237,짝수,"Collyer, Miss. Marjorie ""Lottie""",1,2,female,8.0,C.A. 31921,26.2500,NaN,S,2
265,짝수,"Reeves, Mr. David",0,2,male,36.0,C.A. 17248,10.5000,NaN,S,0
279,짝수,"Abbott, Mrs. Stanton (Rosa Hunt)",1,3,female,35.0,C.A. 2673,20.2500,NaN,S,2
348,홀수,"Coutts, Master. William Loch ""William""",1,3,male,3.0,C.A. 37671,15.9000,NaN,S,2
432,홀수,"Louch, Mrs. Charles Alexander (Alice Adelaide ...",1,2,female,42.0,SC/AH 3085,26.0000,NaN,S,1
439,짝수,"Kvillner, Mr. Johan Henrik Johannesson",0,2,male,31.0,C.A. 18723,10.5000,NaN,S,0
450,홀수,"West, Mr. Edwy Arthur",0,2,male,36.0,C.A. 34651,27.7500,NaN,S,3
472,홀수,"West, Mrs. Edwy Arthur (Ada Mary Worth)",1,2,female,33.0,C.A. 34651,27.7500,NaN,S,3
473,짝수,"Jerwan, Mrs. Amin S (Marie Marthe Thuillard)",1,2,female,23.0,SC/AH Basle 541,13.7917,D,C,0
489,짝수,"Coutts, Master. Eden Leslie ""Neville""",1,3,male,9.0,C.A. 37671,15.9000,NaN,S,2
497,짝수,"Shellard, Mr. Frederick William",0,3,male,NaN,C.A. 6212,15.1000,NaN,S,0
516,홀수,"Lemore, Mrs. (Amelia Milley)",1,2,female,34.0,C.A. 34260,10.5000,F33,S,0
549,짝수,"Davies, Master. John Morgan Jr",1,2,male,8.0,C.A. 33112,36.7500,NaN,S,2
594,홀수,"Chapman, Mr. John Henry",0,2,male,37.0,SC/AH 29037,26.0000,NaN,S,1
637,짝수,"Collyer, Mr. Harvey",0,2,male,31.0,C.A. 31921,26.2500,NaN,S,2
672,홀수,"Mitchell, Mr. Henry Michael",0,2,male,70.0,C.A. 24580,10.5000,NaN,S,0
746,홀수,"Abbott, Mr. Rossmore Edward",0,3,male,16.0,C.A. 2673,20.2500,NaN,S,2
788,홀수,"Dean, Master. Bertram Vere",1,3,male,1.0,C.A. 2315,20.5750,NaN,S,3
801,짝수,"Collyer, Mrs. Harvey (Charlotte Annie Tate)",1,2,female,31.0,C.A. 31921,26.2500,NaN,S,2
845,짝수,"Abbing, Mr. Anthony",0,3,male,42.0,C.A. 5547,7.5500,NaN,S,0
883,짝수,"Banfield, Mr. Frederick James",0,2,male,28.0,C.A./SOTON 34068,10.5000,NaN,S,0

* 승객이름에서 ()를 없애기
* 반복문/리스트표현식을 이용해 없애기
* apply + lambda 함수를 이용해 없애기
* .str 메서드를 이용해 없애기

* 반복문 이용하기

In [106]:
result = []
for name in df["이름"]:
    result.append(name.replace("(", "").replace(")",""))
result
df["이름"] = result

['Braund, Mr. Owen Harris',
 'Cumings, Mrs. John Bradley Florence Briggs Thayer',
 'Heikkinen, Miss. Laina',
 'Futrelle, Mrs. Jacques Heath Lily May Peel',
 'Allen, Mr. William Henry',
 'Moran, Mr. James',
 'McCarthy, Mr. Timothy J',
 'Palsson, Master. Gosta Leonard',
 'Johnson, Mrs. Oscar W Elisabeth Vilhelmina Berg',
 'Nasser, Mrs. Nicholas Adele Achem',
 'Sandstrom, Miss. Marguerite Rut',
 'Bonnell, Miss. Elizabeth',
 'Saundercock, Mr. William Henry',
 'Andersson, Mr. Anders Johan',
 'Vestrom, Miss. Hulda Amanda Adolfina',
 'Hewlett, Mrs. Mary D Kingcome ',
 'Rice, Master. Eugene',
 'Williams, Mr. Charles Eugene',
 'Vander Planke, Mrs. Julius Emelia Maria Vandemoortele',
 'Masselmani, Mrs. Fatima',
 'Fynney, Mr. Joseph J',
 'Beesley, Mr. Lawrence',
 'McGowan, Miss. Anna "Annie"',
 'Sloper, Mr. William Thompson',
 'Palsson, Miss. Torborg Danira',
 'Asplund, Mrs. Carl Oscar Selma Augusta Emilia Johansson',
 'Emir, Mr. Farred Chehab',
 'Fortune, Mr. Charles Alexander',
 'O\'Dwyer, Miss. Ellen "Nellie"',
 'Todoroff, Mr. Lalio',
 'Uruchurtu, Don. Manuel E',
 'Spencer, Mrs. William Augustus Marie Eugenie',
 'Glynn, Miss. Mary Agatha',
 'Wheadon, Mr. Edward H',
 'Meyer, Mr. Edgar Joseph',
 'Holverson, Mr. Alexander Oskar',
 'Mamee, Mr. Hanna',
 'Cann, Mr. Ernest Charles',
 'Vander Planke, Miss. Augusta Maria',
 'Nicola-Yarred, Miss. Jamila',
 'Ahlin, Mrs. Johan Johanna Persdotter Larsson',
 'Turpin, Mrs. William John Robert Dorothy Ann Wonnacott',
 'Kraeff, Mr. Theodor',
 'Laroche, Miss. Simonne Marie Anne Andree',
 'Devaney, Miss. Margaret Delia',
 'Rogers, Mr. William John',
 'Lennon, Mr. Denis',
 "O'Driscoll, Miss. Bridget",
 'Samaan, Mr. Youssef',
 'Arnold-Franchi, Mrs. Josef Josefine Franchi',
 'Panula, Master. Juha Niilo',
 'Nosworthy, Mr. Richard Cater',
 'Harper, Mrs. Henry Sleeper Myna Haxtun',
 'Faunthorpe, Mrs. Lizzie Elizabeth Anne Wilkinson',
 'Ostby, Mr. Engelhart Cornelius',
 'Woolner, Mr. Hugh',
 'Rugg, Miss. Emily',
 'Novel, Mr. Mansouer',
 'West, Miss. Constance Mirium',
 'Goodwin, Master. William Frederick',
 'Sirayanian, Mr. Orsen',
 'Icard, Miss. Amelie',
 'Harris, Mr. Henry Birkhardt',
 'Skoog, Master. Harald',
 'Stewart, Mr. Albert A',
 'Moubarek, Master. Gerios',
 'Nye, Mrs. Elizabeth Ramell',
 'Crease, Mr. Ernest James',
 'Andersson, Miss. Erna Alexandra',
 'Kink, Mr. Vincenz',
 'Jenkin, Mr. Stephen Curnow',
 'Goodwin, Miss. Lillian Amy',
 'Hood, Mr. Ambrose Jr',
 'Chronopoulos, Mr. Apostolos',
 'Bing, Mr. Lee',
 'Moen, Mr. Sigurd Hansen',
 'Staneff, Mr. Ivan',
 'Moutal, Mr. Rahamin Haim',
 'Caldwell, Master. Alden Gates',
 'Dowdell, Miss. Elizabeth',
 'Waelens, Mr. Achille',
 'Sheerlinck, Mr. Jan Baptist',
 'McDermott, Miss. Brigdet Delia',
 'Carrau, Mr. Francisco M',
 'Ilett, Miss. Bertha',
 'Backstrom, Mrs. Karl Alfred Maria Mathilda Gustafsson',
 'Ford, Mr. William Neal',
 'Slocovski, Mr. Selman Francis',
 'Fortune, Miss. Mabel Helen',
 'Celotti, Mr. Francesco',
 'Christmann, Mr. Emil',
 'Andreasson, Mr. Paul Edvin',
 'Chaffee, Mr. Herbert Fuller',
 'Dean, Mr. Bertram Frank',
 'Coxon, Mr. Daniel',
 'Shorney, Mr. Charles Joseph',
 'Goldschmidt, Mr. George B',
 'Greenfield, Mr. William Bertram',
 'Doling, Mrs. John T Ada Julia Bone',
 'Kantor, Mr. Sinai',
 'Petranec, Miss. Matilda',
 'Petroff, Mr. Pastcho "Pentcho"',
 'White, Mr. Richard Frasar',
 'Johansson, Mr. Gustaf Joel',
 'Gustafsson, Mr. Anders Vilhelm',
 'Mionoff, Mr. Stoytcho',
 'Salkjelsvik, Miss. Anna Kristine',
 'Moss, Mr. Albert Johan',
 'Rekic, Mr. Tido',
 'Moran, Miss. Bertha',
 'Porter, Mr. Walter Chamberlain',
 'Zabour, Miss. Hileni',
 'Barton, Mr. David John',
 'Jussila, Miss. Katriina',
 'Attalah, Miss. Malake',
 'Pekoniemi, Mr. Edvard',
 'Connors, Mr. Patrick',
 'Turpin, Mr. William John Robert',
 'Baxter, Mr. Quigg Edmond',
 'Andersson, Miss. Ellis Anna Maria',
 'Hickman, Mr. Stanley George',
 'Moore, Mr. Leonard Charles',
 'Nasser, Mr. Nicholas',
 'Webber, Miss. Susan',
 'White, Mr. Percival Wayland',
 'Nicola-Yarred, Master. Elias',
 'McMahon, Mr. Martin',
 'Madsen, Mr. Fridtjof Arne',
 'Peter, Miss. Anna',
 'Ekstrom, Mr. Johan',
 'Drazenoic, Mr. Jozef',
 'Coelho, Mr. Domingos Fernandeo',
 'Robins, Mrs. Alexander A Grace Charity Laury',
 'Weisz, Mrs. Leopold Mathilde Francoise Pede',
 'Sobey, Mr. Samuel James Hayden',
 'Richard, Mr. Emile',
 'Newsom, Miss. Helen Monypeny',
 'Futrelle, Mr. Jacques Heath',
 'Osen, Mr. Olaf Elon',
 'Giglio, Mr. Victor',
 'Boulos, Mrs. Joseph Sultana',
 'Nysten, Miss. Anna Sofia',
 'Hakkarainen, Mrs. Pekka Pietari Elin Matilda Dolck',
 'Burke, Mr. Jeremiah',
 'Andrew, Mr. Edgardo Samuel',
 'Nicholls, Mr. Joseph Charles',
 'Andersson, Mr. August Edvard "Wennerstrom"',
 'Ford, Miss. Robina Maggie "Ruby"',
 'Navratil, Mr. Michel "Louis M Hoffman"',
 'Byles, Rev. Thomas Roussel Davids',
 'Bateman, Rev. Robert James',
 'Pears, Mrs. Thomas Edith Wearne',
 'Meo, Mr. Alfonzo',
 'van Billiard, Mr. Austin Blyler',
 'Olsen, Mr. Ole Martin',
 'Williams, Mr. Charles Duane',
 'Gilnagh, Miss. Katherine "Katie"',
 'Corn, Mr. Harry',
 'Smiljanic, Mr. Mile',
 'Sage, Master. Thomas Henry',
 'Cribb, Mr. John Hatfield',
 'Watt, Mrs. James Elizabeth "Bessie" Inglis Milne',
 'Bengtsson, Mr. John Viktor',
 'Calic, Mr. Jovo',
 'Panula, Master. Eino Viljami',
 'Goldsmith, Master. Frank John William "Frankie"',
 'Chibnall, Mrs. Edith Martha Bowerman',
 'Skoog, Mrs. William Anna Bernhardina Karlsson',
 'Baumann, Mr. John D',
 'Ling, Mr. Lee',
 'Van der hoef, Mr. Wyckoff',
 'Rice, Master. Arthur',
 'Johnson, Miss. Eleanor Ileen',
 'Sivola, Mr. Antti Wilhelm',
 'Smith, Mr. James Clinch',
 'Klasen, Mr. Klas Albin',
 'Lefebre, Master. Henry Forbes',
 'Isham, Miss. Ann Elizabeth',
 'Hale, Mr. Reginald',
 'Leonard, Mr. Lionel',
 'Sage, Miss. Constance Gladys',
 'Pernot, Mr. Rene',
 'Asplund, Master. Clarence Gustaf Hugo',
 'Becker, Master. Richard F',
 'Kink-Heilmann, Miss. Luise Gretchen',
 'Rood, Mr. Hugh Roscoe',
 'O\'Brien, Mrs. Thomas Johanna "Hannah" Godfrey',
 'Romaine, Mr. Charles Hallace "Mr C Rolmane"',
 'Bourke, Mr. John',
 'Turcin, Mr. Stjepan',
 'Pinsky, Mrs. Rosa',
 'Carbines, Mr. William',
 'Andersen-Jensen, Miss. Carla Christine Nielsine',
 'Navratil, Master. Michel M',
 'Brown, Mrs. James Joseph Margaret Tobin',
 'Lurette, Miss. Elise',
 'Mernagh, Mr. Robert',
 'Olsen, Mr. Karl Siegwart Andreas',
 'Madigan, Miss. Margaret "Maggie"',
 'Yrois, Miss. Henriette "Mrs Harbeck"',
 'Vande Walle, Mr. Nestor Cyriel',
 'Sage, Mr. Frederick',
 'Johanson, Mr. Jakob Alfred',
 'Youseff, Mr. Gerious',
 'Cohen, Mr. Gurshon "Gus"',
 'Strom, Miss. Telma Matilda',
 'Backstrom, Mr. Karl Alfred',
 'Albimona, Mr. Nassef Cassem',
 'Carr, Miss. Helen "Ellen"',
 'Blank, Mr. Henry',
 'Ali, Mr. Ahmed',
 'Cameron, Miss. Clear Annie',
 'Perkin, Mr. John Henry',
 'Givard, Mr. Hans Kristensen',
 'Kiernan, Mr. Philip',
 'Newell, Miss. Madeleine',
 'Honkanen, Miss. Eliina',
 'Jacobsohn, Mr. Sidney Samuel',
 'Bazzani, Miss. Albina',
 'Harris, Mr. Walter',
 'Sunderland, Mr. Victor Francis',
 'Bracken, Mr. James H',
 'Green, Mr. George Henry',
 'Nenkoff, Mr. Christo',
 'Hoyt, Mr. Frederick Maxfield',
 'Berglund, Mr. Karl Ivar Sven',
 'Mellors, Mr. William John',
 'Lovell, Mr. John Hall "Henry"',
 'Fahlstrom, Mr. Arne Jonas',
 'Lefebre, Miss. Mathilde',
 'Harris, Mrs. Henry Birkhardt Irene Wallach',
 'Larsson, Mr. Bengt Edvin',
 'Sjostedt, Mr. Ernst Adolf',
 'Asplund, Miss. Lillian Gertrud',
 'Leyson, Mr. Robert William Norman',
 'Harknett, Miss. Alice Phoebe',
 'Hold, Mr. Stephen',
 'Collyer, Miss. Marjorie "Lottie"',
 'Pengelly, Mr. Frederick William',
 'Hunt, Mr. George Henry',
 'Zabour, Miss. Thamine',
 'Murphy, Miss. Katherine "Kate"',
 'Coleridge, Mr. Reginald Charles',
 'Maenpaa, Mr. Matti Alexanteri',
 'Attalah, Mr. Sleiman',
 'Minahan, Dr. William Edward',
 'Lindahl, Miss. Agda Thorilda Viktoria',
 'Hamalainen, Mrs. William Anna',
 'Beckwith, Mr. Richard Leonard',
 'Carter, Rev. Ernest Courtenay',
 'Reed, Mr. James George',
 'Strom, Mrs. Wilhelm Elna Matilda Persson',
 'Stead, Mr. William Thomas',
 'Lobb, Mr. William Arthur',
 'Rosblom, Mrs. Viktor Helena Wilhelmina',
 'Touma, Mrs. Darwis Hanne Youssef Razi',
 'Thorne, Mrs. Gertrude Maybelle',
 'Cherry, Miss. Gladys',
 'Ward, Miss. Anna',
 'Parrish, Mrs. Lutie Davis',
 'Smith, Mr. Thomas',
 'Asplund, Master. Edvin Rojj Felix',
 'Taussig, Mr. Emil',
 'Harrison, Mr. William',
 'Henry, Miss. Delia',
 'Reeves, Mr. David',
 'Panula, Mr. Ernesti Arvid',
 'Persson, Mr. Ernst Ulrik',
 'Graham, Mrs. William Thompson Edith Junkins',
 'Bissette, Miss. Amelia',
 'Cairns, Mr. Alexander',
 'Tornquist, Mr. William Henry',
 'Mellinger, Mrs. Elizabeth Anne Maidment',
 'Natsch, Mr. Charles H',
 'Healy, Miss. Hanora "Nora"',
 'Andrews, Miss. Kornelia Theodosia',
 'Lindblom, Miss. Augusta Charlotta',
 'Parkes, Mr. Francis "Frank"',
 'Rice, Master. Eric',
 'Abbott, Mrs. Stanton Rosa Hunt',
 'Duane, Mr. Frank',
 'Olsson, Mr. Nils Johan Goransson',
 'de Pelsmaeker, Mr. Alfons',
 'Dorking, Mr. Edward Arthur',
 'Smith, Mr. Richard William',
 'Stankovic, Mr. Ivan',
 'de Mulder, Mr. Theodore',
 'Naidenoff, Mr. Penko',
 'Hosono, Mr. Masabumi',
 'Connolly, Miss. Kate',
 'Barber, Miss. Ellen "Nellie"',
 'Bishop, Mrs. Dickinson H Helen Walton',
 'Levy, Mr. Rene Jacques',
 'Haas, Miss. Aloisia',
 'Mineff, Mr. Ivan',
 'Lewy, Mr. Ervin G',
 'Hanna, Mr. Mansour',
 'Allison, Miss. Helen Loraine',
 'Saalfeld, Mr. Adolphe',
 'Baxter, Mrs. James Helene DeLaudeniere Chaput',
 'Kelly, Miss. Anna Katherine "Annie Kate"',
 'McCoy, Mr. Bernard',
 'Johnson, Mr. William Cahoone Jr',
 'Keane, Miss. Nora A',
 'Williams, Mr. Howard Hugh "Harry"',
 'Allison, Master. Hudson Trevor',
 'Fleming, Miss. Margaret',
 'Penasco y Castellana, Mrs. Victor de Satode Maria Josefa Perez de Soto y Vallejo',
 'Abelson, Mr. Samuel',
 'Francatelli, Miss. Laura Mabel',
 'Hays, Miss. Margaret Bechstein',
 'Ryerson, Miss. Emily Borie',
 'Lahtinen, Mrs. William Anna Sylfven',
 'Hendekovic, Mr. Ignjac',
 'Hart, Mr. Benjamin',
 'Nilsson, Miss. Helmina Josefina',
 'Kantor, Mrs. Sinai Miriam Sternin',
 'Moraweck, Dr. Ernest',
 'Wick, Miss. Mary Natalie',
 'Spedden, Mrs. Frederic Oakley Margaretta Corning Stone',
 'Dennis, Mr. Samuel',
 'Danoff, Mr. Yoto',
 'Slayter, Miss. Hilda Mary',
 'Caldwell, Mrs. Albert Francis Sylvia Mae Harbaugh',
 'Sage, Mr. George John Jr',
 'Young, Miss. Marie Grice',
 'Nysveen, Mr. Johan Hansen',
 'Ball, Mrs. Ada E Hall',
 'Goldsmith, Mrs. Frank John Emily Alice Brown',
 'Hippach, Miss. Jean Gertrude',
 'McCoy, Miss. Agnes',
 'Partner, Mr. Austen',
 'Graham, Mr. George Edward',
 'Vander Planke, Mr. Leo Edmondus',
 'Frauenthal, Mrs. Henry William Clara Heinsheimer',
 'Denkoff, Mr. Mitto',
 'Pears, Mr. Thomas Clinton',
 'Burns, Miss. Elizabeth Margaret',
 'Dahl, Mr. Karl Edwart',
 'Blackwell, Mr. Stephen Weart',
 'Navratil, Master. Edmond Roger',
 'Fortune, Miss. Alice Elizabeth',
 'Collander, Mr. Erik Gustaf',
 'Sedgwick, Mr. Charles Frederick Waddington',
 'Fox, Mr. Stanley Hubert',
 'Brown, Miss. Amelia "Mildred"',
 'Smith, Miss. Marion Elsie',
 'Davison, Mrs. Thomas Henry Mary E Finck',
 'Coutts, Master. William Loch "William"',
 'Dimic, Mr. Jovan',
 'Odahl, Mr. Nils Martin',
 'Williams-Lambert, Mr. Fletcher Fellows',
 'Elias, Mr. Tannous',
 'Arnold-Franchi, Mr. Josef',
 'Yousif, Mr. Wazli',
 'Vanden Steen, Mr. Leo Peter',
 'Bowerman, Miss. Elsie Edith',
 'Funk, Miss. Annie Clemmer',
 'McGovern, Miss. Mary',
 'Mockler, Miss. Helen Mary "Ellie"',
 'Skoog, Mr. Wilhelm',
 'del Carlo, Mr. Sebastiano',
 'Barbara, Mrs. Catherine David',
 'Asim, Mr. Adola',
 "O'Brien, Mr. Thomas",
 'Adahl, Mr. Mauritz Nils Martin',
 'Warren, Mrs. Frank Manley Anna Sophia Atkinson',
 'Moussa, Mrs. Mantoura Boulos',
 'Jermyn, Miss. Annie',
 'Aubart, Mme. Leontine Pauline',
 'Harder, Mr. George Achilles',
 'Wiklund, Mr. Jakob Alfred',
 'Beavan, Mr. William Thomas',
 'Ringhini, Mr. Sante',
 'Palsson, Miss. Stina Viola',
 'Meyer, Mrs. Edgar Joseph Leila Saks',
 'Landergren, Miss. Aurora Adelia',
 'Widener, Mr. Harry Elkins',
 'Betros, Mr. Tannous',
 'Gustafsson, Mr. Karl Gideon',
 'Bidois, Miss. Rosalie',
 'Nakid, Miss. Maria "Mary"',
 'Tikkanen, Mr. Juho',
 'Holverson, Mrs. Alexander Oskar Mary Aline Towner',
 'Plotcharsky, Mr. Vasil',
 'Davies, Mr. Charles Henry',
 'Goodwin, Master. Sidney Leonard',
 'Buss, Miss. Kate',
 'Sadlier, Mr. Matthew',
 'Lehmann, Miss. Bertha',
 'Carter, Mr. William Ernest',
 'Jansson, Mr. Carl Olof',
 'Gustafsson, Mr. Johan Birger',
 'Newell, Miss. Marjorie',
 'Sandstrom, Mrs. Hjalmar Agnes Charlotta Bengtsson',
 'Johansson, Mr. Erik',
 'Olsson, Miss. Elina',
 'McKane, Mr. Peter David',
 'Pain, Dr. Alfred',
 'Trout, Mrs. William H Jessie L',
 'Niskanen, Mr. Juha',
 'Adams, Mr. John',
 'Jussila, Miss. Mari Aina',
 'Hakkarainen, Mr. Pekka Pietari',
 'Oreskovic, Miss. Marija',
 'Gale, Mr. Shadrach',
 'Widegren, Mr. Carl/Charles Peter',
 'Richards, Master. William Rowe',
 'Birkeland, Mr. Hans Martin Monsen',
 'Lefebre, Miss. Ida',
 'Sdycoff, Mr. Todor',
 'Hart, Mr. Henry',
 'Minahan, Miss. Daisy E',
 'Cunningham, Mr. Alfred Fleming',
 'Sundman, Mr. Johan Julian',
 'Meek, Mrs. Thomas Annie Louise Rowley',
 'Drew, Mrs. James Vivian Lulu Thorne Christian',
 'Silven, Miss. Lyyli Karoliina',
 'Matthews, Mr. William John',
 'Van Impe, Miss. Catharina',
 'Gheorgheff, Mr. Stanio',
 'Charters, Mr. David',
 'Zimmerman, Mr. Leo',
 'Danbom, Mrs. Ernst Gilbert Anna Sigrid Maria Brogren',
 'Rosblom, Mr. Viktor Richard',
 'Wiseman, Mr. Phillippe',
 'Clarke, Mrs. Charles V Ada Maria Winfield',
 'Phillips, Miss. Kate Florence "Mrs Kate Louise Phillips Marshall"',
 'Flynn, Mr. James',
 'Pickard, Mr. Berk Berk Trembisky',
 'Bjornstrom-Steffansson, Mr. Mauritz Hakan',
 'Thorneycroft, Mrs. Percival Florence Kate White',
 'Louch, Mrs. Charles Alexander Alice Adelaide Slow',
 'Kallio, Mr. Nikolai Erland',
 'Silvey, Mr. William Baird',
 'Carter, Miss. Lucile Polk',
 'Ford, Miss. Doolina Margaret "Daisy"',
 'Richards, Mrs. Sidney Emily Hocking',
 'Fortune, Mr. Mark',
 'Kvillner, Mr. Johan Henrik Johannesson',
 'Hart, Mrs. Benjamin Esther Ada Bloomfield',
 'Hampe, Mr. Leon',
 'Petterson, Mr. Johan Emil',
 'Reynaldo, Ms. Encarnacion',
 'Johannesen-Bratthammer, Mr. Bernt',
 'Dodge, Master. Washington',
 'Mellinger, Miss. Madeleine Violet',
 'Seward, Mr. Frederic Kimber',
 'Baclini, Miss. Marie Catherine',
 'Peuchen, Major. Arthur Godfrey',
 'West, Mr. Edwy Arthur',
 'Hagland, Mr. Ingvald Olai Olsen',
 'Foreman, Mr. Benjamin Laventall',
 'Goldenberg, Mr. Samuel L',
 'Peduzzi, Mr. Joseph',
 'Jalsevac, Mr. Ivan',
 'Millet, Mr. Francis Davis',
 'Kenyon, Mrs. Frederick R Marion',
 'Toomey, Miss. Ellen',
 "O'Connor, Mr. Maurice",
 'Anderson, Mr. Harry',
 'Morley, Mr. William',
 'Gee, Mr. Arthur H',
 'Milling, Mr. Jacob Christian',
 'Maisner, Mr. Simon',
 'Goncalves, Mr. Manuel Estanslas',
 'Campbell, Mr. William',
 'Smart, Mr. John Montgomery',
 'Scanlan, Mr. James',
 'Baclini, Miss. Helene Barbara',
 'Keefe, Mr. Arthur',
 'Cacic, Mr. Luka',
 'West, Mrs. Edwy Arthur Ada Mary Worth',
 'Jerwan, Mrs. Amin S Marie Marthe Thuillard',
 'Strandberg, Miss. Ida Sofia',
 'Clifford, Mr. George Quincy',
 'Renouf, Mr. Peter Henry',
 'Braund, Mr. Lewis Richard',
 'Karlsson, Mr. Nils August',
 'Hirvonen, Miss. Hildur E',
 'Goodwin, Master. Harold Victor',
 'Frost, Mr. Anthony Wood "Archie"',
 'Rouse, Mr. Richard Henry',
 'Turkula, Mrs. Hedwig',
 'Bishop, Mr. Dickinson H',
 'Lefebre, Miss. Jeannie',
 'Hoyt, Mrs. Frederick Maxfield Jane Anne Forby',
 'Kent, Mr. Edward Austin',
 'Somerton, Mr. Francis William',
 'Coutts, Master. Eden Leslie "Neville"',
 'Hagland, Mr. Konrad Mathias Reiersen',
 'Windelov, Mr. Einar',
 'Molson, Mr. Harry Markland',
 'Artagaveytia, Mr. Ramon',
 'Stanley, Mr. Edward Roland',
 'Yousseff, Mr. Gerious',
 'Eustis, Miss. Elizabeth Mussey',
 'Shellard, Mr. Frederick William',
 'Allison, Mrs. Hudson J C Bessie Waldo Daniels',
 'Svensson, Mr. Olof',
 'Calic, Mr. Petar',
 'Canavan, Miss. Mary',
 "O'Sullivan, Miss. Bridget Mary",
 'Laitinen, Miss. Kristina Sofia',
 'Maioni, Miss. Roberta',
 'Penasco y Castellana, Mr. Victor de Satode',
 'Quick, Mrs. Frederick Charles Jane Richards',
 'Bradley, Mr. George "George Arthur Brayton"',
 'Olsen, Mr. Henry Margido',
 'Lang, Mr. Fang',
 'Daly, Mr. Eugene Patrick',
 'Webber, Mr. James',
 'McGough, Mr. James Robert',
 'Rothschild, Mrs. Martin Elizabeth L. Barrett',
 'Coleff, Mr. Satio',
 'Walker, Mr. William Anderson',
 'Lemore, Mrs. Amelia Milley',
 'Ryan, Mr. Patrick',
 'Angle, Mrs. William A Florence "Mary" Agnes Hughes',
 'Pavlovic, Mr. Stefo',
 'Perreault, Miss. Anne',
 'Vovk, Mr. Janko',
 'Lahoud, Mr. Sarkis',
 'Hippach, Mrs. Louis Albert Ida Sophia Fischer',
 'Kassem, Mr. Fared',
 'Farrell, Mr. James',
 'Ridsdale, Miss. Lucy',
 'Farthing, Mr. John',
 'Salonen, Mr. Johan Werner',
 'Hocking, Mr. Richard George',
 'Quick, Miss. Phyllis May',
 'Toufik, Mr. Nakli',
 'Elias, Mr. Joseph Jr',
 'Peter, Mrs. Catherine Catherine Rizk',
 'Cacic, Miss. Marija',
 'Hart, Miss. Eva Miriam',
 'Butt, Major. Archibald Willingham',
 'LeRoy, Miss. Bertha',
 'Risien, Mr. Samuel Beard',
 'Frolicher, Miss. Hedwig Margaritha',
 'Crosby, Miss. Harriet R',
 'Andersson, Miss. Ingeborg Constanzia',
 'Andersson, Miss. Sigrid Elisabeth',
 'Beane, Mr. Edward',
 'Douglas, Mr. Walter Donald',
 'Nicholson, Mr. Arthur Ernest',
 'Beane, Mrs. Edward Ethel Clarke',
 'Padro y Manent, Mr. Julian',
 'Goldsmith, Mr. Frank John',
 'Davies, Master. John Morgan Jr',
 'Thayer, Mr. John Borland Jr',
 'Sharp, Mr. Percival James R',
 "O'Brien, Mr. Timothy",
 'Leeni, Mr. Fahim "Philip Zenni"',
 'Ohman, Miss. Velin',
 'Wright, Mr. George',
 'Duff Gordon, Lady. Lucille Christiana Sutherland "Mrs Morgan"',
 'Robbins, Mr. Victor',
 'Taussig, Mrs. Emil Tillie Mandelbaum',
 'de Messemaeker, Mrs. Guillaume Joseph Emma',
 'Morrow, Mr. Thomas Rowan',
 'Sivic, Mr. Husein',
 'Norman, Mr. Robert Douglas',
 'Simmons, Mr. John',
 'Meanwell, Miss. Marion Ogden',
 'Davies, Mr. Alfred J',
 'Stoytcheff, Mr. Ilia',
 'Palsson, Mrs. Nils Alma Cornelia Berglund',
 'Doharr, Mr. Tannous',
 'Jonsson, Mr. Carl',
 'Harris, Mr. George',
 'Appleton, Mrs. Edward Dale Charlotte Lamson',
 'Flynn, Mr. John Irwin "Irving"',
 'Kelly, Miss. Mary',
 'Rush, Mr. Alfred George John',
 'Patchett, Mr. George',
 'Garside, Miss. Ethel',
 'Silvey, Mrs. William Baird Alice Munger',
 'Caram, Mrs. Joseph Maria Elias',
 'Jussila, Mr. Eiriik',
 'Christy, Miss. Julie Rachel',
 'Thayer, Mrs. John Borland Marian Longstreth Morris',
 'Downton, Mr. William James',
 'Ross, Mr. John Hugo',
 'Paulner, Mr. Uscher',
 'Taussig, Miss. Ruth',
 'Jarvis, Mr. John Denzil',
 'Frolicher-Stehli, Mr. Maxmillian',
 'Gilinski, Mr. Eliezer',
 'Murdlin, Mr. Joseph',
 'Rintamaki, Mr. Matti',
 'Stephenson, Mrs. Walter Bertram Martha Eustis',
 'Elsbury, Mr. William James',
 'Bourke, Miss. Mary',
 'Chapman, Mr. John Henry',
 'Van Impe, Mr. Jean Baptiste',
 'Leitch, Miss. Jessie Wills',
 'Johnson, Mr. Alfred',
 'Boulos, Mr. Hanna',
 'Duff Gordon, Sir. Cosmo Edmund "Mr Morgan"',
 'Jacobsohn, Mrs. Sidney Samuel Amy Frances Christy',
 'Slabenoff, Mr. Petco',
 'Harrington, Mr. Charles H',
 'Torber, Mr. Ernst William',
 'Homer, Mr. Harry "Mr E Haven"',
 'Lindell, Mr. Edvard Bengtsson',
 'Karaic, Mr. Milan',
 'Daniel, Mr. Robert Williams',
 'Laroche, Mrs. Joseph Juliette Marie Louise Lafargue',
 'Shutes, Miss. Elizabeth W',
 'Andersson, Mrs. Anders Johan Alfrida Konstantia Brogren',
 'Jardin, Mr. Jose Neto',
 'Murphy, Miss. Margaret Jane',
 'Horgan, Mr. John',
 'Brocklebank, Mr. William Alfred',
 'Herman, Miss. Alice',
 'Danbom, Mr. Ernst Gilbert',
 'Lobb, Mrs. William Arthur Cordelia K Stanlick',
 'Becker, Miss. Marion Louise',
 'Gavey, Mr. Lawrence',
 'Yasbeck, Mr. Antoni',
 'Kimball, Mr. Edwin Nelson Jr',
 'Nakid, Mr. Sahid',
 'Hansen, Mr. Henry Damsgaard',
 'Bowen, Mr. David John "Dai"',
 'Sutton, Mr. Frederick',
 'Kirkland, Rev. Charles Leonard',
 'Longley, Miss. Gretchen Fiske',
 'Bostandyeff, Mr. Guentcho',
 "O'Connell, Mr. Patrick D",

* apply와 lambda 함수를 이용해 없애기

In [110]:
df2 = df.copy()

In [112]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [118]:
df['Name'].apply(lambda name: name.replace("(", "").replace(")",""))

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley Florence Briggs Thayer
2                                 Heikkinen, Miss. Laina
3             Futrelle, Mrs. Jacques Heath Lily May Peel
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

* .str.replace를 활용해서 처리하기
* .str.문자열함수 (uplper, lower, split, replace, join, strip)

In [145]:
df['Name'].str.replace("(", "").str.replace(")","")

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley Florence Briggs Thayer
2                                 Heikkinen, Miss. Laina
3             Futrelle, Mrs. Jacques Heath Lily May Peel
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [150]:
df['Name'] = df['Name'].str.strip(", ")

In [151]:
df['Name'].apply(lambda x: x)

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

# groupby
* 특정 기준 컬럼 지정해서 다른 컬럼의 통계량 (평균, 최소, 최대)
* df[['보고싶은 컬럼1', '보고싶은 컬럼2']].groupby('기준컬럼').집합함수(mean, max, min, median, count)

* 성별별 생존자 수

In [158]:
survbysex = df[['Sex', 'Survived']].groupby('Sex').value_counts(sort=False)
survbysex

Sex     Survived
female  0            81
        1           233
male    0           468
        1           109
Name: count, dtype: int64

In [159]:
print(type(survbysex))

<class 'pandas.core.series.Series'>

In [ ]:
233 /

* 선실등급별 생존자 수

In [160]:
df[['Pclass', 'Survived']].groupby('Pclass').value_counts(sort=False)

Pclass  Survived
1       0            80
        1           136
2       0            97
        1            87
3       0           372
        1           119
Name: count, dtype: int64

* 성별별, 선실등급 별 생존자 수

In [161]:
df[['Sex', 'Pclass', 'Survived']].groupby(['Sex', 'Pclass']).value_counts(sort=False)

Sex     Pclass  Survived
female  1       0             3
                1            91
        2       0             6
                1            70
        3       0            72
                1            72
male    1       0            77
                1            45
        2       0            91
                1            17
        3       0           300
                1            47
Name: count, dtype: int64

은행 고객 등급
- 급여 통장 입금여부, 액수
- 적금, 예금

* 성별에 따른 나이의 평균, 최소, 최대값

In [162]:
df[['Sex', 'Age']].groupby('Sex').mean()

              Age
Sex
female  27.915709
male    30.726645

In [164]:
df[['Sex', 'Age']].groupby('Sex').describe()

          Age
        count       mean        std   min   25%   50%   75%   max
Sex
female  261.0  27.915709  14.110146  0.75  18.0  27.0  37.0  63.0
male    453.0  30.726645  14.678201  0.42  21.0  29.0  39.0  80.0

In [165]:
df[['Sex', 'Age']].groupby('Sex').agg(['min', 'max', 'mean'])

         Age
         min   max       mean
Sex
female  0.75  63.0  27.915709
male    0.42  80.0  30.726645

* 피벗테이블 pivot

In [168]:
df.pivot_table(values = "Survived", index="Sex", columns="Pclass")

Pclass         1         2         3
Sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

# 결측값 찾기(값이 없는 것)

In [170]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

isna()

isna() 결측값인지 아닌지 확인 -> True(1),Flase(0) =

In [174]:
df.isna().sum() / len(df) * 100

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

dropna() 결측값이 있는 행을 삭제

In [175]:
df.dropna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

fillna() 결측값을 다른값으로 채워주는 함수

In [178]:
round(df['Age'].mean())

30

# 여러개의 데이터프레임 합치기
* concat: 두개의 데이터 프레임을 하나로 합침
* merge : sql join과 같은 역할 공통된 기준 컬럼 매칭해서 합침
* join : sql join과 같은 역할 index가 같은 것 끼리 합침

In [179]:
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb

In [182]:
engine = create_engine("mysql+pymysql://kict12:kict12@221.155.18.165:3306/titanic")
conn = engine.connect()

In [183]:
passenger = pd.read_sql("p_info", con=conn)
ticket = pd.read_sql("t_info", con=conn)
survived = pd.read_sql("survived", con=conn)
conn.close()

In [184]:
passenger.head(1)

   PassengerId                     Name   Sex   Age  SibSp  Parch
0            1  Braund, Mr. Owen Harris  male  22.0      1      0

In [185]:
ticket.head(1)

   PassengerId     Ticket  Pclass  Fare Cabin Embarked
0            1  A/5 21171       3  7.25  None        S

In [186]:
survived.head(1)

   PassengerId  Survived
0            1         0

## concat axis=0 행 추가, axis=1 열 추가
* 기준 컬럼 없이 무조건 합침
* 기본값은 행방향으로 합쳐줌
* 옆으로 붙이고 싶으면 axis=1

In [192]:
passenger.shape
ticket.shape

(891, 6)

In [190]:
df1 = pd.concat([passenger, ticket, survived], axis=1)
df1

,PassengerId,Name,Sex,Age,SibSp,Parch,PassengerId,Ticket,Pclass,Fare,Cabin,Embarked,PassengerId,Survived
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,1,A/5 21171,3,7.2500,None,S,1,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,2,PC 17599,1,71.2833,C85,C,2,1
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,3,STON/O2. 3101282,3,7.9250,None,S,3,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,4,113803,1,53.1000,C123,S,4,1
4,5,"Allen, Mr. William Henry",male,35.0,0,0,5,373450,3,8.0500,None,S,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0,887,211536,2,13.0000,None,S,887,0
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,888,112053,1,30.0000,B42,S,888,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,889,W./C. 6607,3,23.4500,None,S,889,0
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0,890,111369,1,30.0000,C148,C,890,1
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,891,370376,3,7.7500,None,Q,891,0

In [195]:
df0 = pd.concat([passenger, ticket, survived], axis=0)
df0.iloc[890:893, :]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
890,891,"Dooley, Mr. Patrick",male,32.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
0,1,NaN,NaN,NaN,NaN,NaN,A/5 21171,3.0,7.2500,None,S,NaN
1,2,NaN,NaN,NaN,NaN,NaN,PC 17599,1.0,71.2833,C85,C,NaN

# merge: sql의 join문과 같음

In [197]:
# select * from passenger left join ticket on passenger.PassengerId = ticket.PassengerId
joined_df = pd.merge(passenger, ticket, how="left", on="PassengerId")

In [199]:
joined_df = pd.merge(joined_df, survived, how="inner", on="PassengerId")
joined_df

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived_x,Survived_y
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,None,S,0,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1,1
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,None,S,1,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1,1
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,None,S,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0,211536,2,13.0000,None,S,0,0
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S,1,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,None,S,0,0
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,1,30.0000,C148,C,1,1
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,None,Q,0,0

# join: sql의 join과 같음, index명을 기준으로 합침

In [202]:
passenger = passenger.set_index("PassengerId")

,Name,Sex,Age,SibSp,Parch
PassengerId,,,,,
1,"Braund, Mr. Owen Harris",male,22.0,1,0
2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0
3,"Heikkinen, Miss. Laina",female,26.0,0,0
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0
5,"Allen, Mr. William Henry",male,35.0,0,0
...,...,...,...,...,...
887,"Montvila, Rev. Juozas",male,27.0,0,0
888,"Graham, Miss. Margaret Edith",female,19.0,0,0
889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2
890,"Behr, Mr. Karl Howell",male,26.0,0,0
891,"Dooley, Mr. Patrick",male,32.0,0,0

In [205]:
passenger.join(ticket)

ValueError: columns overlap but no suffix specified: Index(['PassengerId'], dtype='object')

In [206]:
survived = survived.set_index("PassengerId")

In [ ]:
joined_df2

# 중복여부 확인 및 제거하기

In [207]:
toss = pd.read_csv("./data/viva_republica_toss.csv", index_col=0)
toss.head(1)

,사용자,별점,리뷰,날짜,개발자 응답
0,Won Choi,2,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."

In [208]:
toss.info()

<class 'pandas.core.frame.DataFrame'>
Index: 52565 entries, 0 to 52564
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사용자     52531 non-null  object
 1   별점      52565 non-null  int64
 2   리뷰      52565 non-null  object
 3   날짜      52565 non-null  object
 4   개발자 응답  49611 non-null  object
dtypes: int64(1), object(4)
memory usage: 2.4+ MB

중복 컬럼 삭제하기 drop_duplicated()

In [210]:
toss = toss.drop_duplicates()
toss

,사용자,별점,리뷰,날짜,개발자 응답
0,Won Choi,2,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
1,최유연,1,"증권부분이 너무 빈약해요. 이평선, 분봉, 틱봉 자유롭게 수치를 설정할 수 있었음 ...",2025년 1월 18일,"안녕하세요. 최유연 님, 토스팀입니다. 토스증권 사용하시면서 주신 소중한 의견 너무..."
2,EXPRESS,1,주식 UI에서 홈과 관심 종목을 나눈 것도 불편한데 이번 자주 사용하는 계좌 업데이...,2025년 2월 25일,"안녕하세요. EXPRESS 님, 토스팀입니다. 우선 토스증권 이용에 불편을 드려 죄..."
3,JS P,1,언제 한 번 대대적으로 앱 퍼포먼스 최적화를 했으면 좋겠습니다. 예전엔 이러지 않았...,2025년 2월 28일,"안녕하세요. JS P 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였..."
4,AndPeter,1,앱 최적화 좀 해주세요! 무슨 메모리를 1GB나 잡아먹고 패킷전송이 하루에 80만건...,2025년 3월 1일,"안녕하세요. AndPeter 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
...,...,...,...,...,...
52560,나명자,5,사용은 편해요. 계좌개설 확인증이나 송금확인증 의 글씨가 좀 더 컸으면 좋겠습니다....,2024년 10월 31일,"안녕하세요. 나명자 님, 토스팀입니다. 토스를 이용하시면서 느끼신 소중한 의견을 주..."
52561,김주영,4,소비 관리하는 데 아주 유용하게 쓰고 있습니다. ktx 예매 때문에 코레일을 이용했...,2024년 11월 30일,"안녕하세요. 김주영님, 토스팀입니다. 우선, 토스 이용에 불편을 드려 죄송합니다. ..."
52562,bk im,1,편리함은 사라지고 불편함만 가중되고있음. 1. 동영상 광고 도입으로 토스 켤 때 마...,2023년 7월 25일,"안녕하세요. bk im님, 토스 고객센터입니다. 우선 많이 불편하셨음에도 시간내어 ..."
52563,임혜란,2,토스 편해서 사용했는데..최근에 토스에서 하는 꽃돼지이벤트 하다가 짜증났어요. 완전...,2025년 2월 27일,"안녕하세요. 임혜란님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였으나..."
52564,60 2,3,왜 알람이 안 울릴까요? 입출금 알람 설정해뒀는데 어느 순간부터 안 울리네요 그렇다...,2024년 11월 27일,"안녕하세요. 고객 님, 토스팀입니다. 이용에 불편을 드린 것 같아 마음이 무겁습니다..."

In [212]:
toss = toss.reset_index(drop=True)
toss

,사용자,별점,리뷰,날짜,개발자 응답
0,Won Choi,2,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
1,최유연,1,"증권부분이 너무 빈약해요. 이평선, 분봉, 틱봉 자유롭게 수치를 설정할 수 있었음 ...",2025년 1월 18일,"안녕하세요. 최유연 님, 토스팀입니다. 토스증권 사용하시면서 주신 소중한 의견 너무..."
2,EXPRESS,1,주식 UI에서 홈과 관심 종목을 나눈 것도 불편한데 이번 자주 사용하는 계좌 업데이...,2025년 2월 25일,"안녕하세요. EXPRESS 님, 토스팀입니다. 우선 토스증권 이용에 불편을 드려 죄..."
3,JS P,1,언제 한 번 대대적으로 앱 퍼포먼스 최적화를 했으면 좋겠습니다. 예전엔 이러지 않았...,2025년 2월 28일,"안녕하세요. JS P 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였..."
4,AndPeter,1,앱 최적화 좀 해주세요! 무슨 메모리를 1GB나 잡아먹고 패킷전송이 하루에 80만건...,2025년 3월 1일,"안녕하세요. AndPeter 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
...,...,...,...,...,...
508,나명자,5,사용은 편해요. 계좌개설 확인증이나 송금확인증 의 글씨가 좀 더 컸으면 좋겠습니다....,2024년 10월 31일,"안녕하세요. 나명자 님, 토스팀입니다. 토스를 이용하시면서 느끼신 소중한 의견을 주..."
509,김주영,4,소비 관리하는 데 아주 유용하게 쓰고 있습니다. ktx 예매 때문에 코레일을 이용했...,2024년 11월 30일,"안녕하세요. 김주영님, 토스팀입니다. 우선, 토스 이용에 불편을 드려 죄송합니다. ..."
510,bk im,1,편리함은 사라지고 불편함만 가중되고있음. 1. 동영상 광고 도입으로 토스 켤 때 마...,2023년 7월 25일,"안녕하세요. bk im님, 토스 고객센터입니다. 우선 많이 불편하셨음에도 시간내어 ..."
511,임혜란,2,토스 편해서 사용했는데..최근에 토스에서 하는 꽃돼지이벤트 하다가 짜증났어요. 완전...,2025년 2월 27일,"안녕하세요. 임혜란님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였으나..."
512,60 2,3,왜 알람이 안 울릴까요? 입출금 알람 설정해뒀는데 어느 순간부터 안 울리네요 그렇다...,2024년 11월 27일,"안녕하세요. 고객 님, 토스팀입니다. 이용에 불편을 드린 것 같아 마음이 무겁습니다..."