# 1.requests 모듈 : http 프로토콜을 사용할 수 있게 해주는 모듈
* requests 모듈 사용설명서
[requests](https://requests.readthedocs.io/en/latest/)

# 3. requests 모듈 사용법

* 1) 모듈 불러오기 : import requests
* 2) url 변수에 저장
* 3) url parameter
     * payload = {파라미터1 : value, 파라미터2 : value}
* 4) headers
     * headers = {key : value}
* 5) http 요청 보내기 get, post
     * get : r = requests.get(url, params=payload, headers=headers)
     * post : r = requests.post(url, data={key:value})
* 6) 만들어진 url 확인 : print(r.url)
* 7) 응답코드 확인 : print(r.status_code)
* 8) 응답 요소 출력 : r.text, r.content, r.json()

In [4]:
startnum2 = 1
for s_num in range(11):
    if startnum2 < 901:
        print(startnum2)
        startnum2 += 100
    elif startnum2 == 901:
        print(startnum2)
        startnum2 += 99
        print(startnum2)

1
101
201
301
401
501
601
701
801
901
1000

In [7]:
import requests
start_num = 1
result_json = []
for page in range(11):
    url = "https://openapi.naver.com/v1/search/blog"
    payload = {'query': '핀테크', 'display': 100, 'start': start_num, 'sort': "sim"}
    headers = {"X-Naver-Client-Id" : "YYIYgjstxPdUpH7WXuUE", "X-Naver-Client-Secret" : "wqrbMV9nRh"}
    r = requests.get(url, params=payload, headers=headers)
    print(r.url)
    print(r.status_code)
    data = r.json()
    result_json.append(data)
    if start_num < 901:
        start_num += 100
    elif start_num == 901:
        start_num += 99

https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=101&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=201&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=301&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=401&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=501&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=601&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=701&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=801&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=901&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200

In [11]:
pages = data["total"] // data["display"] +1
pages

4562

In [13]:
start_num = 1
response_json2 = []
for page in range(pages):
    import requests
    url = "https://openapi.naver.com/v1/search/blog"
    payload = {'query': '핀테크', 'display': 100, 'start': start_num, 'sort': "sim"}
    headers = {"X-Naver-Client-Id" : "YYIYgjstxPdUpH7WXuUE", "X-Naver-Client-Secret" : "wqrbMV9nRh"}
    r = requests.get(url, params=payload, headers=headers)
    print(r.url)
    print(r.status_code)
    data = r.json()
    response_json2.append(data)
    if start_num == 1000:
        break
    if start_num < 901:
        start_num += 100
    elif start_num == 901:
        start_num += 99

https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=101&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=201&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=301&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=401&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=501&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=601&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=701&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=801&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=901&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200

# While True로 전체데이터 가져오기

In [16]:
page = 1
start_num2 = 1
response_json3 = []
while True:
    import requests
    url = "https://openapi.naver.com/v1/search/blog"
    payload = {'query': '핀테크', 'display': 100, 'start': start_num2, 'sort': "sim"}
    headers = {"X-Naver-Client-Id" : "YYIYgjstxPdUpH7WXuUE", "X-Naver-Client-Secret" : "wqrbMV9nRh"}
    r = requests.get(url, params=payload, headers=headers)
    print(r.url)
    print(r.status_code)
    data = r.json()
    total_pages = (data["total"] // 100) +1
    response_json3.append(data)
    if start_num2 == 1000:
        break
    if start_num2 < 901:
        start_num2 += 100
    elif start_num2 == 901:
        start_num2 += 99
    if page <total_pages:
        page += 1
    else:
        break
print(len(response_json3))

https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=101&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=201&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=301&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=401&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=501&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=601&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=701&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=801&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=901&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200
11

# 블로그, 책, 뉴스 동시에 수집하기

In [21]:
import time
response_json3 = []
for category in ["blog", "news", "book"]:
    page = 1
    start_num2 = 1
    while True:
        url = f"https://openapi.naver.com/v1/search/{category}"
        payload = {'query': '핀테크', 'display': 100, 'start': start_num2, 'sort': "sim"}
        headers = {"X-Naver-Client-Id" : "YYIYgjstxPdUpH7WXuUE", "X-Naver-Client-Secret" : "wqrbMV9nRh"}
        r = requests.get(url, params=payload, headers=headers)
        print(r.url)
        print(r.status_code)
        data = r.json()
        total_pages = (data["total"] // 100) +1
        response_json3.append(data)
        if start_num2 == 1000:
            break
        if start_num2 < 901:
            start_num2 += 100
        elif start_num2 == 901:
            start_num2 += 99
            
        if page <total_pages:
            page += 1
        else:
            break
        time.sleep(0.5)
print(len(response_json3))

https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=101&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=201&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=301&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=401&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=501&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=601&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=701&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=801&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=901&sort=sim
200
https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200
https://openapi.naver.com/v1/search/news?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=sim
200
https://openapi.naver.com/v1/search/news?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=101&sort=sim
200
https://openapi.naver.com/v1/search/news?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=201&sort=sim
200
https://openapi.naver.com/v1/search/news?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=301&sort=sim
200
https://openapi.naver.com/v1/search/news?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=401&sort=sim
200
https://openapi.naver.com/v1/search/news?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=501&sort=sim
200
https://openapi.naver.com/v1/search/news?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=601&sort=sim
200
https://openapi.naver.com/v1/search/news?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=701&sort=sim
200
https://openapi.naver.com/v1/search/news?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=801&sort=sim
200
https://openapi.naver.com/v1/search/news?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=901&sort=sim
200
https://openapi.naver.com/v1/search/news?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200
https://openapi.naver.com/v1/search/book?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=sim
200
https://openapi.naver.com/v1/search/book?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=101&sort=sim
200
24

# 블로그, 뉴스, 책 데이터 각각 저장하기

In [16]:
import time
data_blog = []
data_news = []
data_book = []
keyward = input("검색할 키워드를 입력하세요.")
for category in ["blog", "news", "book"]:
    page = 1
    start_num2 = 1
    while True:
        url = (f"https://openapi.naver.com/v1/search/{category}.json")
        payload = {'query': 'keward', 'display': 100, 'start': start_num2, 'sort': "sim"}
        headers = {"X-Naver-Client-Id" : "YYIYgjstxPdUpH7WXuUE", "X-Naver-Client-Secret" : "wqrbMV9nRh"}
        r = requests.get(url, params=payload, headers=headers)
        data = r.json()
        total_pages = (data["total"] // 100) +1
        
        if category == "blog":
            data_blog.append(data)
        elif category == "news":
            data_news.append(data)
        elif category == "book":
            data_book.append(data)
            
        if start_num2 == 1000:
            break
        if start_num2 < 901:
            start_num2 += 100
        elif start_num2 == 901:
            start_num2 += 99
            
        if page <total_pages:
            page += 1
        else:
            break
        time.sleep(0.5)

검색할 키워드를 입력하세요.핀테크

In [6]:
import requests
import pandas as pd

In [17]:
def json_unpack(all_data):
    final_result = {}
    for page in all_data:
        for item in page['items']:
            for key, value in item.items():
                final_result_blog.setdefault(key, []).append(value)

    df = pd.DataFrame(final_result)
    return df

In [19]:
for jsons, cat in zip([data_blog, data_news, data_book]):
    unpack_result = json_unpack(jsons)
    unpack_result.to_csv(f"naver_{cat}_result.csv", encoding="utf-8", index=False)

ValueError: not enough values to unpack (expected 2, got 1)

# 3개 카테고리 수집 코드를 함수화하기

In [21]:
def naver_search(category):
    data_result = []
    page = 1
    start_num2 = 1
    while True:
        url = (f"https://openapi.naver.com/v1/search/{category}.json")
        payload = {'query': 'keward', 'display': 100, 'start': start_num2, 'sort': "sim"}
        headers = {"X-Naver-Client-Id" : "YYIYgjstxPdUpH7WXuUE", "X-Naver-Client-Secret" : "wqrbMV9nRh"}
        r = requests.get(url, params=payload, headers=headers)
        data = r.json()
        total_pages = (data["total"] // 100) +1
        
        data_result.append(data)
            
        if start_num2 == 1000:
            break
        if start_num2 < 901:
            start_num2 += 100
        elif start_num2 == 901:
            start_num2 += 99
            
        if page <total_pages:
            page += 1
        else:
            break
        time.sleep(0.5)
        
    return data_result

In [23]:
import time
keyward = input("검색할 키워드를 입력하세요.")
for category in ["blog", "news", "book"]:
    naver_search_result = naver_search(category)
    print(f"{category}_search_result: {len(naver_search_result)}")

검색할 키워드를 입력하세요.인공지능
blog_search_result: 1
news_search_result: 1
book_search_result: 1

In [2]:
payload

{'query': '핀테크', 'display': 100, 'start': 1, 'sort': 'sim'}

In [3]:
headers

{'X-Naver-Client-Id': 'YYIYgjstxPdUpH7WXuUE',
 'X-Naver-Client-Secret': 'wqrbMV9nRh'}

* 모든 검색결과를 가져오기 위해서는 여러 페이지 정보를 수집
* 전체 결과 / 1페이지 표시 개수 = 전체 페이지 수
* start 부분 + 1페이지 표시 개수 = 다음 페이지 데이터 수집 가능
* 반복문을 이용해서 start에 100씩 더해서 최대 1000이 되도록 하면 최대한 많은 데이터 수집 가능

네이버 검색 API를 이용해서 책을 검색하고 결과를 데이터프레임으로 만드세요.
* 검색어는 input()을 이용해서 입력받은 값을 이용하세요.

In [4]:
import requests
url = "https://openapi.naver.com/v1/search/book.json"
book = input("책 제목을 입력하세요")
payload = {'query': book, 'display': 100, 'start': 1, 'sort': "sim"}
headers = {"X-Naver-Client-Id" : "YYIYgjstxPdUpH7WXuUE", "X-Naver-Client-Secret" : "wqrbMV9nRh"}
r = requests.get(url, params=payload, headers=headers)
print(r.url)
print(r.status_code)
data = r.json()
data

책 제목을 입력하세요파이썬
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=1&sort=sim
200

{'lastBuildDate': 'Mon, 31 Mar 2025 17:12:52 +0900',
 'total': 1113,
 'start': 1,
 'display': 100,
 'items': [{'title': '혼자 만들면서 공부하는 파이썬 (37개 라이브러리와 API로 보고서, 차트, 게임, 맵, AI 챗봇 만들기|저자 직강 유튜브 강의, 오픈 채팅 제공)',
   'link': 'https://search.shopping.naver.com/book/catalog/52859338841',
   'image': 'https://shopping-phinf.pstatic.net/main_5285933/52859338841.20250209071357.jpg',
   'author': '문현일',
   'discount': '23400',
   'publisher': '한빛미디어',
   'pubdate': '20250214',
   'isbn': '9791169213271',
   'description': '“파이썬을 배워서 어디에 활용할 수 있을지 궁금했나요?”\n나의 신용카드 내역 분석, 우리 아파트 실거래가 시각화해보기, 맛집 지도 웹 앱 만들기 등 \n생활 속  15가지 파이썬 프로젝트를 직접 완성해 보며 재미있게 실전 경험 쌓기!\n\nQR 코드, 이미지 콜라주 등 일상과 가까운 생활형 프로젝트부터 부동산, 경제지표, 시가총액 같은 실용적인 데이터를 다루는 프로젝트, LLM, 멀티모달 AI와 TTS 등 최신 기술까지! 폭넓은 주제를 통해 흥미롭게 따라 해 보세요.\n\n●\t 주식 & 경제 데이터 분석 - 시가총액, 기준금리, 주요 경제지표 데이터 분석 및 시각화하기\n●\t 부동산 실거래가 분석 - 지역별 단위면적당 아파트 매매 실거래가 평균 지도로 만들기\n●\t 멀티모달 AI & 챗봇 개발 - 생성형 AI와 챗봇을 활용한 실시간 영자 신문 스크레이핑\n●\t 웹 자동화 & 크롤링 - 연관 키워드 분석을 통한 연령별, 성별 쇼핑 트렌드 분석\n●\t 게임 & GUI 개발 - 슬라이딩 퍼즐, 영어 받아쓰기 앱으로 직접 만들어 보는 인터랙티브 프로젝트'},
  {'title': '혼자 공부하는 파이썬 (1:1 과외하듯 배우는 프로그래밍 자습서)',
   'link': 'https://search.shopping.naver.com/book/catalog/32507605957',
   'image': 'https://shopping-phinf.pstatic.net/main_3250760/32507605957.20230509170119.jpg',
   'author': '윤인성',
   'discount': '19800',
   'publisher': '한빛미디어',
   'pubdate': '20220601',
   'isbn': '9791162245651',
   'description': '혼자 해도 충분하다! 1:1 과외하듯 배우는 파이썬 프로그래밍 자습서\n\n『혼자 공부하는 파이썬』이 더욱 흥미있고 알찬 내용으로 개정되었습니다. 프로그래밍이 정말 처음인 입문자도 따라갈 수 있는 친절한 설명과 단계별 학습은 그대로! 혼자 공부하더라도 체계적으로 계획을 세워 학습할 수 있도록 ‘혼공 계획표’를 새롭게 추가했습니다. 또한 입문자가 자주 물어보는 질문과 오류 해결 방법을 적재적소에 배치하여 예상치 못한 문제에 부딪혀도 좌절하지 않고 끝까지 완독할 수 있도록 도와줍니다. 단순한 문법 암기와 코딩 따라하기에 지쳤다면, 새로운 혼공파와 함께 ‘누적 예제’와 ‘도전 문제’로 프로그래밍의 신세계를 경험해 보세요! 배운 내용을 씹고 뜯고 맛보고 즐기다 보면 응용력은 물론 알고리즘 사고력까지 키워 코딩 실력이 쑥쑥 성장할 것입니다.\n\n이 책은 독학으로 파이썬을 배우는 입문자가 ‘꼭 필요한 내용을 제대로 학습’할 수 있도록 구성했습니다. 뭘 모르는지조차 모르는 입문자의 막연한 마음에 십분 공감하여 과외 선생님이 알려주듯 친절하게, 핵심적인 내용만 콕콕 집어줍니다. 책의 첫 페이지를 펼쳐서 마지막 페이지를 덮을 때까지, 혼자서도 충분히 파이썬을 배울 수 있다는 자신감과 확신이 계속될 것입니다!\n\n베타리더와 함께 입문자에게 맞는 난이도, 분량, 학습 요소 등을 적극 반영했습니다. 어려운 용어와 개념은 한 번 더 풀어쓰고, 복잡한 설명은 눈에 잘 들어오는 그림으로 풀어냈습니다. ‘혼자 공부해 본’ 여러 입문자의 초심과 눈높이가 책 곳곳에 반영된 것이 이 책의 가장 큰 장점입니다.'},
  {'title': 'Do it! 점프 투 파이썬 (중학생도 첫날부터 실습하는 초고속 입문서)',
   'link': 'https://search.shopping.naver.com/book/catalog/40354085633',
   'image': 'https://shopping-phinf.pstatic.net/main_4035408/40354085633.20230927071024.jpg',
   'author': '박응용',
   'discount': '19800',
   'publisher': '이지스퍼블리싱',
   'pubdate': '20230615',
   'isbn': '9791163034735',
   'description': '프로그래밍 분야 8년 연속 베스트셀러!\n《Do it! 점프 투 파이썬》 전면 개정 2판 출시!\n\n중고등학생도, 비전공자도, 직장인도 프로그래밍에 눈뜨게 만든 바로 그 책이 전면 개정 2판으로 새롭게 태어났다! 챗GPT를 시작으로 펼쳐진 생성 AI 시대에 맞춰 설명과 예제를 다듬고, 최신 경향과 심화 내용을 보충했다. 또한 이번 개정 2판도 50만 코딩 유튜버인 조코딩과 협업을 통해 유튜브 동영상을 제공해 파이썬을 더 쉽게 공부할 수 있다.\n\n8년 연속 베스트셀러! 위키독스 누적 방문 300만! 독자의 입에서 입으로 전해진 추천과 수많은 대학 및 학원의 교재 채택을 통해 검증은 이미 끝났다. 코딩을 처음 배우는 중고등학생부터 코딩 소양을 기르려는 비전공자, 자기계발에 진심인 직장인까지! 이 책과 함께 파이썬 프로그래밍의 세계로 ‘점프’해 보자!'},
  {'title': '밑바닥부터 시작하는 딥러닝 1(리마스터판) (파이썬으로 익히는 딥러닝 이론과 구현)',
   'link': 'https://search.shopping.naver.com/book/catalog/52615553184',
   'image': 'https://shopping-phinf.pstatic.net/main_5261555/52615553184.20250123071242.jpg',
   'author': '사이토 고키',
   'discount': '23400',
   'publisher': '한빛미디어',
   'pubdate': '20250124',
   'isbn': '9791169213387',
   'description': '딥러닝 분야 부동의 베스트셀러!\n머리로 이해하고 손으로 익히는 가장 쉬운 딥러닝 입문서\n\n이 책은 딥러닝의 핵심 개념을 ‘밑바닥부터’ 구현해보며 기초를 한 걸음씩 탄탄하게 다질 수 있도록 도와주는 친절한 안내서입니다. 라이브러리나 프레임워크에 의존하지 않고 딥러닝의 기본 개념부터 이미지 인식에 활용되는 합성곱 신경망(CNN)까지 딥러닝의 원리를 체계적으로 설명합니다. 또한 복잡한 개념은 계산 그래프를 활용해 시각적으로 전달하여 누구나 쉽게 이해할 수 있습니다. 이 책은 딥러닝에 첫발을 내딛는 입문자는 물론이고 기초를 다시금 다지고 싶은 개발자와 연구자에게도 훌륭한 길잡이가 되어줄 것입니다.'},
  {'title': '50개의 프로젝트로 완성하는 파이썬 업무 자동화 (프로젝트 따라하기로 업무 자동화 일잘러 되기!)',
   'link': 'https://search.shopping.naver.com/book/catalog/53737731866',
   'image': 'https://shopping-phinf.pstatic.net/main_5373773/53737731866.20250325080212.jpg',
   'author': '오토코더',
   'discount': '19800',
   'publisher': '위즈앤북(Wiznbook)',
   'pubdate': '20250317',
   'isbn': '9791198685353',
   'description': 'ㆍ퀴즈와 QR 코드 생성부터 나만의 음성 비서 제작까지 다양한 프로젝트 대공개!\nㆍ문서 번역, 파일 분류, 데이터 분석, 엑셀 문서, 영상 다운로드 등의 업무 자동화!\nㆍ뉴스, 날씨, 주식, 핫딜, 환율, 이커머스, 이미지 크롤링 등 데이터 자동 수집 및 관리!\nㆍChatGPT, Copilot, Gemini를 활용한 AI 스마트 자동화 노하우!\n\n이 책은 실무에서 바로 사용할 수 있는 50개의 프로젝트를 이용하여 업무 시스템 자동화, 애플리케이션 자동화, 인터넷 자동화 모델을 효율적으로 구현해 보고 완성할 수 있습니다. 특히, 인공지능과 데이터 분석 등에서 가장 많이 사용하는 파이썬 프로그래밍을 실제 다양한 업무 현장에서 활용하고자 하는 모든 분들을 위해 야심차게 준비했습니다.'},
  {'title': '제대로 시작하는 챗GPT와 AI 활용 with 파이썬 (프롬프트 엔지니어링, 음성 인식, 이미지 생성, 챗봇, 웹 서비스까지)',
   'link': 'https://search.shopping.naver.com/book/catalog/53683945404',
   'image': 'https://shopping-phinf.pstatic.net/main_5368394/53683945404.20250322092309.jpg',
   'author': '에이먼 엘 암리',
   'discount': '22500',
   'publisher': '한빛미디어',
   'pubdate': '20250324',
   'isbn': '9791169213639',
   'description': '파이썬으로 배우는AI와 챗GPT 활용법!\n매혹적인 인공지능의 세계를 탐험하며 실제 문제를 해결해 보세요\n\n지금껏 경험하지 못한 강력한 AI 개발의 세계로 여러분을 초대합니다!\n이 책은 오픈AI의 챗GPT, DALL·E, 위스퍼를 포함한 AI/ML 에코시스템의 다양한 도구를 사용하여 지능형 애플리케이션을 만드는 실용적 가이드입니다. 초중급 개발자 눈높이에 맞춰  최대한 이해하기 쉽게 구성했으며, 실용적인 파이썬 코드 예제로  더 쉽고 명확하게 학습할 수 있습니다. 챗GPT의 기본 개념부터 API 활용법, 애플리케이션 통합에 이르기까지 차근차근 살펴보며 초보 개발자와 현업 실무자 모두에게 모두에게 명쾌한 해답을 제공합니다. 챗봇, 시맨틱 검색 엔진, 분류 시스템, 추천 엔진 등 다양한  자연어/이미지/음성 처리 플랫폼을 구축하고자 한다면 이 책이 실질적인 도움을 줄 것입니다. GPT와 파이썬을 결합해 개발 능력을 한 단계 업그레이드하고 무궁무진한 AI의 가능성을 경험해 보세요. \n\n이 책의 특징\n●\tGPT 모델의 원리부터 파이썬 코드 구현까지 단계별로 명료하게 설명\n●\t실습 중심의 구체적인 예제로 빠르게 배우고 즉시 적용 가능\n●\t최신 API 사용법과 효율적인 프로그래밍 팁 제공 \n\n이 책에서 다루는 AI 애플리케이션 개발 사례 \n●\t파인 튜닝 도메인 특화 챗봇\n●\t기억을 보존하는 지능형 대화 시스템\n●\tRAG 기법을 사용한 최신 시맨틱 검색 엔진\n●\t사용자 취향에 맞춘 지능형 커피 추천 시스템\n●\t리눅스 명령어 작성을 돕는 챗봇 어시스턴트\n●\t대규모 정신 건강 대화 데이터셋을 학습한 AI 기반 정신 건강 코치\n●\t뉴스 기사 카테고리 분류 시스템\n●\t지능형 이미지 인식 시스템(이미지 to 텍스트)\n●\t이미지 생성 프로그램(텍스트 to 이미지)'},
  {'title': '파이썬',
   'link': 'https://search.shopping.naver.com/book/catalog/32460987987',
   'image': 'https://shopping-phinf.pstatic.net/main_3246098/32460987987.20230207163755.jpg',
   'author': '홍의경',
   'discount': '29440',
   'publisher': '생능출판',
   'pubdate': '20220309',
   'isbn': '9788970506784',
   'description': '코딩 실력을 키우는 지름길은 실습이다.\n\n2008년 즈음에 검인정 중학교 교과서 정보1, 정보2, 정보3을 공저로 저술하였습니다. 그 당시에 8종류의 교과서가 검인정에 합격하였는데, 파이썬을 기반으로 하는 교과서가 2종류, C언어를 기반으로 하는 교과서가 2종류, 베이직을 기반으로 하는 교과서가 2종류, 스크래치를 기반으로 하는 교과서가 2종류였습니다.\n\n교육용 언어로 시작한 파이썬이 중학교 학생들이 비교적 쉽게 학습할 수 있는 프로그래밍 언어라고 생각했는데 10여년의 세월이 흐른 지금 파이썬이 활용되는 분야가 가히 폭발적으로 증가하였습니다. \n\n파이썬에 관한 쉽고 좋은 교재를 저술하기 위해서 인터넷에서 30,000페이지 이상의 자료를 찾아서 검토하였습니다. 어쩌면 파이썬이 첫 프로그래밍 언어일 본 교재의 독자들이 두려움 없이 파이썬을 기초부터 쉽게 공부하다가, 교재를 다 읽고 나면 “어느새 중급 수준에 도달했구나”라는 생각이 들도록  완성도 높은 교재를 목표로 하였습니다. \n\n입문자를 대상으로 하는 교재일수록 집필하는데 훨씬 더 많은 정성과 노력이 필요하다는 것을 잘 알고 있습니다. 개인적으로는 데이터베이스 전공교재를 저술할 때보다 몇 배 더 힘들었고, 공을 많이 들였습니다. \n\n원고를 버전 9까지 작성하는 동안 셀 수 없이 원고를 읽어보면서 꼭 필요하지 않은 문장은 삭제하고, 필요한 문장은 반드시 넣었습니다. 고등학교 검인정 교과서 1권, 중학교 검인정 교과서 3권, 데이터베이스 전공 교재 2권, 엑셀 교재 1권, 번역서 2권을 집필하면서 나름대로 한글을 정확하고 간결하게 표현하는데 자신이 있습니다.'},
  {'title': 'CODING BASICS PYTHON (파이썬)',
   'link': 'https://search.shopping.naver.com/book/catalog/32440944646',
   'image': 'https://shopping-phinf.pstatic.net/main_3244094/32440944646.20230509164030.jpg',
   'author': '김상민^장성식^김일태',
   'discount': '18000',
   'publisher': '렉스미디어닷넷',
   'pubdate': '20220210',
   'isbn': '9788959604210',
   'description': '파이썬으로 다지는 프로그래밍의 기초\n\nㆍ 다양한 예제를 활용하여 초보자도 쉽게 프로그래밍의 기본을 익힐 수 있는 파이썬 입문서입니다.\nㆍ 문법을 사전식으로 나열하지 않고 기능적인 프로그램을 하나씩 완성하면서 익힐 수 있게 구성했습니다.\nㆍ 단계별로 완성하는 장별 예제 및 연습문제를 바탕으로 자신만의 프로그램을 완성할 수 있습니다.'},
  {'title': '파이썬 (제2판)',
   'link': 'https://search.shopping.naver.com/book/catalog/32436240934',
   'image': 'https://shopping-phinf.pstatic.net/main_3243624/32436240934.20230928092006.jpg',
   'author': '염기원^오지영',
   'discount': '16200',
   'publisher': '북두',
   'pubdate': '20220120',
   'isbn': '9791166750991',
   'description': '책의 전반부는 비전공자의 입장에서 비전공자를 위한 파이썬 프로그래밍의 기초적인 내용으로 구성되어 있다. 프로그래밍에 익숙하거나 파이썬 경험이 있는 독자들은 곧바로 책의 후반부를 공부하는 것을 권한다. 책의 전반부에서는 저자가 처음 컴퓨터 프로그래밍이라는 것을 배울 때 가장 어려워했던 변수와 메모리 관계, 특성에 대해서 상세하게 설명하면서 비전공자들이 쉽게 프로그래밍에 입문할 수 있도록 하였다. 대부분의 프로그래밍 교재와 다를바 없이, 파이썬으로 프로그램을 작성할 수 있도록 개발환경을 설치하는 과정과 사용 가능한 프로그래밍 툴에 대해서도 빠지지 않고 최대한 상세한 설명과 충분한 그림을 삽입하였다. 또한, 전반부의 뒷부분은 데이터 분석에 필요한 파이썬 프로그램 위주로 구성해서 앞부분의 기초 프로그래밍 지식을 바탕으로 본격적인 데이터 분석을 위한 토대를 마련할 수 있도록 구성하였다.'},
  {'title': '파이썬',
   'link': 'https://search.shopping.naver.com/book/catalog/32489150082',
   'image': 'https://shopping-phinf.pstatic.net/main_3248915/32489150082.20230207165503.jpg',
   'author': '천인국',
   'discount': '10800',
   'publisher': '인피니티북스',
   'pubdate': '20170830',
   'isbn': '9791185578330',
   'description': '컴퓨팅 사고(Computational Thinking)는 자넷 윙 교수가 2006년에 컴퓨터 학술지에서 언급한 이후로 컴퓨터 교육 분야에서 상당한 이슈가 되고 있는 용어이다. 컴퓨팅 사고는 복잡한 문제를 분해하여 문제 안에 내재된 패턴을 찾고 추상화 단계를 거쳐서 문제를 해결하는 알고리즘을 작성하는 과정이다. 작성된 알고리즘은 사람이 수행하거나 컴퓨터를 이용하여 자동화될 수 있다. \n이 책은 컴퓨팅 사고와 파이썬을 동시에 학습할 수 있도록 기획되었다. 파이썬은 컴퓨터를 전공하지 않은 학생들도 쉽게 사용할 수 있다는 큰 장점이 있다. 컴퓨팅 사고는 흥미로운 실습 예제가 많이 필요하다. 이 책에서는 최대한 많은 실습 예제를 간추려서 파이썬으로 실습할 수 있도록 하였다. 파이썬은 다양한 애니메이션이나 가상 실습을 만들 수 있는 최적의 도구이다. 학생들은 파이썬을 통하여 컴퓨터 프로그래밍의 기본적인 개념들과 컴퓨팅 사고에서 나타나는 다양한 실습을 수행할 수 있을 것이다.'},
  {'title': '파이썬 (비전공자를위한 파이썬 기초 입문서)',
   'link': 'https://search.shopping.naver.com/book/catalog/32436003648',
   'image': 'https://shopping-phinf.pstatic.net/main_3243600/32436003648.20230920072841.jpg',
   'author': '김명호',
   'discount': '16200',
   'publisher': '에듀웨이',
   'pubdate': '20190525',
   'isbn': '9791186179369',
   'description': '막막했던 파이썬, 이제 한 권으로 기초를 배우는\n파이썬 사용 설명서!\n\n전 세계적으로 유명한 구글(Google)이 자신의 많은 서비스를 파이썬으로 제공하고 있습니다. 이것은 구글의 뛰어난 서비스를 개인의 비즈니스에 쉽게 이용할 수 있다는 의미입니다.  이러한 발전에 맞춰 파이썬 문법의 기초를 쉽게 이해할 수 있도록 이 책에서는 친절한 도해와 함께 코딩 개념을 설명합니다. 파이썬을 처음 배우는 학생부터 비전공자, 코딩 실력을 높이려는 직장인까지 기본 문법부터 예제를 통한 활용 실력을 높여 파이썬 프로그래밍을 마스터할 수 있습니다. 가장 쉽고, 빠르게, 효율적인 파이썬 사용 설명서! ‘한 권으로 끝내는 파이썬’에서 찾아보세요.'},
  {'title': '파이썬',
   'link': 'https://search.shopping.naver.com/book/catalog/32490271648',
   'image': 'https://shopping-phinf.pstatic.net/main_3249027/32490271648.20220527033830.jpg',
   'author': '염기원',
   'discount': '0',
   'publisher': '복두출판사',
   'pubdate': '20200820',
   'isbn': '9791159069048',
   'description': '비전공자의 데이터 분석을 위한 『파이썬』은 〈파이썬 기초〉, 〈파이썬을 이용한 데이터 분석 기초〉, 〈시각화 라이브러리 사용하기〉 등 파이썬의 기초적이고 전반적인 내용이 수록되어 있다.'},
  {'title': '파이썬',
   'link': 'https://search.shopping.naver.com/book/catalog/32438172833',
   'image': 'https://shopping-phinf.pstatic.net/main_3243817/32438172833.20230920072917.jpg',
   'author': '김영천',
   'discount': '23750',
   'publisher': '기한재',
   'pubdate': '20200225',
   'isbn': '9788970187990',
   'description': '▶ 이 책은 Python(파이썬)을 다룬 이론서입니다. Python(파이썬)의 기초적이고 전반적인 내용을 학습할 수 있습니다.'},
  {'title': '파이썬',
   'link': 'https://search.shopping.naver.com/book/catalog/32505098970',
   'image': 'https://shopping-phinf.pstatic.net/main_3250509/32505098970.20220527074158.jpg',
   'author': '서정원^김태령',
   'discount': '0',
   'publisher': '생능출판',
   'pubdate': '20190228',
   'isbn': '9788970509723',
   'description': '이 책은 지금까지 경험하지 못한 코딩 교육의 진수를 보여준다. “코딩 교육이 가야 할 방향은 컴퓨팅 사고력을 높이는 것이다.”라고 이 책의 저자들이 말하듯, “디지털 시대에 적합한 창의력과 문제해결력을 기르기 위한 코딩의 기초부터 응용까지 컴퓨터 코드를 작성하는 것은 물론이고, 알고리즘 학습을 통한 컴퓨팅 사고력을 완전 정복한다.'},
  {'title': '파이썬 (다양한 예제로 알로리즘 쉽게 분석하기)',
   'link': 'https://search.shopping.naver.com/book/catalog/32441765959',
   'image': 'https://shopping-phinf.pstatic.net/main_3244176/32441765959.20220527045202.jpg',
   'author': '김유진',
   'discount': '22500',
   'publisher': '다본',
   'pubdate': '20190410',
   'isbn': '9791188577255',
   'description': '파이썬은 인터프리터 방식으로 접근이 쉬운 반면 다양한 기능의 라이브러리들이 제공되어 빅 데이터나 머신 러닝, 순수 과학, 웹, GUI 등 다양한 분야에서 사용되고 있다. 또한, 파이썬은 이식성이 높고 모듈 제작이 가능하기 때문에 자주 사용하는 기능을 모듈로 제작하여 해당 기능이 필요할 때마다 작성한 모듈을 임포트(import)하여 사용할 수 있다. 이처럼 많은 장점을 가진 파이썬은 특히 빅 데이터나 머신 러닝, 사물 인터넷, 웹에서 많이 사용되므로 해당 분야와 관련해 취업을 준비하거나 공부하는 학생 그리고 이런 분야와 관련된 일을 하는 개발자들에게 꼭 필요한 프로그램 언어이므로 이 책은 이들에게 좋은 참고서가 될 것이다.'},
  {'title': '파이썬',
   'link': 'https://search.shopping.naver.com/book/catalog/32441653441',
   'image': 'https://shopping-phinf.pstatic.net/main_3244165/32441653441.20230418164550.jpg',
   'author': 'Y. Daniel Liang',
   'discount': '31500',
   'publisher': '에피스테메',
   'pubdate': '20180302',
   'isbn': '9788920028892',
   'description': '이 책은 누구나 쉽게 따라할 수 있는 파이썬 프로그래밍 언어에 기반하고 있기 때문에 프로그래밍을 통해 얻을 수 있는 논리 능력 향상과 문제 해결력 배양에 가장 적합하다. \n비전공자도 쉽게 이해하고 활용할 수 있는 풍부한 예제를 제공하여 프로그래밍의 기본 개념 정립에 도움을 주며 실생활과 밀접하게 관련된 다양한 사례 연구를 통해 실생활의 문제 해결 능력을 자연스럽게 배양시킨다.\n 이 책을 활용한 프로그래밍 학습을 통해 파이썬 프로그램을 스스로 작성하고 실행해 봄으로써 자신만의 프로그램을 작성할 수 있다는 뿌듯함을 느껴볼 수 있다. \n객체지향 개념과 그래픽 처리, 이벤트 처리 등이 쉽게 설명되어 있어 복잡하지 않고 간단하게 프로그램에 추가하여 다양한 기능을 가진 자신만의 프로그램도 작성해 볼 수 있다.\n이 책은 파이썬 언어에 대한 기본 문법부터 활용까지 프로그래밍에 관한 전반적인 내용을 다루고 있고 원저자의 경험과 능력, 치밀한 구성에 의해 완성한 책인 만큼 완성도 및 충실도는 매우 뛰어나다. \n그동안 무심코 넘어갔던 개념들에 대해서 다시 한 번 생각해 보는 계기를 마련해 준다. 그만큼 이 책은 파이썬 프로그래밍 언어에 대한 개념과 활용을 집대성했기 때문이다. 그래서 IT 전공자뿐만 아니라 광범위한 분야에서 프로그래밍에 관심 있는 입문자들에게 많은 도움과 개념을 정리해 줄 수 있는 책이다.'},
  {'title': '파이썬',
   'link': 'https://search.shopping.naver.com/book/catalog/32504743740',
   'image': 'https://shopping-phinf.pstatic.net/main_3250474/32504743740.20220527031429.jpg',
   'author': 'Y. Daniel Liang',
   'discount': '0',
   'publisher': '생능출판',
   'pubdate': '20160205',
   'isbn': '9788970508504',
   'description': '[파이썬]은 파이썬 언어에 대한 기본 문법부터 활용까지 프로그래밍에 관한 전반적인 내용을 다루고 있다. 이 책을 활용한 프로그래밍 학습을 통해 파이썬 프로그램을 스스로 작성하고 실행해 봄으로써 자신만의 프로그램을 작성할 수 있을 것이다.'},
  {'title': '내공의 파이썬 (한 권으로 끝내는 초보자용 코딩 입문서)',
   'link': 'https://search.shopping.naver.com/book/catalog/53550577590',
   'image': 'https://shopping-phinf.pstatic.net/main_5355057/53550577590.20250315093055.jpg',
   'author': '한선관',
   'discount': '24300',
   'publisher': '자유아카데미',
   'pubdate': '20250315',
   'isbn': '9791158087005',
   'description': '『내공의 파이썬』은 파이썬을 처음 접하는 독자들이 기본 개념을 쉽게 익히고, 점진적으로 내공의 실력을 쌓을 수 있도록 구성하였다. 단순한 문법 암기에 그치지 않고, 실제 코딩에 적용할 수 있는 능력을 기를 수 있도록 다양한 예제와 실습 문제를 포함하였다. 또한, 프로그래밍의 기초 개념을 배우는 과정에서 컴퓨터과학적 사고를 함께 익힐 수 있도록 ‘기초 내공 쌓기’, ‘도전 내공 쌓기’, ‘기초튼튼 컴퓨터과학’ 등의 코너를 마련하여 독자들이 문제 해결 능력을 기르면서 컴퓨터과학의 개념과 자연스럽게 연결 지을 수 있도록 하였다.'},
  {'title': '파이썬 머신러닝 완벽 가이드 (다양한 캐글 예제와 함께 기초 알고리즘부터 최신 기법까지 배우는)',
   'link': 'https://search.shopping.naver.com/book/catalog/32485894885',
   'image': 'https://shopping-phinf.pstatic.net/main_3248589/32485894885.20230620101232.jpg',
   'author': '권철민',
   'discount': '29800',
   'publisher': '위키북스',
   'pubdate': '20220421',
   'isbn': '9791158393229',
   'description': '자세한 이론 설명과 파이썬 실습을 통해 머신러닝을 완벽하게 배울 수 있습니다!\n\n《파이썬 머신러닝 완벽 가이드》는 이론 위주의 머신러닝 책에서 탈피해, 다양한 실전 예제를 직접 구현해 보면서 머신러닝을 체득할 수 있도록 만들었습니다. 캐글과 UCI 머신러닝 리포지토리에서 난이도가 있는 실습 데이터를 기반으로 실전 예제를 구성했고, XGBoost, LightGBM, 스태킹 기법 등 캐글의 많은 데이터 사이언스에서 애용하는 최신 알고리즘과 기법을 상세하게 설명했습니다.\n\n이번 개정2판에서는 최신 사이킷런 버전(1.0.2)을 포함해 책에서 사용되는 모든 라이브러리를 최신 버전으로 업그레이드한 실습 코드를 구현하고, 다양한 유형의 하이퍼파라미터를 가지는 XGBoost나 LightGBM 모델의 최적 하이퍼파라미터 튜닝을 위한 베이지안 최적화 기법 적용 실습을 제공합니다. 또한 머신러닝 관련 데이터 분석에 널리 쓰이는 시각화 라이브러리인 matplotlib과 seaborn의 활용법을 다룬 장을 새롭게 추가했습니다.'},
  {'title': '독학 파이썬',
   'link': 'https://search.shopping.naver.com/book/catalog/51981118640',
   'image': 'https://shopping-phinf.pstatic.net/main_5198111/51981118640.20241224071117.jpg',
   'author': '야마다 요시히로',
   'discount': '28800',
   'publisher': '정보문화사',
   'pubdate': '20241220',
   'isbn': '9788956749891',
   'description': '이론과 실전이 모두 담긴 단 한 권의 파이썬 교과서\n\n처음 파이썬 프로그래밍을 시작하는 사람 또는 더욱 깊은 내용을 목표로 하는 사람에게 정확한 지식을 제공하기 위해 쓰였다. 파이썬 프로그래밍을 위한 환경 설정과 파이썬만의 기본 규칙에서 시작해 연산자, 라이브러리, 객체지향 구문까지 다뤘다. 파이썬을 보다 정확하게 이해해 책 속 예제 코드뿐만 아니라 실전에서 관련 지식을 활용할 수 있도록 꼼꼼하게 설명한다. 이렇게 기초를 탄탄하게 세운 후, 의식하면 좋은 파이썬 개발 관습과 보다 간단한 표현법을 언급해 프로그래밍 능력을 차근차근 키울 수 있게 했으며, 이 책 한 권으로 독학부터 협업까지 가능하게 했다.\n또한 이 책은 중간에 포함된 연습 문제의 해답을 제공한다. 챕터와 절이 끝날 때마다 단답형, 코드 작성, OX 등의 연습 문제가 다양하게 제공되는데, 독학이 가능한 파이썬 교과서답게 모든 연습 문제의 해답을 부록으로 실어 독자의 답답함을 해소했다. 꼼꼼하면서 실무적인 설명과 해답이 있는 연습 문제에 더불어 각종 팁이 담긴 ‘note’와 추가 정보를 담은 ‘전문가에게 묻기’, ‘칼럼’이 곳곳에 준비되어 있어, 파이썬을 독학으로 마스터하려는 사람, 파이썬의 어느 부분을 공부해야 할지 망설여졌던 사람에게 특히 도움이 될 것이다.'},
  {'title': '파이썬으로 쉽게 배우는 자료구조 (개정판)',
   'link': 'https://search.shopping.naver.com/book/catalog/40595743620',
   'image': 'https://shopping-phinf.pstatic.net/main_4059574/40595743620.20230711115354.jpg',
   'author': '최영규^천인국',
   'discount': '26680',
   'publisher': '생능출판',
   'pubdate': '20230626',
   'isbn': '9791192932187',
   'description': '자료구조(data structure)는 컴퓨터로 처리할 자료들을 효율적으로 관리하고 구조화시키기 위한 학문으로 컴퓨터 분야에서 매우 중요하고 기초적인 과목이다. 그러나 개념의 이해와 함께 코딩을 통한 구현 능력이 필수적으로 요구되기 때문에 학생들이 어려워하는 과목이기도 하다.\n이 책은 입문자들이 보다 쉽고 재미있게 자료구조를 공부하고 다양한 문제 해결에 활용할 수 있는 능력을 기르는데 초점을 맞추었다.'},
  {'title': '파이썬 마스터 (실생활 융합 예제로 배우는)',
   'link': 'https://search.shopping.naver.com/book/catalog/52509305501',
   'image': 'https://shopping-phinf.pstatic.net/main_5250930/52509305501.20250123071218.jpg',
   'author': '김종훈^김동건',
   'discount': '31040',
   'publisher': '한빛아카데미',
   'pubdate': '20250117',
   'isbn': '9791173400018',
   'description': '파이썬 프로그래밍 기초와 데이터 분석을\n한 권으로 마스터하는 파이썬 기본서!\n\n『파이썬 마스터』는 파이썬을 처음 배우는 독자를 대상으로 하는 책이며, 파이썬의 기초 문법부터 넘파이, 판다스, 데이터 시각화, 머신러닝과 딥러닝까지 학습할 수 있다. 각 장에는 꼭 알아야 하는 파이썬의 핵심 개념과 문법을 다루고 있으며, 더 나아가 실제 개발에 필요한 실력을 쌓을 수 있도록 5단계 반복 학습 과정을 제공한다. 이 책의 단계별 훈련으로 문제 해결 능력을 키우고 파이썬을 마스터하길 바란다.\n\n※ 본 도서는 대학 강의용 교재로 개발되었으므로 연습문제 해답은 제공하지 않습니다.'},
  {'title': '파이썬 워크북',
   'link': 'https://search.shopping.naver.com/book/catalog/52417646624',
   'image': 'https://shopping-phinf.pstatic.net/main_5241764/52417646624.20250111113916.jpg',
   'author': '안기수',
   'discount': '13500',
   'publisher': '생능출판',
   'pubdate': '20250115',
   'isbn': '9791192932682',
   'description': '파이썬 언어의 가장 큰 특징은 문법이 간결하여 배우기 쉽다는 것이다. 그러나 이미 만들어진 프로그램이나 어플을 단지 활용만 해보다가 그 프로그램이 어떤 언어로 만들어진 것인지, 그 어플이 어떤 과정을 거쳐서 만들어진 것인지를 알아보려는 시점에서 그것을 만드는데 사용한 언어가 아무리 쉽다하더라도 컴퓨터 언어 자체가 우리가 사용하는 언어처럼 익숙한 것이 아니므로 어려움을 느낄 수밖에 없다.\n\n컴퓨터 언어의 실습시간에 학생들에게 “궁금한 것 또는 이해되지 않는 부분에 대해 질문하세요?”라고 물어봤을 때 언젠가 한 학생이 “뭘 알아야 질문을 하죠?”라고 말한 적이 있다. 그 말의 의미가 무엇인지 대략은 이해하지만, 나의 대답은 이러했다. “뭘 알면 질문할 필요가 있나요? 모르니까 질문을 하는 것이 아닐까요?”\n여기서 중요한 것은 그 학생의 경우 수업내용을 이해하지 못하면 무슨 질문을 해야 할지를 모른다는 것이고, 조금이라도 뭘 좀 알고 있어야, 지식이 좀 있어야 질문할 수 있다고 생각한다는 점이다. 이러한 생각이 틀렸다고 생각하지는 않지만 학생들마다 수업에 대한 이해 정도가 다르므로 무엇을 이해했고 무엇을 이해하지 못하고 있는 것인지를 스스로 판단할 수 있도록 유도한다면 이러한 문제가 해소되지 않을까 생각한다.\n\n프로그램 언어를 설명한 대부분의 책들은 각 단원의 마지막 부분에 있는 연습문제를 통해 이해의 정도를 스스로 판단하도록 하지만, 풀어나갈 문제의 난이도 또는 주관식 문제가 주는 부담감으로 문제를 풀 엄두가 나지 않는 경우가 발생하기도 한다. 이러한 부담감을 줄여주기 위한 방법을 고민하다가 가급적 학생들이 문제를 스스로 해결해 나갈 수 있도록 문제 풀이에 관심을 갖게 하고, 틀린 이유와 원인을 실습을 통해 확인하고 메모해가면서 자기주도의 반복 학습으로 유도하기 위하여 워크북을 이용하고자 한다.\n따라서 이 워크북은 수업이 끝나고 과제로 남겨두는 것이 아니라 수업 시간에 학생들 스스로가 직접 코딩하고 실행하여 결과를 확인하고, 나름대로 틀린 부분들을 요약하는 오답노트로 활용하여 프로그램 작성에 대한 이해도와 자신감을 점차 높이도록 구성하였다.'},
  {'title': '파이썬 + AI (코드조각과 실행화면으로 배우는 코딩)',
   'link': 'https://search.shopping.naver.com/book/catalog/48703888619',
   'image': 'https://shopping-phinf.pstatic.net/main_4870388/48703888619.20240627091044.jpg',
   'author': '안용제^김남규',
   'discount': '25200',
   'publisher': '디지털북스',
   'pubdate': '20240715',
   'isbn': '9788960884571',
   'description': '“코드조각과 실행화면을 통해, 단계적 반복을 통해 배우는 파이썬과 AI”\n\n이 책은 프로그래밍 언어에 익숙한 프로그래머가 아닌 프로그램 입문자들을 대상으로 프로그래밍에 대해 아무런 지식이 없다고 가정하고 프로그램 코딩을 가르치기 위해 작성되었습니다. 이 책을 통해 코딩 개요, Python 기초, numpy, matplotlib, pandas 그리고 머신러닝/딥러닝 퀵스타트 등 Python의 전반을 한 권으로 학습할 수 있습니다.\n또한 코드조각이라고 부르는 프로그램 코딩에 대한 예제를 설명을 위한 주축으로 사용합니다. 그래서 코드조각을 먼저 이해하려고 노력한 후 코드조각을 실행하여 얻게 되는 실행화면을 통해, 코딩의 결과를 바로바로 확인할 수 있도록 하였습니다. 코드조각을 컴퓨터에 입력하여 실행시켜 보면서 프로그램의 수행 결과를 자세히 관찰하고, 프로그램 코드를 한 줄씩 따라가면서 변수와 객체 등 컴퓨터 저장 공간의 변화를 함께 따라가 보면 어느새 파이썬과 AI 코딩을 능숙하게 활용할 수 있을 것입니다.'},
  {'title': '파이썬 3 (프로그래밍을 배우기에 가장 재미있는 언어)',
   'link': 'https://search.shopping.naver.com/book/catalog/32485534946',
   'image': 'https://shopping-phinf.pstatic.net/main_3248553/32485534946.20221019105212.jpg',
   'author': '박상현',
   'discount': '0',
   'publisher': '한빛미디어',
   'pubdate': '20160210',
   'isbn': '9788968482359',
   'description': '본서는 프로그래밍 경험이 없는 독자가 파이썬을 통해 프로그래밍을 배워볼 수 있는 입문서로서, 프로그래밍을 배우고 싶지만 두려움이 있는 입문자에게 가장 적합한 난이도로 설명한다.'},
  {'title': '으뜸 파이썬 (개정판)',
   'link': 'https://search.shopping.naver.com/book/catalog/48359296619',

In [2]:
def json_unpack(data):
    result = {}
    for item in data["items"]:
        for key, value in item.items():
            result.setdefault(key, []).append(value)
    result
    import pandas as pd
    df = pd.DataFrame(result)
    return df

In [1]:
import requests
url = "https://openapi.naver.com/v1/search/book.json"
book = input("책 제목을 입력하세요")
payload = {'query': book, 'display': 100, 'start':1000 , 'sort':'sim'}
headers = {"X-Naver-Client-Id":"YYIYgjstxPdUpH7WXuUE", "X-Naver-Client-Secret":"wqrbMV9nRh"}
r = requests.get(url, params=payload, headers=headers)
print(r.url)
print(r.status_code)
data = r.json()
print("전체 검색 데이터 수 :", data["total"], "검색할 페이지수:", (int(data["total"])//100)+1)

책 제목을 입력하세요파이썬
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=1000&sort=sim
200
전체 검색 데이터 수 : 1113 검색할 페이지수: 12

In [7]:
result_df = json_unpack(data)
result_df

,title,link,image,author,discount,publisher,pubdate,isbn,description
0,파이썬과 케라스를 이용한 딥러닝/강화학습 주식투자 (퀀트 투자 알고리즘 트레이딩을 ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324920...,김문권,0,위키북스,20180529,9791158391065,강화학습은 스스로 학습하는 머신러닝 기법으로서 주식 데이터 학습에 잘 적용되는 기법...
1,슬기로운 코딩 생활 with 파이썬 으랏차차 기초편 (즐겁게 시작하고 똑똑하게 끝내...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324902...,김정욱,0,루비페이퍼,20180515,9791186710333,"수학, 과학, 국어, 사회 등 실제 초중등 교과 과목과 연계된 예제로 코딩력과 학습..."
2,2024 내일은 빅데이터분석기사 실기 with 파이썬 (제6회부터 변경된 작업형 제...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_434140...,Jade Jeong,20700,김앤북,20231030,9788965127925,「2024 내일은 빅데이터분석기사 실기」는 자격증을 준비하는 수험생 & 재직자(비전...
3,2024 빅데이터분석기사 실기 한권완성: 파이썬(Python) (작업형 제3유형 완...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_461080...,최예신^박진원^이경숙^김주현,27000,예문에듀,20240520,9791163862833,빅데이터분석기사 실기시험 초단기 합격을 위한 최고의 실전 대비서\n‘2024 빅데이...
4,Step by Step CRM을 위한 파이썬 머신러닝 (빅 데이터 분석 자격증 머신...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_394909...,김형수,30000,프레딕스,20230501,9791195511792,"본서는 파이썬을 전혀 모르는 사람도, 프로그래밍을 전혀 해보지 않은 사람도 단계적으..."
...,...,...,...,...,...,...,...,...,...
95,"챗GPT와 업무자동화 (1분 만에 끝내는 엑셀, 구글 시트, 파워포인트, 파이썬 자...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_386135...,김철수,16200,위키북스,20230321,9791158394288,"코드 한 줄 몰라도 1분 만에 끝내는 엑셀, 구글 스프레드시트, 파워포인트 업무 자..."
96,프로그래밍 정석(개념을 잡아주는) (기초 연산부터 고급 문제해결 능력까지 파이썬을 ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324972...,제니퍼 캠벨^폴 그리스^제이슨 몬토조^그렉 윌슨,0,에이콘출판,20100504,9788960771338,"『개념을 잡아주는 프로그래밍 정석』은 기본적인 프로그래밍 요소부터 알고리즘, 디버깅..."
97,머신러닝 딥러닝을 이용한 A.I. 자율주행 RC카 프로젝트 with 파이썬+아두이노...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324665...,서민우,0,앤써북,20220520,9791185553979,〈머신러닝 딥러닝을 이용한 A.I. 자율주행 RC카 프로젝트 with 파이썬+아두이...
98,파이썬 딥러닝 파이토치(Python Deep Learning PyTorch),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324549...,이경택^방성수^안상준,14800,정보문화사,20201008,9788956748573,파이썬은 선택이 아닌 필수! 파이토치로 딥러닝 입문하기!\n\n이 책은 딥러닝 기술...
99,Let’s Start Coding with Raptor & Python (랩터 & ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324972...,김충석,0,앤아이컴즈,20190815,9788993163568,▶ 이 책은 Python(파이썬)을 다룬 이론서입니다.

# 네이버 API로 검색한 결과 최대한 가져오기
* 1회 네이버 서버에 요청
* 응답에서 total을 찾아서 dispalay로 나누어 총 반복할 페이지 산출
* 반복문 작성 및 종료 조건 설정
* 1페이지 결과를 데이터 프레임으로 만들고 리스트에 append
* 반복이 끝난 후 리스트에 append된 데이터 프레임을 1개로 합침

# for문을 이용해서 전체 페이지 가져오기

In [3]:
keyword = input("검색할 키워드를 입력해 주세요: ")

검색할 키워드를 입력해 주세요: 파이썬

In [4]:
all_data = []

In [5]:
url = "https://openapi.naver.com/v1/search/book.json"
Client_Id = "YYIYgjstxPdUpH7WXuUE"
Client_Secret = "wqrbMV9nRh"
headers = {"X-Naver-Client-Id" : Client_Id, "X-Naver-Client-Secret" : Client_Secret}
payload = dict(query=keyword, display=100, start=1, sort="sim")
r = requests.get(url, params=payload, headers=headers)
print(r.url)
print(r.status_code)
data = r.json()
n_data = data['total']
total_pages = (int(data['total'])//100)+1
print("전체 검색 데이터 수: ", n_data, "검색할 페이지수: ", total_pages )
result_df = json_unpack(data)
all_data.append(result_df)

https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=1&sort=sim
200
전체 검색 데이터 수:  1113 검색할 페이지수:  12

In [6]:
start = 101
for page in range(total_pages):
    print(f"{page+1}/{total_pages} 수집중", end="\r")
    url = "https://openapi.naver.com/v1/search/book.json"
    Client_Id = "sk2iKdMANqpvG3Pa2WIJ"
    Client_Secret = "by6xHZcrlB"
    headers = {"X-Naver-Client-Id" : Client_Id, "X-Naver-Client-Secret" : Client_Secret}
    payload = dict(query=keyword, display=100, start=start, sort="sim")
    r = requests.get(url, params=payload, headers=headers)
    print(r.url)
    print(r.status_code)
    data = r.json()
    n_data = data['total']
    total_pages = (int(data['total'])//100)+1
#     print("전체 검색 데이터 수: ", n_data, "검색할 페이지수: ", total_pages )
    result_df = json_unpack(data)
    all_data.append(result_df)
    if start == 1000:
        break
    elif start < 901:
        start += 100
    elif start == 901:
        start += 99

https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=101&sort=sim
200
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=201&sort=sim
200
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=301&sort=sim
200
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=401&sort=sim
200
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=501&sort=sim
200
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=601&sort=sim
200
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=701&sort=sim
200
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=801&sort=sim
200
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=901&sort=sim
200
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=1000&sort=sim
200

In [7]:
len(all_data)

11

In [9]:
import pandas as pd

In [10]:
final_result = pd.concat(all_data)
final_result = final_result.reset_index(drop=True)
final_result

,title,link,image,author,discount,publisher,pubdate,isbn,description
0,"혼자 만들면서 공부하는 파이썬 (37개 라이브러리와 API로 보고서, 차트, 게임,...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_528593...,문현일,23400,한빛미디어,20250214,9791169213271,“파이썬을 배워서 어디에 활용할 수 있을지 궁금했나요?”\n나의 신용카드 내역 분석...
1,혼자 공부하는 파이썬 (1:1 과외하듯 배우는 프로그래밍 자습서),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_325076...,윤인성,19800,한빛미디어,20220601,9791162245651,혼자 해도 충분하다! 1:1 과외하듯 배우는 파이썬 프로그래밍 자습서\n\n『혼자 ...
2,Do it! 점프 투 파이썬 (중학생도 첫날부터 실습하는 초고속 입문서),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_403540...,박응용,19800,이지스퍼블리싱,20230615,9791163034735,프로그래밍 분야 8년 연속 베스트셀러!\n《Do it! 점프 투 파이썬》 전면 개정...
3,밑바닥부터 시작하는 딥러닝 1(리마스터판) (파이썬으로 익히는 딥러닝 이론과 구현),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_526155...,사이토 고키,23400,한빛미디어,20250124,9791169213387,딥러닝 분야 부동의 베스트셀러!\n머리로 이해하고 손으로 익히는 가장 쉬운 딥러닝 ...
4,50개의 프로젝트로 완성하는 파이썬 업무 자동화 (프로젝트 따라하기로 업무 자동화 ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_537377...,오토코더,19800,위즈앤북(Wiznbook),20250317,9791198685353,ㆍ퀴즈와 QR 코드 생성부터 나만의 음성 비서 제작까지 다양한 프로젝트 대공개!\n...
...,...,...,...,...,...,...,...,...,...
1095,"챗GPT와 업무자동화 (1분 만에 끝내는 엑셀, 구글 시트, 파워포인트, 파이썬 자...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_386135...,김철수,16200,위키북스,20230321,9791158394288,"코드 한 줄 몰라도 1분 만에 끝내는 엑셀, 구글 스프레드시트, 파워포인트 업무 자..."
1096,프로그래밍 정석(개념을 잡아주는) (기초 연산부터 고급 문제해결 능력까지 파이썬을 ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324972...,제니퍼 캠벨^폴 그리스^제이슨 몬토조^그렉 윌슨,0,에이콘출판,20100504,9788960771338,"『개념을 잡아주는 프로그래밍 정석』은 기본적인 프로그래밍 요소부터 알고리즘, 디버깅..."
1097,머신러닝 딥러닝을 이용한 A.I. 자율주행 RC카 프로젝트 with 파이썬+아두이노...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324665...,서민우,0,앤써북,20220520,9791185553979,〈머신러닝 딥러닝을 이용한 A.I. 자율주행 RC카 프로젝트 with 파이썬+아두이...
1098,파이썬 딥러닝 파이토치(Python Deep Learning PyTorch),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324549...,이경택^방성수^안상준,14800,정보문화사,20201008,9788956748573,파이썬은 선택이 아닌 필수! 파이토치로 딥러닝 입문하기!\n\n이 책은 딥러닝 기술...
1099,Let’s Start Coding with Raptor & Python (랩터 & ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324972...,김충석,0,앤아이컴즈,20190815,9788993163568,▶ 이 책은 Python(파이썬)을 다룬 이론서입니다.

# While 문으로 데이터 모두 가져오기

In [11]:
import requests
import pandas as pd

In [12]:
keyword = input("검색 키워드를 입력해 주세요. ")

검색 키워드를 입력해 주세요. 핀테크

In [13]:
all_data2 = []
start = 1

while True:
    url = "https://openapi.naver.com/v1/search/book.json"
    Client_Id = "sk2iKdMANqpvG3Pa2WIJ"
    Client_Secret = "by6xHZcrlB"
    headers = {"X-Naver-Client-Id" : Client_Id, "X-Naver-Client-Secret" : Client_Secret}
    payload = dict(query=keyword, display=100, start=start, sort="sim")
    r = requests.get(url, params=payload, headers=headers)
    print(r.url)
    print(r.status_code)
    data = r.json()
    n_data = data['total']
    total_pages = (int(data['total'])//100)+1
    print("전체 검색 데이터 수: ", n_data, "검색할 페이지수: ", total_pages )
    result_df = json_unpack(data)
    all_data2.append(result_df)
    if start == 1000:
        break
    elif start < 901:
        start += 100
    elif start == 901:
        start += 99

https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지수:  2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=101&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지수:  2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=201&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지수:  2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=301&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지수:  2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=401&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지수:  2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=501&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지수:  2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=601&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지수:  2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=701&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지수:  2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=801&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지수:  2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=901&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지수:  2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지수:  2

In [14]:
len(all_data2)

11

In [15]:
final_result2 = pd.concat(all_data2)
final_result2 = final_result2.reset_index(drop=True)
final_result2

,title,link,image,author,discount,publisher,pubdate,isbn,description
0,핀테크,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324383...,한석주,11400,커뮤니케이션북스,20151101,9791130441436,디지털 기술의 발달은 금융의 모든 것을 바꾸고 있다. 기술 기반의 스타트업들과 비금...
1,핀테크 (IT와 금융이 만나는 새로운 세상),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_325064...,강창호,0,한빛미디어,20150605,9788968482007,금융과 기술로 혁신하는 핀테크 시장을 선점하라!\n\n상시 연결된 디지털 세상에서 ...
2,핀테크 4.0 (핀테크 혁명과 금융의 미래),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_520007...,김종현,17100,한국금융연수원,20241216,9788928782284,본서에서는 세계 최초로 핀테크 산업의 발전을 4단계로 구분하여 설명하는 [핀테크 4...
3,핀테크와 법 (제3판),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324417...,강현구^유주선^이성남,19800,씨아이알,20201112,9791156109020,핀테크의 영역과 그에 대한 법률문제의 간격을 \n어떻게 좁힐 수 있을 것인가\n\n...
4,핀테크 전쟁 (세계 금융 시장의 거대한 트렌드 | 새로운 돈의 시대가 온다),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324666...,브렛 킹,13500,예문,20150612,9788956592503,"다가오는 미래, 달라지는 금융의 패러다임을 한 권으로 읽는다!\n\n핀테크란 금융을..."
...,...,...,...,...,...,...,...,...,...
101,"신남방 지역 주요국의 핀테크 발전과 협력방안: 인도, 태국, 말레이시아, 베트남, ...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_332340...,이충열^이종하^이선호,9000,대외경제정책연구원,20201231,9788932290201,이 책은 대외경제정책연구원의 신남방 지역 주요국의 핀테크 발전과 협력방안을 다룬 정...
102,[CD] 2018 4차산업 기업.스타트업 주소록 - CD-ROM 1장 (가상현실·드...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324666...,한국콘텐츠미디어,170100,한국콘텐츠미디어,20180921,9791155055663,"2018 4차산업 기업·스타트업 주소록 CD에는 4차 산업기술, 바이오헬스케어, 창..."
103,"4차산업 기업·스타트업 주소록(2023)(CD) (IOT, VR, 가상현실, 블록체...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_400602...,한국콘텐츠미디어 편집부,215100,한국콘텐츠미디어,20230501,8809496290337,"4차산업 기업·스타트업 주소록을 분야별, 지역별로 18,460건, IT기업 상세정보..."
104,"4차산업 기업·스타트업 주소록(2024)(CD) (3D프린터, IOT, VR, 가상...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_466775...,한국콘텐츠미디어 편집부,215100,한국콘텐츠미디어,20240326,9791172340209,"4차산업 기업·스타트업 주소록을 분야별, 지역별로 19,908건, IT기업 상세정보..."
105,"전국 체험마을 주소록(2024)(CD) (3D프린터, IOT, VR, 가상현실, 드...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_466775...,한국콘텐츠미디어 편집부,215100,한국콘텐츠미디어,20240322,9791172340193,"전국 체험마을 주소록을 분야별, 지역별로 33,479건, 관광·여가산업 상세정보를 ..."

In [16]:
final_result2.to_csv("네이버검색_책_파이썬.csv", encoding="utf-8-sig", index=False)

# 뉴스, 블로그, 책 한번에 검색해서 저장하기

In [17]:
all_data3 = []

for category in ["blog", "news", "book"]:
    start = 1
    while True:
        url = f"https://openapi.naver.com/v1/search/{category}.json"
        Client_Id = "sk2iKdMANqpvG3Pa2WIJ"
        Client_Secret = "by6xHZcrlB"
        headers = {"X-Naver-Client-Id" : Client_Id, "X-Naver-Client-Secret" : Client_Secret}
        payload = dict(query=keyword, display=100, start=start, sort="sim")
        r = requests.get(url, params=payload, headers=headers)
        print(r.url)
        print(r.status_code)
        data = r.json()
        n_data = data['total']
        total_pages = (int(data['total'])//100)+1
        print("전체 검색 데이터 수: ", n_data, "검색할 페이지수: ", total_pages )
        result_df = json_unpack(data)
        all_data3.append(result_df)
        if start == 1000:
            break
        elif start < 901:
            start += 100
        elif start == 901:
            start += 99
final_result3 = pd.concat(all_data3)
final_result3 = final_result3.reset_index(drop=True)
final_result3

https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=sim
200
전체 검색 데이터 수:  456162 검색할 페이지수:  4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=101&sort=sim
200
전체 검색 데이터 수:  456162 검색할 페이지수:  4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=201&sort=sim
200
전체 검색 데이터 수:  456162 검색할 페이지수:  4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=301&sort=sim
200
전체 검색 데이터 수:  456162 검색할 페이지수:  4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=401&sort=sim
200
전체 검색 데이터 수:  456162 검색할 페이지수:  4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=501&sort=sim
200
전체 검색 데이터 수:  456162 검색할 페이지수:  4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=601&sort=sim
200
전체 검색 데이터 수:  456162 검색할 페이지수:  4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=701&sort=sim
200
전체 검색 데이터 수:  456162 검색할 페이지수:  4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=801&sort=sim
200
전체 검색 데이터 수:  456162 검색할 페이지수:  4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=901&sort=sim
200
전체 검색 데이터 수:  456162 검색할 페이지수:  4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200
전체 검색 데이터 수:  456162 검색할 페이지수:  4562
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=sim
200
전체 검색 데이터 수:  498086 검색할 페이지수:  4981
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=101&sort=sim
200
전체 검색 데이터 수:  498086 검색할 페이지수:  4981
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=201&sort=sim
200
전체 검색 데이터 수:  498086 검색할 페이지수:  4981
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=301&sort=sim
200
전체 검색 데이터 수:  498086 검색할 페이지수:  4981
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=401&sort=sim
200
전체 검색 데이터 수:  498086 검색할 페이지수:  4981
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=501&sort=sim
200
전체 검색 데이터 수:  498086 검색할 페이지수:  4981
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=601&sort=sim
200
전체 검색 데이터 수:  498086 검색할 페이지수:  4981
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=701&sort=sim
200
전체 검색 데이터 수:  498086 검색할 페이지수:  4981
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=801&sort=sim
200
전체 검색 데이터 수:  498086 검색할 페이지수:  4981
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=901&sort=sim
200
전체 검색 데이터 수:  498086 검색할 페이지수:  4981
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200
전체 검색 데이터 수:  498086 검색할 페이지수:  4981
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지수:  2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=101&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지수:  2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=201&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지수:  2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=301&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지수:  2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=401&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지수:  2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=501&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지수:  2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=601&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지수:  2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=701&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지수:  2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=801&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지수:  2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=901&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지수:  2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지수:  2

,title,link,description,bloggername,bloggerlink,postdate,originallink,pubDate,image,author,discount,publisher,pubdate,isbn
0,<b>핀테크</b> 투자 후기,https://blog.naver.com/kan1687/223812724931,"<b>핀테크</b> 투자, 아직도 망설이고 계신가요? 여러분 혹시 이런 고민 해보...",우정잉♥,blog.naver.com/kan1687,20250329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[<b>핀테크</b>] 2024년 <b>핀테크</b> 업계 결산: 놀라운 3가지 변화,https://blog.naver.com/xoom777/223708685044,동안 <b>핀테크</b> 업계에는 예상치 못한 변화의 바람이 불었습니다. 한동안 주...,Ich fange an,blog.naver.com/xoom777,20241229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[인사이트 캠퍼스] 2025 동계 <b>핀테크</b> 캠프 (with 전주대학교...,https://blog.naver.com/fininsight/223734638126,전주대학교 친구들이 직접 여의도까지 방문하여 <b>핀테크</b>(FinTech)의 ...,핀인사이트 (Fininsight),blog.naver.com/fininsight,20250122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[AI <b>핀테크</b>] AI와 빅데이터로 금융 시장을 재편하는 <b>핀테크</...,https://blog.naver.com/jangpung_/223765345858,이제 대출도 AI가 하는 시대 출처 : 파가야 테크놀러지스 홈페이지 금융과 기술이 ...,낭만을 꿈꾸는 일상,blog.naver.com/jangpung_,20250218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,IPAY <b>핀테크</b>관련주 ETF -미국 CBDC 코인 서비스 실험 확대,https://blog.naver.com/jaso_/223736810791,IPAY <b>핀테크</b>관련주 ETF -미국 CBDC 코인 서비스 실험 확대 I...,미국주식 퍼주마,blog.naver.com/jaso_,20250130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2301,"신남방 지역 주요국의 핀테크 발전과 협력방안: 인도, 태국, 말레이시아, 베트남, ...",https://search.shopping.naver.com/book/catalog...,이 책은 대외경제정책연구원의 신남방 지역 주요국의 핀테크 발전과 협력방안을 다룬 정...,NaN,NaN,NaN,NaN,NaN,https://shopping-phinf.pstatic.net/main_332340...,이충열^이종하^이선호,9000,대외경제정책연구원,20201231,9788932290201
2302,[CD] 2018 4차산업 기업.스타트업 주소록 - CD-ROM 1장 (가상현실·드...,https://search.shopping.naver.com/book/catalog...,"2018 4차산업 기업·스타트업 주소록 CD에는 4차 산업기술, 바이오헬스케어, 창...",NaN,NaN,NaN,NaN,NaN,https://shopping-phinf.pstatic.net/main_324666...,한국콘텐츠미디어,170100,한국콘텐츠미디어,20180921,9791155055663
2303,"4차산업 기업·스타트업 주소록(2023)(CD) (IOT, VR, 가상현실, 블록체...",https://search.shopping.naver.com/book/catalog...,"4차산업 기업·스타트업 주소록을 분야별, 지역별로 18,460건, IT기업 상세정보...",NaN,NaN,NaN,NaN,NaN,https://shopping-phinf.pstatic.net/main_400602...,한국콘텐츠미디어 편집부,215100,한국콘텐츠미디어,20230501,8809496290337
2304,"4차산업 기업·스타트업 주소록(2024)(CD) (3D프린터, IOT, VR, 가상...",https://search.shopping.naver.com/book/catalog...,"4차산업 기업·스타트업 주소록을 분야별, 지역별로 19,908건, IT기업 상세정보...",NaN,NaN,NaN,NaN,NaN,https://shopping-phinf.pstatic.net/main_466775...,한국콘텐츠미디어 편집부,215100,한국콘텐츠미디어,20240326,9791172340209
2305,"전국 체험마을 주소록(2024)(CD) (3D프린터, IOT, VR, 가상현실, 드...",https://search.shopping.naver.com/book/catalog...,"전국 체험마을 주소록을 분야별, 지역별로 33,479건, 관광·여가산업 상세정보를 ...",NaN,NaN,NaN,NaN,NaN,https://shopping-phinf.pstatic.net/main_466775...,한국콘텐츠미디어 편집부,215100,한국콘텐츠미디어,20240322,9791172340193

## 내가 한 것(수정하기)

In [8]:
payload=[]
i = 1
while i < 1000:
    i += 100
    if i == 1001:
        i -= 1
    payload.append({'query': book, 'display': 100, 'start':i , 'sort':'sim'})
payload

[{'query': '파이썬', 'display': 100, 'start': 101, 'sort': 'sim'},
 {'query': '파이썬', 'display': 100, 'start': 201, 'sort': 'sim'},
 {'query': '파이썬', 'display': 100, 'start': 301, 'sort': 'sim'},
 {'query': '파이썬', 'display': 100, 'start': 401, 'sort': 'sim'},
 {'query': '파이썬', 'display': 100, 'start': 501, 'sort': 'sim'},
 {'query': '파이썬', 'display': 100, 'start': 601, 'sort': 'sim'},
 {'query': '파이썬', 'display': 100, 'start': 701, 'sort': 'sim'},
 {'query': '파이썬', 'display': 100, 'start': 801, 'sort': 'sim'},
 {'query': '파이썬', 'display': 100, 'start': 901, 'sort': 'sim'},
 {'query': '파이썬', 'display': 100, 'start': 1000, 'sort': 'sim'}]

In [9]:
import requests
url = "https://openapi.naver.com/v1/search/book.json"
book = input("책 제목을 입력하세요")
payload = {'query': book, 'display': 100, 'start':1000 , 'sort':'sim'}
headers = {"X-Naver-Client-Id":"YYIYgjstxPdUpH7WXuUE", "X-Naver-Client-Secret":"wqrbMV9nRh"}
r = requests.get(url, params=payload, headers=headers)
print(r.url)
print(r.status_code)
data = r.json()
print("전체 검색 데이터 수 :", data["total"], "검색할 페이지수:", (int(data["total"])//100)+1)

책 제목을 입력하세요파이썬
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=1000&sort=sim
200
전체 검색 데이터 수 : 1113 검색할 페이지수: 12

In [10]:
result_df = json_unpack(data)
result_df

,title,link,image,author,discount,publisher,pubdate,isbn,description
0,파이썬과 케라스를 이용한 딥러닝/강화학습 주식투자 (퀀트 투자 알고리즘 트레이딩을 ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324920...,김문권,0,위키북스,20180529,9791158391065,강화학습은 스스로 학습하는 머신러닝 기법으로서 주식 데이터 학습에 잘 적용되는 기법...
1,슬기로운 코딩 생활 with 파이썬 으랏차차 기초편 (즐겁게 시작하고 똑똑하게 끝내...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324902...,김정욱,0,루비페이퍼,20180515,9791186710333,"수학, 과학, 국어, 사회 등 실제 초중등 교과 과목과 연계된 예제로 코딩력과 학습..."
2,2024 내일은 빅데이터분석기사 실기 with 파이썬 (제6회부터 변경된 작업형 제...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_434140...,Jade Jeong,20700,김앤북,20231030,9788965127925,「2024 내일은 빅데이터분석기사 실기」는 자격증을 준비하는 수험생 & 재직자(비전...
3,2024 빅데이터분석기사 실기 한권완성: 파이썬(Python) (작업형 제3유형 완...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_461080...,최예신^박진원^이경숙^김주현,27000,예문에듀,20240520,9791163862833,빅데이터분석기사 실기시험 초단기 합격을 위한 최고의 실전 대비서\n‘2024 빅데이...
4,Step by Step CRM을 위한 파이썬 머신러닝 (빅 데이터 분석 자격증 머신...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_394909...,김형수,30000,프레딕스,20230501,9791195511792,"본서는 파이썬을 전혀 모르는 사람도, 프로그래밍을 전혀 해보지 않은 사람도 단계적으..."
...,...,...,...,...,...,...,...,...,...
95,"챗GPT와 업무자동화 (1분 만에 끝내는 엑셀, 구글 시트, 파워포인트, 파이썬 자...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_386135...,김철수,16200,위키북스,20230321,9791158394288,"코드 한 줄 몰라도 1분 만에 끝내는 엑셀, 구글 스프레드시트, 파워포인트 업무 자..."
96,프로그래밍 정석(개념을 잡아주는) (기초 연산부터 고급 문제해결 능력까지 파이썬을 ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324972...,제니퍼 캠벨^폴 그리스^제이슨 몬토조^그렉 윌슨,0,에이콘출판,20100504,9788960771338,"『개념을 잡아주는 프로그래밍 정석』은 기본적인 프로그래밍 요소부터 알고리즘, 디버깅..."
97,머신러닝 딥러닝을 이용한 A.I. 자율주행 RC카 프로젝트 with 파이썬+아두이노...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324665...,서민우,0,앤써북,20220520,9791185553979,〈머신러닝 딥러닝을 이용한 A.I. 자율주행 RC카 프로젝트 with 파이썬+아두이...
98,파이썬 딥러닝 파이토치(Python Deep Learning PyTorch),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324549...,이경택^방성수^안상준,14800,정보문화사,20201008,9788956748573,파이썬은 선택이 아닌 필수! 파이토치로 딥러닝 입문하기!\n\n이 책은 딥러닝 기술...
99,Let’s Start Coding with Raptor & Python (랩터 & ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324972...,김충석,0,앤아이컴즈,20190815,9788993163568,▶ 이 책은 Python(파이썬)을 다룬 이론서입니다.

In [11]:

while True:
    if page <== tatal_page
    import requests
    url = "https://openapi.naver.com/v1/search/book.json"
    book = input("책 제목을 입력하세요")
    payload = {'query': book, 'display': 100, 'start':1000 , 'sort':'sim'}
    headers = {"X-Naver-Client-Id":"YYIYgjstxPdUpH7WXuUE", "X-Naver-Client-Secret":"wqrbMV9nRh"}
    r = requests.get(url, params=payload, headers=headers)
    print(r.url)
    print(r.status_code)
    data = r.json()
    print("전체 검색 데이터 수 :", data["total"], "검색할 페이지수:", (int(data["total"])//100)+1)

SyntaxError: invalid syntax (126672947.py, line 2)

for 문

In [13]:
all_data = []

In [15]:
start = 101
for page in range(total_pages):
    import requests
    url = "https://openapi.naver.com/v1/search/book.json"
    book = input("책 제목을 입력하세요")
    payload = {'query': book, 'display': 100, 'start':start , 'sort':'sim'}
    headers = {"X-Naver-Client-Id":"YYIYgjstxPdUpH7WXuUE", "X-Naver-Client-Secret":"wqrbMV9nRh"}
    r = requests.get(url, params=payload, headers=headers)
    print(r.url)
    print(r.status_code)
    data = r.json()
    n_data = data["total"]
    total_pages = (int(data["total"])//100)+1
    print("전체 검색 데이터 수 :", data["total"], "검색할 페이지수:", (int(data["total"])//100)+1)
    result_df = json_unpack(data)
    all_data.append(result_df)
    if start == 1000:
        break
    elif start < 901:
        start += 100
    elif start == 901:
        start += 99

NameError: name 'total_pages' is not defined

In [ ]:
payload=[]
i = 1
while i < 1000:
    i += 100
    if i == 1001:
        i -= 1
    payload.append({'query': book, 'display': 100, 'start':i , 'sort':'sim'})
payload

In [ ]:
import requests
url = "https://openapi.naver.com/v1/search/book.json"
result2=[]
book = input("책 제목을 입력하세요")
i = 1
while i < 1000:
    i += 100
    if i == 1001:
        i -= 1
    payload = {'query': book, 'display': 100, 'start':i, 'sort':'sim'}
    headers = {"X-Naver-Client-Id":"YYIYgjstxPdUpH7WXuUE", "X-Naver-Client-Secret":"wqrbMV9nRh"}
    r = requests.get(url, params=payload, headers=headers)
    data = r.json()

    result2.append(data)

In [ ]:
for i in result2:
    result2[i]['items']

# While문으로 데이터 모두 가져오기

In [ ]:
all_data2 = []
start = 1
while True:
    import requests
    url = "https://openapi.naver.com/v1/search/book.json"
    book = input("책 제목을 입력하세요")
    payload = {'query': book, 'display': 100, 'start':1000 , 'sort':'sim'}
    headers = {"X-Naver-Client-Id":"YYIYgjstxPdUpH7WXuUE", "X-Naver-Client-Secret":"wqrbMV9nRh"}
    r = requests.get(url, params=payload, headers=headers)
    print(r.url)
    print(r.status_code)
    data = r.json()
    n_data = data["total"]
    total_pages = (int(data["total"])//100)+1
    print("전체 검색 데이터 수 :", data["total"], "검색할 페이지수:", (int(data["total"])//100)+1)
    result_df = json_unpack(data)
    all_data2.append(result_df)
    if start == 1000:
        break
    if start < 901:
        start +=100
    elif start == 901:
        start + 99

책 제목을 입력하세요파이썬
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=1000&sort=sim
200
전체 검색 데이터 수 : 1113 검색할 페이지수: 12

# 뉴스, 블로그 책 한번에 검색해서 저장하기