# 하나은행에서 환율조회 부분 찾아서 selenium으로 열기
* 날짜 입력부분 찾아 날짜 넣기
* 조회 버튼 찾아 버튼 클릭하기
* 조회된 데이터를 pd.read_html을 이용해 datafrmae으로 만들기
* 날짜 프레임을 추가해서 데이터에 넣기

In [1]:
import pandas as pd

In [2]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

options = Options()
options.add_experimental_option("detach", True)
options.add_argument("start-maximized")
options.add_argument("Chrome/134.0.0.0")
options.add_argument("lang=ko_KR")

url = "https://www.kebhana.com/cms/rate/index.do?contentUrl=/cms/rate/wpfxd651_01i.do"
driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
    )
driver.get(url)

In [3]:
# 날짜 입력
date_input = driver.find_element(By.CSS_SELECTOR, "#tmpInqStrDt")
date_input.clear()
date_input.send_keys("20250408")
date_input.send_keys(Keys.ENTER)

# 조회버튼 클릭
search_button = driver.find_element(By.CSS_SELECTOR, "#HANA_CONTENTS_DIV > div.btnBoxCenter > a")
search_button.click()

In [13]:
driver.find_element(By.CSS_SELECTOR, ".tblBasic.leftNone").get_attribute("outerHTML")

'<table class="tblBasic leftNone" summary="통화,현찰,송금,외화수표파실때,매매기준율,환가료율,미화환산율,사실 때,파실 때,보낼 때,받을 때,환율,Spread,환율,Spread(으)로 이루어진 기간별 기준가격 고시회차에 대한 내용 테이블입니다.">\n\t<caption>기간별 기준가격 고시회차에 대한 내용</caption> \n\t<colgroup>\n\t\t<col style="width:*">\n\t\t<col style="width:8%">\n\t\t<col style="width:7%">\n\t\t<col style="width:8%">\n\t\t<col style="width:7%">\n\t\t<col style="width:8%">\n\t\t<col style="width:7%">\n\t\t<col style="width:8%">\n\t\t<col style="width:8%">\n\t\t<col style="width:8%">\n\t\t<col style="width:8%">\n<!-- \t\t<col style="width:8%" /> -->\n\t</colgroup>\n\t<thead>\n\t\t<tr>\n\t\t\t<th class="leftNone" scope="col" rowspan="3">통화</th>\n\t\t\t<th class="leftLine" scope="col" colspan="4">현찰</th>\n\t\t\t<th class="leftLine" scope="col" colspan="2">송금</th>\n\t\t\n\t\t\t<th class="leftLine" scope="col" rowspan="3">외화<br>수표<br>파실때</th>\n\t\t\t<th class="leftLine" scope="col" rowspan="3">매매<br>기준율</th>\n\t\t\t<th class="leftLine" scope="col" rowspan="3">환가<br>료율</th>\n\t\t\t<th class="leftLine" scope="col" rowspan="3">미화<br>환산율</th>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<th class="leftLine" scope="col" colspan="2">사실 때</th>\n\t\t\t<th class="leftLine" scope="col" colspan="2">파실 때</th>\n\t\t\t<th class="leftLine" scope="col" rowspan="2">보낼 때</th>\n\t\t\t<th class="leftLine" scope="col" rowspan="2">받을 때</th>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<th class="leftLine" scope="col">환율</th>\n\t\t\t<th class="leftLine" scope="col">Spread</th>\n\t\t\t<th class="leftLine" scope="col">환율</th>\n\t\t\t<th class="leftLine" scope="col">Spread</th>\n\t\t</tr>\n\t\t</thead>\n\t\t<tbody>\n\t\t\t\t\n\t\t\t\t\n\t\t\t\t<tr>\n\t\t\t\t\t<td class="tc">\n\t\t\t\t\t\t<a href="#//HanaBank" title="미국 USD 일일변동내역 보기" onclick="pbk.foreign.rate.pbld.prs.goFluctuation(\'USD\',\'20250408\');">\n\t\t\t\t\t\t\t<u>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t미국 USD\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t</u>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</td>\n\t\t\t\t\t<td class="txtAr">1,512.51</td>\n\t\t\t\t\t<td class="txtAr">1.75</td>\n\t\t\t\t\t<td class="txtAr">1,460.49</td>\n\t\t\t\t\t<td class="txtAr">1.75</td>\n\t\t\t\t\t<td class="txtAr">1,501.00</td>\n\t\t\t\t\t<td class="txtAr">1,472.00</td>\n\t\t\t\t\t\n\t\t\t\t\t<td class="txtAr">1,469.47</td>\n\t\t\t\t\t<td class="txtAr">1,486.50</td>\n\t\t\t\t\t<td class="txtAr">6.15079</td>\n\t\t\t\t\t<td class="txtAr">1.0000</td>\n\t\t\t\t\t\n\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t<tr>\n\t\t\t\t\t<td class="tc">\n\t\t\t\t\t\t<a href="#//HanaBank" title="일본 JPY (100) 일일변동내역 보기" onclick="pbk.foreign.rate.pbld.prs.goFluctuation(\'JPY\',\'20250408\');">\n\t\t\t\t\t\t\t<u>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t일본 JPY (100)\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t</u>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</td>\n\t\t\t\t\t<td class="txtAr">1,036.35</td>\n\t\t\t\t\t<td class="txtAr">1.75</td>\n\t\t\t\t\t<td class="txtAr">1,000.71</td>\n\t\t\t\t\t<td class="txtAr">1.75</td>\n\t\t\t\t\t<td class="txtAr">1,028.51</td>\n\t\t\t\t\t<td class="txtAr">1,008.55</td>\n\t\t\t\t\t\n\t\t\t\t\t<td class="txtAr">1,007.90</td>\n\t\t\t\t\t<td class="txtAr">1,018.53</td>\n\t\t\t\t\t<td class="txtAr">2.60318</td>\n\t\t\t\t\t<td class="txtAr">0.6852</td>\n\t\t\t\t\t\n\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t<tr>\n\t\t\t\t\t<td class="tc">\n\t\t\t\t\t\t<a href="#//HanaBank" title="유로 EUR 일일변동내역 보기" onclick="pbk.foreign.rate.pbld.prs.goFluctuation(\'EUR\',\'20250408\');">\n\t\t\t\t\t\t\t<u>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t유로 EUR\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t</u>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</td>\n\t\t\t\t\t<td class="txtAr">1,663.21</td>\n\t\t\t\t\t<td class="txtAr">1.99</td>\n\t\t\t\t\t<td class="txtAr">1,598.31</td>\n\t\t\t\t\t<td class="txtAr">1.99</td>\n\t\t\t\t\t<td class="txtAr">1,647.06</td>\n\t\t\t\t\t<td class="txtAr">1,614.46</td>\n\t\t\t\t\t\n\t\t\t\t\t<td class="txtAr">1,612.51</td>\n\t\t\t\t\t<td class="txtAr">1,630.76</td>\n\t\t\t\t\t<td class="txtAr">4.31600</td>\n\t\t\t\t\t<td class="txtAr">1.0970</td>\n\t\t\t\t\t\n\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t<tr>\n\t\t\t\t\t<td class="tc">\n\t\t\t\t\t\t<a href="#//HanaBank" title="중국 CNY 일일변동내역 보기" onclick="pbk.foreign.rate.pbld.prs.goFluctuation(\'CNY\',\'20250408\');">\n\t\t\t\t\t\t\t<u>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t중국 CNY\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t</u>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</td>\n\t\t\t\t\t<td class="txtAr">210.70</td>\n\t\t\t\t\t<td class="txtAr">5.00</td>\n\t\t\t\t\t<td class="txtAr">190.64</td>\n\t\t\t\t\t<td class="txtAr">5.00</td>\n\t\t\t\t\t<td class="txtAr">202.67</td>\n\t\t\t\t\t<td class="txtAr">198.67</td>\n\t\t\t\t\t\n\t\t\t\t\t<td class="txtAr">0.00</td>\n\t\t\t\t\t<td class="txtAr">200.67</td>\n\t\t\t\t\t<td class="txtAr">4.43712</td>\n\t\t\t\t\t<td class="txtAr">0.1350</td>\n\t\t\t\t\t\n\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t<tr>\n\t\t\t\t\t<td class="tc">\n\t\t\t\t\t\t<a href="#//HanaBank" title="홍콩 HKD 일일변동내역 보기" onclick="pbk.foreign.rate.pbld.prs.goFluctuation(\'HKD\',\'20250408\');">\n\t\t\t\t\t\t\t<u>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t홍콩 HKD\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t</u>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</td>\n\t\t\t\t\t<td class="txtAr">195.05</td>\n\t\t\t\t\t<td class="txtAr">1.97</td>\n\t\t\t\t\t<td class="txtAr">187.53</td>\n\t\t\t\t\t<td class="txtAr">1.97</td>\n\t\t\t\t\t<td class="txtAr">193.20</td>\n\t\t\t\t\t<td class="txtAr">189.38</td>\n\t\t\t\t\t\n\t\t\t\t\t<td class="txtAr">189.11</td>\n\t\t\t\t\t<td class="txtAr">191.29</td>\n\t\t\t\t\t<td class="txtAr">5.74800</td>\n\t\t\t\t\t<td class="txtAr">0.1287</td>\n\t\t\t\t\t\n\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t<tr>\n\t\t\t\t\t<td class="tc">\n\t\t\t\t\t\t<a href="#//HanaBank" title="태국 THB 일일변동내역 보기" onclick="pbk.foreign.rate.pbld.prs.goFluctuation(\'THB\',\'20250408\');">\n\t\t\t\t\t\t\t<u>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t태국 THB\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t</u>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</td>\n\t\t\t\t\t<td class="txtAr">44.71</td>\n\t\t\t\t\t<td class="txtAr">5.00</td>\n\t\t\t\t\t<td class="txtAr">40.04</td>\n\t\t\t\t\t<td class="txtAr">6.00</td>\n\t\t\t\t\t<td class="txtAr">43.01</td>\n\t\t\t\t\t<td class="txtAr">42.17</td>\n\t\t\t\t\t\n\t\t\t\t\t<td class="txtAr">42.13</td>\n\t\t\t\t\t<td class="txtAr">42.59</td>\n\t\t\t\t\t<td class="txtAr">4.03366</td>\n\t\t\t\t\t<td class="txtAr">0.0287</td>\n\t\t\t\t\t\n\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t<tr>\n\t\t\t\t\t<td class="tc">\n\t\t\t\t\t\t<a href="#//HanaBank" title="대만 TWD 일일변동내역 보기" onclick="pbk.foreign.rate.pbld.prs.goFluctuation(\'TWD\',\'20250408\');">\n\t\t\t\t\t\t\t<u>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t대만 TWD\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t</u>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</td>\n\t\t\t\t\t<td class="txtAr">50.73</td>\n\t\t\t\t\t<td class="txtAr">13.10</td>\n\t\t\t\t\t<td class="txtAr">40.38</td>\n\t\t\t\t\t<td class="txtAr">10.00</td>\n\t\t\t\t\t<td class="txtAr">0.00</td>\n\t\t\t\t\t<td class="txtAr">0.00</td>\n\t\t\t\t\t\n\t\t\t\t\t<td class="txtAr">0.00</td>\n\t\t\t\t\t<td class="txtAr">44.86</td>\n\t\t\t\t\t<td class="txtAr">3.58766</td>\n\t\t\t\t\t<td class="txtAr">0.0302</td>\n\t\t\t\t\t\n\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t<tr>\n\t\t\t\t\t<td class="tc">\n\t\t\t\t\t\t<a href="#//HanaBank" title="필리핀 PHP 일일변동내역 보기" onclick="pbk.foreign.rate.pbld.prs.goFluctuation(\'PHP\',\'20250408\');">\n\t\t\t\t\t\t\t<u>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t필리핀 PHP\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t</u>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</td>\n\t\t\t\t\t<td class="txtAr">28.41</td>\n\t\t\t\t\t<td class="txtAr">10.00</td>\n\t\t\t\t\t<td class="txtAr">23.72</td>\n\t\t\t\t\t<td class="txtAr">8.20</td>\n\t\t\t\t\t<td class="txtAr">26.08</td>\n\t\t\t\t\t<td class="txtAr">25.58</td>\n\t\t\t\t\t\n\t\t\t\t\t<td class="txtAr">0.00</td>\n\t\t\t\t\t<td class="txtAr">25.83</td>\n\t\t\t\t\t<td class="txtAr">7.52400</td>\n\t\t\t\t\t<td class="txtAr">0.0174</td>\n\t\t\t\t\t\n\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t<tr>\n\t\t\t\t\t<td class="tc">\n\t\t\t\t\t\t<a href="#//HanaBank" title="싱가포르 SGD 일일변동내역 보기" onclick="pbk.foreign.rate.pbld.prs.goFluctuation(\'SGD\',\'20250408\');">\n\t\t\t\t\t\t\t<u>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t싱가포르 SGD\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t</u>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</td>\n\t\t\t\t\t<td class="txtAr">1,120.61</td>\n\t\t\t\t\t<td class="txtAr">1.99</td>\n\t\t\t\t\t<td class="txtAr">1,076.89</td>\n\t\t\t\t\t<td class="txtAr">1.99</td>\n\t\t\t\t\t<td class="txtAr">1,109.73</td>\n\t\t\t\t\t<td class="txtAr">1,087.77</td>\n\t\t\t\t\t\n\t\t\t\t\t<td class="txtAr">1,086.49</td>\n\t\t\t\t\t<td class="txtAr">1,098.75</td>\n\t\t\t\t\t<td class="txtAr">4.76033</td>\n\t\t\t\t\t<td class="txtAr">0.7392</td>\n\t\t\t\t\t\n\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t<tr>\n\t\t\t\t\t<td class="tc">\n\t\t\t\t\t\t<a href="#//HanaBank" title="호주 AUD 일일변동내역 보기" onclick="pbk.foreign.rate.pbld.prs.goFluctuation(\'AUD\',\'20250408\');">\n\t\t\t\t\t\t\t<u>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t호주 AUD\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t</u>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</td>\n\t\t\t\t\t<td class="txtAr">902.57</td>\n\t\t\t\t\t<td class="txtAr">1.97</td>\n\t\t\t\t\t<td class="txtAr">867.71</td>\n\t\t\t\t\t<td class="txtAr">1.97</td>\n\t\t\t\t\t<td class="txtAr">893.99</td>\n\t\t\t\t\t<td class="txtAr">876.29</td>\n\t\t\t\t\t\n\t\t\t\t\t<td class="txtAr">874.79</td>\n\t\t\t\t\t<td class="txtAr">885.14</td>\n\t\t\t\t\t<td class="txtAr">6.22766</td>\n\t\t\t\t\t<td class="txtAr">0.5955</td>\n\t\t\t\t\t\n\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t<tr>\n\t\t\t\t\t<td class="tc">\n\t\t\t\t\t\t<a href="#//HanaBank" title="베트남 VND (100) 일일변동내역 보기" onclick="pbk.foreign.rate.pbld.prs.goFluctuation(\'VND\',\'20250408\');">\n\t\t\t\t\t\t\t<u>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t베트남 VND (100)\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t</u>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</td>\n\t\t\t\t\t<td class="txtAr">6.40</td>\n\t\t\t\t\t<td class="txtAr">11.80</td>\n\t\t\t\t\t<td class="txtAr">5.06</td>\n\t\t\t\t\t<td class="txtAr">11.80</td>\n\t\t\t\t\t<td class="txtAr">5.78</td>\n\t\t\t\t\t<td class="txtAr">5.68</td>\n\t\t\t\t\t\n\t\t\t\t\t<td class="txtAr">0.00</td>\n\t\t\t\t\t<td class="txtAr">5.73</td>\n\t\t\t\t\t<td class="txtAr">6.61166</td>\n\t\t\t\t\t<td class="txtAr">0.0039</td>\n\t\t\t\t\t\n\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t<tr>\n\t\t\t\t\t<td class="tc">\n\t\t\t\t\t\t<a href="#//HanaBank" title="영국 GBP 일일변동내역 보기" onclick="pbk.foreign.rate.pbld.prs.goFluctuation(\'GBP\',\'20250408\');">\n\t\t\t\t\t\t\t<u>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t영국 GBP\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t</u>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</td>\n\t\t\t\t\t<td class="txtAr">1,937.55</td>\n\t\t\t\t\t<td class="txtAr">1.97</td>\n\t\t\t\t\t<td class="txtAr">1,862.69</td>\n\t\t\t\t\t<td class="txtAr">1.97</td>\n\t\t\t\t\t<td class="txtAr">1,919.12</td>\n\t\t\t\t\t<td class="txtAr">1,881.12</td>\n\t\t\t\t\t\n\t\t\t\t\t<td class="txtAr">1,877.72</td>\n\t\t\t\t\t<td class="txtAr">1,900.12</td>\n\t\t\t\t\t<td class="txtAr">6.53300</td>\n\t\t\t\t\t<td class="txtAr">1.2783</td>\n\t\t\t\t\t\n\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t<tr>\n\t\t\t\t\t<td class="tc">\n\t\t\t\t\t\t<a href="#//HanaBank" title="캐나다 CAD 일일변동내역 보기" onclick="pbk.foreign.rate.pbld.prs.goFluctuation(\'CAD\',\'20250408\');">\n\t\t\t\t\t\t\t<u>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t캐나다 CAD\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t</u>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</td>\n\t\t\t\t\t<td class="txtAr">1,063.19</td>\n\t\t\t\t\t<td class="txtAr">1.97</td>\n\t\t\t\t\t<td class="txtAr">1,022.11</td>\n\t\t\t\t\t<td class="txtAr">1.97</td>\n\t\t\t\t\t<td class="txtAr">1,053.07</td>\n\t\t\t\t\t<td class="txtAr">1,032.23</td>\n\t\t\t\t\t\n\t\t\t\t\t<td class="txtAr">1,030.85</td>\n\t\t\t\t\t<td class="txtAr">1,042.65</td>\n\t\t\t\t\t<td class="txtAr">4.76900</td>\n\t\t\t\t\t<td class="txtAr">0.7014</td>\n\t\t\t\t\t\n\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t<tr>\n\t\t\t\t\t<td class="tc">\n\t\t\t\t\t\t<a href="#//HanaBank" title="말레이시아 MYR 일일변동내역 보기" onclick="pbk.foreign.rate.pbld.prs.goFluctuation(\'MYR\',\'20250408\');">\n\t\t\t\t\t\t\t<u>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t말레이시아 MYR\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t</u>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</td>\n\t\t\t\t\t<td class="txtAr">355.49</td>\n\t\t\t\t\t<td class="txtAr">7.40</td>\n\t\t\t\t\t<td class="txtAr">306.51</td>\n\t\t\t\t\t<td class="txtAr">7.40</td>\n\t\t\t\t\t<td class="txtAr">0.00</td>\n\t\t\t\t\t<td class="txtAr">327.69</td>\n\t\t\t\t\t\n\t\t\t\t\t<td class="txtAr">0.00</td>\n\t\t\t\t\t<td class="txtAr">331.00</td>\n\t\t\t\t\t<td class="txtAr">5.26066</td>\n\t\t\t\t\t<td class="txtAr">0.2227</td>\n\t\t\t\t\t\n\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t<tr>\n\t\t\t\t\t<td class="tc">\n\t\t\t\t\t\t<a href="#//HanaBank" title="러시아 RUB 일일변동내역 보기" onclick="pbk.foreign.rate.pbld.prs.goFluctuation(\'RUB\',\'20250408\');">\n\t\t\t\t\t\t\t<u>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t러시아 RUB\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t</u>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</td>\n\t\t\t\t\t<td class="txtAr">18.96</td>\n\t\t\t\t\t<td class="txtAr">9.50</td>\n\t\t\t\t\t<td class="txtAr">14.29</td>\n\t\t\t\t\t<td class="txtAr">17.50</td>\n\t\t\t\t\t<td class="txtAr">17.92</td>\n\t\t\t\t\t<td class="txtAr">16.72</td>\n\t\t\t\t\t\n\t\t\t\t\t<td class="txtAr">0.00</td>\n\t\t\t\t\t<td class="txtAr">17.32</td>\n\t\t\t\t\t<td class="txtAr">2.97500</td>\n\t\t\t\t\t<td class="txtAr">0.0117</td>\n\t\t\t\t\t\n\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t<tr>\n\t\t\t\t\t<td class="tc">\n\t\t\t\t\t\t<a href="#//HanaBank" title="남아공화국 ZAR 일일변동내역 보기" onclick="pbk.foreign.rate.pbld.prs.goFluctuation(\'ZAR\',\'20250408\');">\n\t\t\t\t\t\t\t<u>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t남아공화국 ZAR\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t</u>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</td>\n\t\t\t\t\t<td class="txtAr">81.31</td>\n\t\t\t\t\t<td class="txtAr">8.00</td>\n\t\t\t\t\t<td class="txtAr">69.27</td>\n\t\t\t\t\t<td class="txtAr">8.00</td>\n\t\t\t\t\t<td class="txtAr">76.19</td>\n\t\t\t\t\t<td class="txtAr">74.39</td>\n\t\t\t\t\t\n\t\t\t\t\t<td class="txtAr">0.00</td>\n\t\t\t\t\t<td class="txtAr">75.29</td>\n\t\t\t\t\t<td class="txtAr">9.61100</td>\n\t\t\t\t\t<td class="txtAr">0.0506</td>\n\t\t\t\t\t\n\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t<tr>\n\t\t\t\t\t<td class="tc">\n\t\t\t\t\t\t<a href="#//HanaBank" title="노르웨이 NOK 일일변동내역 보기" onclick="pbk.foreign.rate.pbld.prs.goFluctuation(\'NOK\',\'20250408\');">\n\t\t\t\t\t\t\t<u>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t노르웨이 NOK\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t</u>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</td>\n\t\t\t\t\t<td class="txtAr">140.30</td>\n\t\t\t\t\t<td class="txtAr">3.30</td>\n\t\t\t\t\t<td class="txtAr">128.08</td>\n\t\t\t\t\t<td class="txtAr">5.70</td>\n\t\t\t\t\t<td class="txtAr">137.17</td>\n\t\t\t\t\t<td class="txtAr">134.47</td>\n\t\t\t\t\t\n\t\t\t\t\t<td class="txtAr">134.23</td>\n\t\t\t\t\t<td class="txtAr">135.82</td>\n\t\t\t\t\t<td class="txtAr">6.44133</td>\n\t\t\t\t\t<td class="txtAr">0.0914</td>\n\t\t\t\t\t\n\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t<tr>\n\t\t\t\t\t<td class="tc">\n\t\t\t\t\t\t<a href="#//HanaBank" title="뉴질랜드 NZD 일일변동내역 보기" onclick="pbk.foreign.rate.pbld.prs.goFluctuation(\'NZD\',\'20250408\');">\n\t\t\t\t\t\t\t<u>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t뉴질랜드 NZD\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t</u>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</td>\n\t\t\t\t\t<td class="txtAr">837.62</td>\n\t\t\t\t\t<td class="txtAr">1.97</td>\n\t\t\t\t\t<td class="txtAr">805.26</td>\n\t\t\t\t\t<td class="txtAr">1.97</td>\n\t\t\t\t\t<td class="txtAr">829.65</td>\n\t\t\t\t\t<td class="txtAr">813.23</td>\n\t\t\t\t\t\n\t\t\t\t\t<td class="txtAr">811.95</td>\n\t\t\t\t\t<td class="txtAr">821.44</td>\n\t\t\t\t\t<td class="txtAr">5.71166</td>\n\t\t\t\t\t<td class="txtAr">0.5526</td>\n\t\t\t\t\t\n\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t<tr>\n\t\t\t\t\t<td class="tc">\n\t\t\t\t\t\t<a href="#//HanaBank" title="덴마크 DKK 일일변동내역 보기" onclick="pbk.foreign.rate.pbld.prs.goFluctuation(\'DKK\',\'20250408\');">\n\t\t\t\t\t\t\t<u>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t덴마크 DKK\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t</u>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</td>\n\t\t\t\t\t<td class="txtAr">225.62</td>\n\t\t\t\t\t<td class="txtAr">3.30</td>\n\t\t\t\t\t<td class="txtAr">205.98</td>\n\t\t\t\t\t<td class="txtAr">5.70</td>\n\t\t\t\t\t<td class="txtAr">220.60</td>\n\t\t\t\t\t<td class="txtAr">216.24</td>\n\t\t\t\t\t\n\t\t\t\t\t<td class="txtAr">215.97</td>\n\t\t\t\t\t<td class="txtAr">218.42</td>\n\t\t\t\t\t<td class="txtAr">4.60800</td>\n\t\t\t\t\t<td class="txtAr">0.1469</td>\n\t\t\t\t\t\n\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t<tr>\n\t\t\t\t\t<td class="tc">\n\t\t\t\t\t\t<a href="#//HanaBank" title="멕시코 MXN 일일변동내역 보기" onclick="pbk.foreign.rate.pbld.prs.goFluctuation(\'MXN\',\'20250408\');">\n\t\t\t\t\t\t\t<u>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t멕시코 MXN\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t</u>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</td>\n\t\t\t\t\t<td class="txtAr">78.78</td>\n\t\t\t\t\t<td class="txtAr">10.50</td>\n\t\t\t\t\t<td class="txtAr">63.82</td>\n\t\t\t\t\t<td class="txtAr">10.50</td>\n\t\t\t\t\t<td class="txtAr">72.01</td>\n\t\t\t\t\t<td class="txtAr">70.59</td>\n\t\t\t\t\t\n\t\t\t\t\t<td class="txtAr">0.00</td>\n\t\t\t\t\t<td class="txtAr">71.30</td>\n\t\t\t\t\t<td class="txtAr">11.68300</td>\n\t\t\t\t\t<td class="txtAr">0.0480</td>\n\t\t\t\t\t\n\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t<tr>\n\t\t\t\t\t<td class="tc">\n\t\t\t\t\t\t<a href="#//HanaBank" title="몽골 MNT 일일변동내역 보기" onclick="pbk.foreign.rate.pbld.prs.goFluctuation(\'MNT\',\'20250408\');">\n\t\t\t\t\t\t\t<u>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t몽골 MNT\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t</u>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</td>\n\t\t\t\t\t<td class="txtAr">0.00</td>\n\t\t\t\t\t<td class="txtAr">0.00</td>\n\t\t\t\t\t<td class="txtAr">0.00</td>\n\t\t\t\t\t<td class="txtAr">0.00</td>\n\t\t\t\t\t<td class="txtAr">0.00</td>\n\t\t\t\t\t<td class="txtAr">0.00</td>\n\t\t\t\t\t\n\t\t\t\t\t<td class="txtAr">0.00</td>\n\t\t\t\t\t<td class="txtAr">0.42</td>\n\t\t\t\t\t<td class="txtAr">13.47500</td>\n\t\t\t\t\t<td class="txtAr">0.0003</td>\n\t\t\t\t\t\n\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t<tr>\n\t\t\t\t\t<td class="tc">\n\t\t\t\t\t\t<a href="#//HanaBank" title="바레인 BHD 일일변동내역 보기" onclick="pbk.foreign.rate.pbld.prs.goFluctuation(\'BHD\',\'20250408\');">\n\t\t\t\t\t\t\t<u>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t바레인 BHD\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t</u>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</td>\n\t\t\t\t\t<td class="txtAr">4,195.87</td>\n\t\t\t\t\t<td class="txtAr">6.40</td>\n\t\t\t\t\t<td class="txtAr">3,628.02</td>\n\t\t\t\t\t<td class="txtAr">8.00</td>\n\t\t\t\t\t<td class="txtAr">3,982.92</td>\n\t\t\t\t\t<td class="txtAr">3,904.06</td>\n\t\t\t\t\t\n\t\t\t\t\t<td class="txtAr">3,895.56</td>\n\t\t\t\t\t<td class="txtAr">3,943.49</td>\n\t\t\t\t\t<td class="txtAr">7.76900</td>\n\t\t\t\t\t<td class="txtAr">2.6529</td>\n\t\t\t\t\t\n\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t<tr>\n\t\t\t\t\t<td class="tc">\n\t\t\t\t\t\t<a href="#//HanaBank" title="방글라데시 BDT 일일변동내역 보기" onclick="pbk.foreign.rate.pbld.prs.goFluctuation(\'BDT\',\'20250408\');">\n\t\t\t\t\t\t\t<u>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t방글라데시 BDT\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t</u>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</td>\n\t\t\t\t\t<td class="txtAr">0.00</td>\n\t\t\t\t\t<td class="txtAr">0.00</td>\n\t\t\t\t\t<td class="txtAr">0.00</td>\n\t\t\t\t\t<td class="txtAr">0.00</td>\n\t\t\t\t\t<td class="txtAr">0.00</td>\n\t\t\t\t\t<td class="txtAr">0.00</td>\n\t\t\t\t\t\n\t\t\t\t\t<td class="txtAr">0.00</td>\n\t\t\t\t\t<td class="txtAr">12.23</td>\n\t\t\t\t\t<td class="txtAr">12.17370</td>\n\t\t\t\t\t<td class="txtAr">0.0082</td>\n\t\t\t\t\t\n\t\t\t\t</tr>\n\t\t\t\t\n\t\t\t\t<tr>\n\t\t\t\t\t<td class="tc">\n\t\t\t\t\t\t<a href="#//HanaBank" title="브라질 BRL 일일변동내역 보기" onclick="pbk.foreign.rate.pbld.prs.goFluctuation(\'BRL\',\'20250408\');">\n\t\t\t\t\t\t\t<u>\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t브라질 BRL\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t</u>\n\t\t\t\t\t\t</a>\n\t\t\t\t\t</td>\n\t\t\t\t\t<td class="txtAr">272.32</td>\n\t\t\t\t\t<td class="txtAr">10.20</td>\n\t\t\t\t\t<td class="txtAr">222.41</td>\n\t\t\t\t\t<td class="txtAr">10.00</td>\n\t\t\t\t

In [4]:
from io import StringIO

In [5]:
df = pd.read_html(StringIO(driver.find_element(By.CSS_SELECTOR, ".tblBasic.leftNone").get_attribute("outerHTML")))[0]
df

                 통화       현찰                              송금           \
                 통화     사실 때            파실 때            보낼 때     받을 때
                 통화       환율 Spread       환율 Spread     보낼 때     받을 때
0            미국 USD  1512.51   1.75  1460.49   1.75  1501.00  1472.00
1      일본 JPY (100)  1036.35   1.75  1000.71   1.75  1028.51  1008.55
2            유로 EUR  1663.21   1.99  1598.31   1.99  1647.06  1614.46
3            중국 CNY   210.70   5.00   190.64   5.00   202.67   198.67
4            홍콩 HKD   195.05   1.97   187.53   1.97   193.20   189.38
5            태국 THB    44.71   5.00    40.04   6.00    43.01    42.17
6            대만 TWD    50.73  13.10    40.38  10.00     0.00     0.00
7           필리핀 PHP    28.41  10.00    23.72   8.20    26.08    25.58
8          싱가포르 SGD  1120.61   1.99  1076.89   1.99  1109.73  1087.77
9            호주 AUD   902.57   1.97   867.71   1.97   893.99   876.29
10    베트남 VND (100)     6.40  11.80     5.06  11.80     5.78     5.68
11           영국 GBP  1937.55   1.97  1862.69   1.97  1919.12  1881.12
12          캐나다 CAD  1063.19   1.97  1022.11   1.97  1053.07  1032.23
13        말레이시아 MYR   355.49   7.40   306.51   7.40     0.00   327.69
14          러시아 RUB    18.96   9.50    14.29  17.50    17.92    16.72
15        남아공화국 ZAR    81.31   8.00    69.27   8.00    76.19    74.39
16         노르웨이 NOK   140.30   3.30   128.08   5.70   137.17   134.47
17         뉴질랜드 NZD   837.62   1.97   805.26   1.97   829.65   813.23
18          덴마크 DKK   225.62   3.30   205.98   5.70   220.60   216.24
19          멕시코 MXN    78.78  10.50    63.82  10.50    72.01    70.59
20           몽골 MNT     0.00   0.00     0.00   0.00     0.00     0.00
21          바레인 BHD  4195.87   6.40  3628.02   8.00  3982.92  3904.06
22        방글라데시 BDT     0.00   0.00     0.00   0.00     0.00     0.00
23          브라질 BRL   272.32  10.20   222.41  10.00     0.00   244.16
24         브루나이 BND  1142.70   4.00  1032.83   6.00     0.00     0.00
25      사우디아라비아 SAR   420.93   6.30   368.67   6.90   399.94   392.04
26         스리랑카 LKR     0.00   0.00     0.00   0.00     0.00     0.00
27          스웨덴 SEK   153.51   3.30   140.14   5.70   150.09   147.13
28          스위스 CHF  1791.60   1.97  1722.38   1.97  1774.55  1739.43
29    아랍에미리트공화국 AED   426.95   5.50   376.78   6.90   408.74   400.66
30          알제리 DZD     0.00   0.00     0.00   0.00     0.00     0.00
31           오만 OMR  4131.41   7.00  3590.87   7.00     0.00     0.00
32          요르단 JOD  2283.20   8.90  1928.89   8.00     0.00     0.00
33         이스라엘 ILS   432.63  10.00   361.84   8.00     0.00     0.00
34          이집트 EGP     0.00   0.00     0.00   0.00     0.00     0.00
35           인도 INR     0.00   0.00     0.00   0.00    17.42    17.04
36  인도네시아 IDR (100)     9.71  10.00     7.95  10.00     8.91     8.75
37           체코 CZK    70.18   8.50    58.87   9.00    65.40    63.98
38           칠레 CLP     1.63  10.00     1.35  10.00     0.00     0.00
39        카자흐스탄 KZT     0.00   0.00     0.00   0.00     0.00     0.00
40          카타르 QAR     0.00   0.00     0.00   0.00     0.00     0.00
41           케냐 KES     0.00   0.00     0.00   0.00     0.00     0.00
42         콜롬비아 COP     0.00   0.00     0.00   0.00     0.00     0.00
43         쿠웨이트 KWD  5138.00   6.50  4438.47   8.00  4872.66  4776.18
44         탄자니아 TZS     0.00   0.00     0.00   0.00     0.00     0.00
45         튀르키예 TRY     0.00   0.00     0.00   0.00    39.63    38.77
46         파키스탄 PKR     0.00   0.00     0.00   0.00     0.00     0.00
47          폴란드 PLN   412.32   8.00   351.24   8.00   385.97   377.59
48          헝가리 HUF     4.37   9.30     3.68   8.00     4.04     3.96
49           네팔 NPR     0.00   0.00     0.00   0.00     0.00     0.00
50          마카오 MOP     0.00   0.00     0.00   0.00     0.00     0.00
51         캄보디아 KHR     0.00   0.00     0.00   0.00     0.00     0.00
52           피지 FJD     0.00   0.00     0.00   0.00     0.00     0.00
53          리비아 LYD     0.00   0.00     0.00   0.00   269.96   264.62
54         루마니아 RON     0.00   0.00     0.00   0.00   331.26   324.06
55          미얀마 MMK     0.00   0.00     0.00   0.00     0.00     0.00
56        에티오피아 ETB     0.00   0.00     0.00   0.00     0.00     0.00
57       우즈베키스탄 UZS     0.00   0.00     0.00   0.00     0.00     0.00

   외화 수표 파실때   매매 기준율     환가 료율  미화 환산율
   외화 수표 파실때   매매 기준율     환가 료율  미화 환산율
   외화 수표 파실때   매매 기준율     환가 료율  미화 환산율
0    1469.47  1486.50   6.15079  1.0000
1    1007.90  1018.53   2.60318  0.6852
2    1612.51  1630.76   4.31600  1.0970
3       0.00   200.67   4.43712  0.1350
4     189.11   191.29   5.74800  0.1287
5      42.13    42.59   4.03366  0.0287
6       0.00    44.86   3.58766  0.0302
7       0.00    25.83   7.52400  0.0174
8    1086.49  1098.75   4.76033  0.7392
9     874.79   885.14   6.22766  0.5955
10      0.00     5.73   6.61166  0.0039
11   1877.72  1900.12   6.53300  1.2783
12   1030.85  1042.65   4.76900  0.7014
13      0.00   331.00   5.26066  0.2227
14      0.00    17.32   2.97500  0.0117
15      0.00    75.29   9.61100  0.0506
16    134.23   135.82   6.44133  0.0914
17    811.95   821.44   5.71166  0.5526
18    215.97   218.42   4.60800  0.1469
19      0.00    71.30  11.68300  0.0480
20      0.00     0.42  13.47500  0.0003
21   3895.56  3943.49   7.76900  2.6529
22      0.00    12.23  12.17370  0.0082
23      0.00   247.12  14.67000  0.1662
24      0.00  1098.75   4.67500  0.7392
25    391.22   395.99   7.47533  0.2664
26      0.00     4.96  11.50000  0.0033
27    146.95   148.61   4.40666  0.1000
28   1738.30  1756.99   2.32000  1.1820
29    400.10   404.70   5.07500  0.2723
30      0.00    11.13   5.97500  0.0075
31      0.00  3861.14   4.45500  2.5975
32      0.00  2096.61   8.73900  1.4104
33      0.00   393.30   6.56500  0.2646
34      0.00    28.99   5.97500  0.0195
35      0.00    17.23   9.06800  0.0116
36      8.74     8.83   8.42166  0.0059
37      0.00    64.69   5.73366  0.0435
38      0.00     1.49   6.12200  0.0010
39      0.00     2.87  16.97500  0.0019
40      0.00   407.82   3.35500  0.2743
41      0.00    11.48   9.78333  0.0077
42      0.00     0.34   0.00000  0.0002
43   4769.94  4824.42   4.65766  3.2455
44      0.00     0.55  10.27500  0.0004
45      0.00    39.20  49.80833  0.0264
46      0.00     5.30  18.24833  0.0036
47      0.00   381.78   8.13933  0.2568
48      0.00     4.00   8.44966  0.0027
49      0.00    10.77   0.00000  0.0072
50      0.00   185.58   0.00000  0.1248
51      0.00     0.37   0.00000  0.0002
52      0.00   633.84   0.00000  0.4264
53      0.00   267.29   0.00000  0.1798
54      0.00   327.66   7.75800  0.2204
55      0.00     0.71   0.00000  0.0005
56      0.00    11.24   0.00000  0.0076
57      0.00     0.11   0.00000  0.0001

In [6]:
df['date'] = "2025-04-08"
df

                 통화       현찰                              송금           \
                 통화     사실 때            파실 때            보낼 때     받을 때
                 통화       환율 Spread       환율 Spread     보낼 때     받을 때
0            미국 USD  1512.51   1.75  1460.49   1.75  1501.00  1472.00
1      일본 JPY (100)  1036.35   1.75  1000.71   1.75  1028.51  1008.55
2            유로 EUR  1663.21   1.99  1598.31   1.99  1647.06  1614.46
3            중국 CNY   210.70   5.00   190.64   5.00   202.67   198.67
4            홍콩 HKD   195.05   1.97   187.53   1.97   193.20   189.38
5            태국 THB    44.71   5.00    40.04   6.00    43.01    42.17
6            대만 TWD    50.73  13.10    40.38  10.00     0.00     0.00
7           필리핀 PHP    28.41  10.00    23.72   8.20    26.08    25.58
8          싱가포르 SGD  1120.61   1.99  1076.89   1.99  1109.73  1087.77
9            호주 AUD   902.57   1.97   867.71   1.97   893.99   876.29
10    베트남 VND (100)     6.40  11.80     5.06  11.80     5.78     5.68
11           영국 GBP  1937.55   1.97  1862.69   1.97  1919.12  1881.12
12          캐나다 CAD  1063.19   1.97  1022.11   1.97  1053.07  1032.23
13        말레이시아 MYR   355.49   7.40   306.51   7.40     0.00   327.69
14          러시아 RUB    18.96   9.50    14.29  17.50    17.92    16.72
15        남아공화국 ZAR    81.31   8.00    69.27   8.00    76.19    74.39
16         노르웨이 NOK   140.30   3.30   128.08   5.70   137.17   134.47
17         뉴질랜드 NZD   837.62   1.97   805.26   1.97   829.65   813.23
18          덴마크 DKK   225.62   3.30   205.98   5.70   220.60   216.24
19          멕시코 MXN    78.78  10.50    63.82  10.50    72.01    70.59
20           몽골 MNT     0.00   0.00     0.00   0.00     0.00     0.00
21          바레인 BHD  4195.87   6.40  3628.02   8.00  3982.92  3904.06
22        방글라데시 BDT     0.00   0.00     0.00   0.00     0.00     0.00
23          브라질 BRL   272.32  10.20   222.41  10.00     0.00   244.16
24         브루나이 BND  1142.70   4.00  1032.83   6.00     0.00     0.00
25      사우디아라비아 SAR   420.93   6.30   368.67   6.90   399.94   392.04
26         스리랑카 LKR     0.00   0.00     0.00   0.00     0.00     0.00
27          스웨덴 SEK   153.51   3.30   140.14   5.70   150.09   147.13
28          스위스 CHF  1791.60   1.97  1722.38   1.97  1774.55  1739.43
29    아랍에미리트공화국 AED   426.95   5.50   376.78   6.90   408.74   400.66
30          알제리 DZD     0.00   0.00     0.00   0.00     0.00     0.00
31           오만 OMR  4131.41   7.00  3590.87   7.00     0.00     0.00
32          요르단 JOD  2283.20   8.90  1928.89   8.00     0.00     0.00
33         이스라엘 ILS   432.63  10.00   361.84   8.00     0.00     0.00
34          이집트 EGP     0.00   0.00     0.00   0.00     0.00     0.00
35           인도 INR     0.00   0.00     0.00   0.00    17.42    17.04
36  인도네시아 IDR (100)     9.71  10.00     7.95  10.00     8.91     8.75
37           체코 CZK    70.18   8.50    58.87   9.00    65.40    63.98
38           칠레 CLP     1.63  10.00     1.35  10.00     0.00     0.00
39        카자흐스탄 KZT     0.00   0.00     0.00   0.00     0.00     0.00
40          카타르 QAR     0.00   0.00     0.00   0.00     0.00     0.00
41           케냐 KES     0.00   0.00     0.00   0.00     0.00     0.00
42         콜롬비아 COP     0.00   0.00     0.00   0.00     0.00     0.00
43         쿠웨이트 KWD  5138.00   6.50  4438.47   8.00  4872.66  4776.18
44         탄자니아 TZS     0.00   0.00     0.00   0.00     0.00     0.00
45         튀르키예 TRY     0.00   0.00     0.00   0.00    39.63    38.77
46         파키스탄 PKR     0.00   0.00     0.00   0.00     0.00     0.00
47          폴란드 PLN   412.32   8.00   351.24   8.00   385.97   377.59
48          헝가리 HUF     4.37   9.30     3.68   8.00     4.04     3.96
49           네팔 NPR     0.00   0.00     0.00   0.00     0.00     0.00
50          마카오 MOP     0.00   0.00     0.00   0.00     0.00     0.00
51         캄보디아 KHR     0.00   0.00     0.00   0.00     0.00     0.00
52           피지 FJD     0.00   0.00     0.00   0.00     0.00     0.00
53          리비아 LYD     0.00   0.00     0.00   0.00   269.96   264.62
54         루마니아 RON     0.00   0.00     0.00   0.00   331.26   324.06
55          미얀마 MMK     0.00   0.00     0.00   0.00     0.00     0.00
56        에티오피아 ETB     0.00   0.00     0.00   0.00     0.00     0.00
57       우즈베키스탄 UZS     0.00   0.00     0.00   0.00     0.00     0.00

   외화 수표 파실때   매매 기준율     환가 료율  미화 환산율        date
   외화 수표 파실때   매매 기준율     환가 료율  미화 환산율
   외화 수표 파실때   매매 기준율     환가 료율  미화 환산율
0    1469.47  1486.50   6.15079  1.0000  2025-04-08
1    1007.90  1018.53   2.60318  0.6852  2025-04-08
2    1612.51  1630.76   4.31600  1.0970  2025-04-08
3       0.00   200.67   4.43712  0.1350  2025-04-08
4     189.11   191.29   5.74800  0.1287  2025-04-08
5      42.13    42.59   4.03366  0.0287  2025-04-08
6       0.00    44.86   3.58766  0.0302  2025-04-08
7       0.00    25.83   7.52400  0.0174  2025-04-08
8    1086.49  1098.75   4.76033  0.7392  2025-04-08
9     874.79   885.14   6.22766  0.5955  2025-04-08
10      0.00     5.73   6.61166  0.0039  2025-04-08
11   1877.72  1900.12   6.53300  1.2783  2025-04-08
12   1030.85  1042.65   4.76900  0.7014  2025-04-08
13      0.00   331.00   5.26066  0.2227  2025-04-08
14      0.00    17.32   2.97500  0.0117  2025-04-08
15      0.00    75.29   9.61100  0.0506  2025-04-08
16    134.23   135.82   6.44133  0.0914  2025-04-08
17    811.95   821.44   5.71166  0.5526  2025-04-08
18    215.97   218.42   4.60800  0.1469  2025-04-08
19      0.00    71.30  11.68300  0.0480  2025-04-08
20      0.00     0.42  13.47500  0.0003  2025-04-08
21   3895.56  3943.49   7.76900  2.6529  2025-04-08
22      0.00    12.23  12.17370  0.0082  2025-04-08
23      0.00   247.12  14.67000  0.1662  2025-04-08
24      0.00  1098.75   4.67500  0.7392  2025-04-08
25    391.22   395.99   7.47533  0.2664  2025-04-08
26      0.00     4.96  11.50000  0.0033  2025-04-08
27    146.95   148.61   4.40666  0.1000  2025-04-08
28   1738.30  1756.99   2.32000  1.1820  2025-04-08
29    400.10   404.70   5.07500  0.2723  2025-04-08
30      0.00    11.13   5.97500  0.0075  2025-04-08
31      0.00  3861.14   4.45500  2.5975  2025-04-08
32      0.00  2096.61   8.73900  1.4104  2025-04-08
33      0.00   393.30   6.56500  0.2646  2025-04-08
34      0.00    28.99   5.97500  0.0195  2025-04-08
35      0.00    17.23   9.06800  0.0116  2025-04-08
36      8.74     8.83   8.42166  0.0059  2025-04-08
37      0.00    64.69   5.73366  0.0435  2025-04-08
38      0.00     1.49   6.12200  0.0010  2025-04-08
39      0.00     2.87  16.97500  0.0019  2025-04-08
40      0.00   407.82   3.35500  0.2743  2025-04-08
41      0.00    11.48   9.78333  0.0077  2025-04-08
42      0.00     0.34   0.00000  0.0002  2025-04-08
43   4769.94  4824.42   4.65766  3.2455  2025-04-08
44      0.00     0.55  10.27500  0.0004  2025-04-08
45      0.00    39.20  49.80833  0.0264  2025-04-08
46      0.00     5.30  18.24833  0.0036  2025-04-08
47      0.00   381.78   8.13933  0.2568  2025-04-08
48      0.00     4.00   8.44966  0.0027  2025-04-08
49      0.00    10.77   0.00000  0.0072  2025-04-08
50      0.00   185.58   0.00000  0.1248  2025-04-08
51      0.00     0.37   0.00000  0.0002  2025-04-08
52      0.00   633.84   0.00000  0.4264  2025-04-08
53      0.00   267.29   0.00000  0.1798  2025-04-08
54      0.00   327.66   7.75800  0.2204  2025-04-08
55      0.00     0.71   0.00000  0.0005  2025-04-08
56      0.00    11.24   0.00000  0.0076  2025-04-08
57      0.00     0.11   0.00000  0.0001  2025-04-08

# 날짜 생성하기
* 1995-01-03 ~ 2025-04-08(어제) 날짜 생성하기
* 월~금 평일만 날짜 생성
* 날짜 리스트에 모든 날짜 저장

In [7]:
import datetime

In [17]:
current_date < day

True

In [15]:
# weekdays() 는 월 0, 화 1, 수 2, 목 3, 금 4, 토 5, 일 6
for days in range(1, 10):
#     print(current_date + datetime.timedelta(days=days))
    day = current_date + datetime.timedelta(days=days)
    if day.weekday() < 5:
        print(day, day.weekday())

2025-04-09 2
2025-04-10 3
2025-04-11 4
2025-04-14 0
2025-04-15 1
2025-04-16 2
2025-04-17 3

# 시작일과 끝일을 입력해서 평일만 생성하기

In [25]:
start_date = datetime.date(2025, 4, 1)
end_date = datetime.date(2025, 4, 8)

In [26]:
date_list = []
while start_date <= end_date:
    # 평일인지 필터링
    if start_date.weekday() < 5:
        date_list.append(start_date)
    start_date += datetime.timedelta(days = 1)
date_list

[datetime.date(2025, 4, 1),
 datetime.date(2025, 4, 2),
 datetime.date(2025, 4, 3),
 datetime.date(2025, 4, 4),
 datetime.date(2025, 4, 7),
 datetime.date(2025, 4, 8)]

In [29]:
print(str(date_list[0]).replace("-",""))

20250401

# 코드 합쳐서 전체 날짜 데이터 추출하기

In [55]:
def new_col(df):
    new_cols = []
    for col in df.columns:
        if col[0] == col[1] == col[2]:
            new_cols.append(col[0].replace(" ",""))
        else:
            new_cols.append(" ".join(col).strip().replace(" ","_"))
    return new_cols

In [57]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from io import StringIO
import pandas as pd
import datetime
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time
from ex_dbio import to_ex_db

options = Options()
options.add_experimental_option("detach", True)
options.add_argument("start-maximized")
options.add_argument("Chrome/134.0.0.0")
options.add_argument("lang=ko_KR")

url = "https://www.kebhana.com/cms/rate/index.do?contentUrl=/cms/rate/wpfxd651_01i.do"
driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
    )
driver.get(url)

wait = WebDriverWait(driver, 10)

# 시작일과 끝일 설정
start_date = datetime.date(2025, 4, 1)
end_date = datetime.date(2025, 4, 2)

date_list = []
while start_date <= end_date:
    # 평일인지 필터링
    if start_date.weekday() < 5:
        date_list.append(start_date)
    start_date += datetime.timedelta(days = 1)
date_list

for date in date_list:
    # 날짜 입력
    
    date_input = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "#tmpInqStrDt")))
    date_input.clear()
    date_input.send_keys(str(date).replace("-",""))
    date_input.send_keys(Keys.ENTER)

    # 조회버튼 클릭
    search_button = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "#HANA_CONTENTS_DIV > div.btnBoxCenter > a")))
    search_button.click()
    time.sleep(2)
    df = pd.read_html(StringIO(driver.find_element(By.CSS_SELECTOR, ".tblBasic.leftNone").get_attribute("outerHTML")))[0]
    df["일자"] = date
    new_colums = new_col(df)
    df.columns = new_colums
    df = df[['일자', '통화', '현찰_사실_때_환율', '현찰_사실_때_Spread', '현찰_파실_때_환율', '현찰_파실_때_Spread',
       '송금_보낼_때_보낼_때', '송금_받을_때_받을_때', '외화수표파실때', '매매기준율', '환가료율', '미화환산율']]
    display(df)
    to_ex_db(df)

,일자,통화,현찰_사실_때_환율,현찰_사실_때_Spread,현찰_파실_때_환율,현찰_파실_때_Spread,송금_보낼_때_보낼_때,송금_받을_때_받을_때,외화수표파실때,매매기준율,환가료율,미화환산율
0,2025-04-01,미국 USD,1504.88,1.75,1453.12,1.75,1493.40,1464.60,1462.08,1479.00,6.14181,1.0000
1,2025-04-01,일본 JPY (100),1035.74,1.75,1000.12,1.75,1027.90,1007.96,1007.31,1017.93,2.59591,0.6883
2,2025-04-01,유로 EUR,1663.87,1.99,1598.95,1.99,1647.72,1615.10,1613.15,1631.41,4.32200,1.1030
3,2025-04-01,중국 CNY,210.45,5.00,190.41,5.00,202.43,198.43,0.00,200.43,4.34379,0.1355
4,2025-04-01,홍콩 HKD,194.32,1.97,186.82,1.97,192.47,188.67,188.41,190.57,5.73500,0.1289
5,2025-04-01,태국 THB,44.87,5.00,40.18,6.00,43.16,42.32,42.28,42.74,4.02533,0.0289
6,2025-04-01,대만 TWD,50.71,13.10,40.36,10.00,0.00,0.00,0.00,44.84,3.58766,0.0303
7,2025-04-01,필리핀 PHP,28.36,10.00,23.68,8.20,26.04,25.54,0.00,25.79,7.37000,0.0174
8,2025-04-01,싱가포르 SGD,1119.59,1.99,1075.91,1.99,1108.72,1086.78,1085.50,1097.75,4.75433,0.7422
9,2025-04-01,호주 AUD,906.68,1.97,871.66,1.97,898.06,880.28,878.77,889.17,6.22966,0.6012
10,2025-04-01,베트남 VND (100),6.37,11.80,5.03,11.80,5.75,5.65,0.00,5.70,6.60833,0.0039
11,2025-04-01,영국 GBP,1933.88,1.97,1859.16,1.97,1915.48,1877.56,1874.17,1896.52,6.53200,1.2823
12,2025-04-01,캐나다 CAD,1061.61,1.97,1020.61,1.97,1051.52,1030.70,1029.33,1041.11,4.75533,0.7039
13,2025-04-01,말레이시아 MYR,353.49,7.40,304.79,7.40,0.00,325.85,0.00,329.14,5.26066,0.2225
14,2025-04-01,러시아 RUB,18.80,9.50,14.17,17.50,17.77,16.57,0.00,17.17,2.97500,0.0116
15,2025-04-01,남아공화국 ZAR,81.31,8.00,69.27,8.00,76.19,74.39,0.00,75.29,9.60100,0.0509
16,2025-04-01,노르웨이 NOK,139.46,3.30,127.32,5.70,136.36,133.66,133.42,135.01,6.44233,0.0913
17,2025-04-01,뉴질랜드 NZD,838.29,1.97,805.91,1.97,830.32,813.88,812.60,822.10,5.69366,0.5558
18,2025-04-01,덴마크 DKK,225.67,3.30,206.02,5.70,220.65,216.29,216.02,218.47,4.60633,0.1477
19,2025-04-01,멕시코 MXN,78.56,10.50,63.64,10.50,71.81,70.39,0.00,71.10,11.68600,0.0481
20,2025-04-01,몽골 MNT,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.42,13.47500,0.0003
21,2025-04-01,바레인 BHD,4174.38,6.40,3609.43,8.00,3962.52,3884.06,3875.60,3923.29,7.77200,2.6527
22,2025-04-01,방글라데시 BDT,0.00,0.00,0.00,0.00,0.00,0.00,0.00,12.17,12.18010,0.0082
23,2025-04-01,브라질 BRL,270.94,10.20,221.29,10.00,0.00,242.92,0.00,245.87,14.51900,0.1662
24,2025-04-01,브루나이 BND,1141.66,4.00,1031.89,6.00,0.00,0.00,0.00,1097.75,4.67500,0.7422
25,2025-04-01,사우디아라비아 SAR,418.79,6.30,366.79,6.90,397.90,390.04,389.23,393.97,7.47766,0.2664
26,2025-04-01,스리랑카 LKR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,4.92,11.50000,0.0033
27,2025-04-01,스웨덴 SEK,152.95,3.30,139.64,5.70,149.55,146.59,146.41,148.07,4.40700,0.1001
28,2025-04-01,스위스 CHF,1786.89,1.97,1717.85,1.97,1769.89,1734.85,1733.73,1752.37,2.31100,1.1848
29,2025-04-01,아랍에미리트공화국 AED,424.80,5.50,374.88,6.90,406.68,398.64,398.08,402.66,5.07500,0.2723
30,2025-04-01,알제리 DZD,0.00,0.00,0.00,0.00,0.00,0.00,0.00,11.09,8.22500,0.0075
31,2025-04-01,오만 OMR,4110.14,7.00,3572.38,7.00,0.00,0.00,0.00,3841.26,4.62500,2.5972
32,2025-04-01,요르단 JOD,2271.69,8.90,1919.16,8.00,0.00,0.00,0.00,2086.04,8.73900,1.4104
33,2025-04-01,이스라엘 ILS,428.85,10.00,358.69,8.00,0.00,0.00,0.00,389.87,6.56500,0.2636
34,2025-04-01,이집트 EGP,0.00,0.00,0.00,0.00,0.00,0.00,0.00,28.62,8.22500,0.0194
35,2025-04-01,인도 INR,0.00,0.00,0.00,0.00,17.27,16.89,0.00,17.08,9.06233,0.0115
36,2025-04-01,인도네시아 IDR (100),9.66,10.00,7.92,10.00,8.87,8.71,8.70,8.79,8.42166,0.0059
37,2025-04-01,체코 CZK,70.31,8.50,58.98,9.00,65.52,64.10,0.00,64.81,5.73500,0.0438
38,2025-04-01,칠레 CLP,1.62,10.00,1.34,10.00,0.00,0.00,0.00,1.48,6.17100,0.0010
39,2025-04-01,카자흐스탄 KZT,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2.84,16.97500,0.0019
40,2025-04-01,카타르 QAR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,405.73,3.35500,0.2743
41,2025-04-01,케냐 KES,0.00,0.00,0.00,0.00,0.00,0.00,0.00,11.43,9.77500,0.0077
42,2025-04-01,콜롬비아 COP,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.33,0.00000,0.0002
43,2025-04-01,쿠웨이트 KWD,5123.05,6.50,4425.55,8.00,4858.48,4762.28,4756.06,4810.38,4.65766,3.2525
44,2025-04-01,탄자니아 TZS,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.55,10.36666,0.0004
45,2025-04-01,튀르키예 TRY,0.00,0.00,0.00,0.00,39.33,38.49,0.00,38.91,50.17500,0.0263
46,2025-04-01,파키스탄 PKR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,5.27,18.12166,0.0036
47,2025-04-01,폴란드 PLN,411.64,8.00,350.66,8.00,385.34,376.96,0.00,381.15,8.13266,0.2577
48,2025-04-01,헝가리 HUF,4.36,9.30,3.68,8.00,4.03,3.95,0.00,3.99,8.44066,0.0027
49,2025-04-01,네팔 NPR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,10.67,0.00000,0.0072
50,2025-04-01,마카오 MOP,0.00,0.00,0.00,0.00,0.00,0.00,0.00,184.89,0.00000,0.1250
51,2025-04-01,캄보디아 KHR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.37,0.00000,0.0003
52,2025-04-01,피지 FJD,0.00,0.00,0.00,0.00,0.00,0.00,0.00,633.46,0.00000,0.4283
53,2025-04-01,리비아 LYD,0.00,0.00,0.00,0.00,268.59,263.29,0.00,265.94,0.00000,0.1798
54,2025-04-01,루마니아 RON,0.00,0.00,0.00,0.00,331.36,324.16,0.00,327.76,7.75633,0.2216
55,2025-04-01,미얀마 MMK,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.70,0.00000,0.0005
56,2025-04-01,에티오피아 ETB,0.00,0.00,0.00,0.00,0.00,0.00,0.00,11.18,0.00000,0.0076
57,2025-04-01,우즈베키스탄 UZS,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.11,0.00000,0.0001

OperationalError: (pymysql.err.OperationalError) (1049, "Unknown database 'excnage_rate'")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [49]:
def new_col(df):
    new_cols = []
    for col in df.columns:
        if col[0] == col[1] == col[2]:
            new_cols.append(col[0].replace(" ",""))
        else:
            new_cols.append(" ".join(col).strip().replace(" ","_"))
    return new_cols

In [50]:
new_cols

['통화',
 '현찰_사실_때_환율',
 '현찰_사실_때_Spread',
 '현찰_파실_때_환율',
 '현찰_파실_때_Spread',
 '송금_보낼_때_보낼_때',
 '송금_받을_때_받을_때',
 '외화수표파실때',
 '매매기준율',
 '환가료율',
 '미화환산율',
 '일자']

In [51]:
df.columns = new_cols
df.columns

Index(['통화', '현찰_사실_때_환율', '현찰_사실_때_Spread', '현찰_파실_때_환율', '현찰_파실_때_Spread',
       '송금_보낼_때_보낼_때', '송금_받을_때_받을_때', '외화수표파실때', '매매기준율', '환가료율', '미화환산율',
       '일자'],
      dtype='object')

In [53]:
df = df[['일자', '통화', '현찰_사실_때_환율', '현찰_사실_때_Spread', '현찰_파실_때_환율', '현찰_파실_때_Spread',
       '송금_보낼_때_보낼_때', '송금_받을_때_받을_때', '외화수표파실때', '매매기준율', '환가료율', '미화환산율']]
df

,일자,통화,현찰_사실_때_환율,현찰_사실_때_Spread,현찰_파실_때_환율,현찰_파실_때_Spread,송금_보낼_때_보낼_때,송금_받을_때_받을_때,외화수표파실때,매매기준율,환가료율,미화환산율
0,2025-04-02,미국 USD,1493.18,1.75,1441.82,1.75,1481.80,1453.20,1450.69,1467.50,6.16896,1.0000
1,2025-04-02,일본 JPY (100),1007.50,1.75,972.86,1.75,999.88,980.48,979.85,990.18,2.58136,0.6747
2,2025-04-02,유로 EUR,1618.38,1.99,1555.24,1.99,1602.67,1570.95,1569.05,1586.81,4.33300,1.0813
3,2025-04-02,중국 CNY,209.71,5.00,189.75,5.00,201.72,197.74,0.00,199.73,4.03924,0.1361
4,2025-04-02,홍콩 HKD,192.26,1.97,184.84,1.97,190.43,186.67,186.40,188.55,5.82466,0.1285
5,2025-04-02,태국 THB,44.75,5.00,40.07,6.00,43.04,42.20,42.16,42.62,4.06700,0.0290
6,2025-04-02,대만 TWD,49.92,13.10,39.73,10.00,0.00,0.00,0.00,44.14,3.58633,0.0301
7,2025-04-02,필리핀 PHP,28.22,10.00,23.56,8.20,25.91,25.41,0.00,25.66,7.30900,0.0175
8,2025-04-02,싱가포르 SGD,1108.63,1.99,1065.37,1.99,1097.87,1076.13,1074.85,1087.00,4.79033,0.7407
9,2025-04-02,호주 AUD,933.23,1.97,897.19,1.97,924.36,906.06,904.51,915.21,6.21633,0.6237
10,2025-04-02,베트남 VND (100),6.41,11.80,5.07,11.80,5.79,5.69,0.00,5.74,6.63833,0.0039
11,2025-04-02,영국 GBP,1943.31,1.97,1868.23,1.97,1924.82,1886.72,1883.31,1905.77,6.53666,1.2987
12,2025-04-02,캐나다 CAD,1046.33,1.97,1005.91,1.97,1036.38,1015.86,1014.50,1026.12,4.80266,0.6992
13,2025-04-02,말레이시아 MYR,353.86,7.40,305.10,7.40,0.00,326.19,0.00,329.48,5.26033,0.2245
14,2025-04-02,러시아 RUB,19.07,9.50,14.38,17.50,18.02,16.82,0.00,17.42,2.97500,0.0119
15,2025-04-02,남아공화국 ZAR,83.67,8.00,71.29,8.00,78.40,76.56,0.00,77.48,9.66233,0.0528
16,2025-04-02,노르웨이 NOK,145.17,3.30,132.53,5.70,141.94,139.14,138.89,140.54,6.43333,0.0958
17,2025-04-02,뉴질랜드 NZD,851.97,1.97,819.07,1.97,843.87,827.17,825.85,835.52,5.77166,0.5693
18,2025-04-02,덴마크 DKK,219.68,3.30,200.55,5.70,214.79,210.55,210.28,212.67,4.66533,0.1449
19,2025-04-02,멕시코 MXN,79.76,10.50,64.62,10.50,72.91,71.47,0.00,72.19,11.66900,0.0492
20,2025-04-02,몽골 MNT,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.42,13.47500,0.0003
21,2025-04-02,바레인 BHD,4141.91,6.40,3581.36,8.00,3931.70,3853.86,3845.47,3892.78,7.76600,2.6527
22,2025-04-02,방글라데시 BDT,0.00,0.00,0.00,0.00,0.00,0.00,0.00,12.08,12.18010,0.0082
23,2025-04-02,브라질 BRL,285.42,10.20,233.11,10.00,0.00,255.91,0.00,259.01,14.29800,0.1765
24,2025-04-02,브루나이 BND,1130.48,4.00,1021.78,6.00,0.00,0.00,0.00,1087.00,4.67500,0.7407
25,2025-04-02,사우디아라비아 SAR,415.81,6.30,364.18,6.90,395.08,387.26,386.45,391.17,7.47566,0.2666
26,2025-04-02,스리랑카 LKR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,4.96,11.50000,0.0034
27,2025-04-02,스웨덴 SEK,152.57,3.30,139.29,5.70,149.17,146.23,146.06,147.70,4.40633,0.1006
28,2025-04-02,스위스 CHF,1699.20,1.97,1633.56,1.97,1683.04,1649.72,1648.63,1666.38,2.36233,1.1355
29,2025-04-02,아랍에미리트공화국 AED,421.50,5.50,371.97,6.90,403.52,395.54,394.98,399.53,5.07500,0.2723
30,2025-04-02,알제리 DZD,0.00,0.00,0.00,0.00,0.00,0.00,0.00,10.96,3.97500,0.0075
31,2025-04-02,오만 OMR,4078.72,7.00,3545.06,7.00,0.00,0.00,0.00,3811.89,4.29500,2.5975
32,2025-04-02,요르단 JOD,2254.03,8.90,1904.24,8.00,0.00,0.00,0.00,2069.82,8.73900,1.4104
33,2025-04-02,이스라엘 ILS,434.69,10.00,363.57,8.00,0.00,0.00,0.00,395.18,6.56500,0.2693
34,2025-04-02,이집트 EGP,0.00,0.00,0.00,0.00,0.00,0.00,0.00,29.02,3.97500,0.0198
35,2025-04-02,인도 INR,0.00,0.00,0.00,0.00,17.36,16.98,0.00,17.17,9.07966,0.0117
36,2025-04-02,인도네시아 IDR (100),9.76,10.00,8.00,10.00,8.96,8.80,8.79,8.88,8.42166,0.0061
37,2025-04-02,체코 CZK,69.03,8.50,57.91,9.00,64.32,62.94,0.00,63.63,5.73366,0.0434
38,2025-04-02,칠레 CLP,1.69,10.00,1.39,10.00,0.00,0.00,0.00,1.54,6.17100,0.0010
39,2025-04-02,카자흐스탄 KZT,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2.92,16.97500,0.0020
40,2025-04-02,카타르 QAR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,402.58,3.35500,0.2743
41,2025-04-02,케냐 KES,0.00,0.00,0.00,0.00,0.00,0.00,0.00,11.35,9.75833,0.0077
42,2025-04-02,콜롬비아 COP,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.35,0.00000,0.0002
43,2025-04-02,쿠웨이트 KWD,5070.84,6.50,4380.46,8.00,4808.97,4713.75,4707.66,4761.36,4.61200,3.2445
44,2025-04-02,탄자니아 TZS,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.56,10.05666,0.0004
45,2025-04-02,튀르키예 TRY,0.00,0.00,0.00,0.00,39.13,38.29,0.00,38.71,48.34166,0.0264
46,2025-04-02,파키스탄 PKR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,5.24,18.37500,0.0036
47,2025-04-02,폴란드 PLN,409.96,8.00,349.24,8.00,383.77,375.43,0.00,379.60,8.14000,0.2587
48,2025-04-02,헝가리 HUF,4.31,9.30,3.64,8.00,3.99,3.91,0.00,3.95,8.46133,0.0027
49,2025-04-02,네팔 NPR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,10.73,0.00000,0.0073
50,2025-04-02,마카오 MOP,0.00,0.00,0.00,0.00,0.00,0.00,0.00,182.96,0.00000,0.1247
51,2025-04-02,캄보디아 KHR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.37,0.00000,0.0003
52,2025-04-02,피지 FJD,0.00,0.00,0.00,0.00,0.00,0.00,0.00,630.44,0.00000,0.4296
53,2025-04-02,리비아 LYD,0.00,0.00,0.00,0.00,306.47,300.41,0.00,303.44,0.00000,0.2068
54,2025-04-02,루마니아 RON,0.00,0.00,0.00,0.00,322.30,315.30,0.00,318.80,7.76766,0.2172
55,2025-04-02,미얀마 MMK,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.70,0.00000,0.0005
56,2025-04-02,에티오피아 ETB,0.00,0.00,0.00,0.00,0.00,0.00,0.00,11.15,0.00000,0.0076
57,2025-04-02,우즈베키스탄 UZS,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.11,0.00000,0.0001